### ISSUE TITLE
[NumericInput] Support custom formatting

### ISSUE THREAD

**Issue by jakobz** [epam/UUI#1010]
## Description

In certain cases, we need to allow overriding standard Intl-based formatting. 

E.g.:
AED -100.00
instead of 
-AED 100.00 (with currencyDisplay: 'symbol')
or
-100,00 AED (with currencyDisplay: 'code')

## Describe the solution you'd like

Let's add a new prop to the NumericInput, which would override the standard formatting:

    /**
     * A function to convert current input value to displayed text.
     * Overrides standard Intl-based formatting. If passed, formatOptions prop is ignored.
     * Note, that formatting is used only in read-mode, when input is out of focus.
     */
    formatValue?(value: number): string;

value = "USD " + value
10000 => "десять тысяч ровно"

**Comment by NatalliaAlieva** [comment]
Released in 4.10.1 version.
