### ISSUE TITLE
[ContextProvider] Doesn't replace screen with appropriate error screen if 503-error occurs.

### ISSUE THREAD

**Issue by mikhail-burnin-epam** [epam/UUI#1015]
## Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ x ] I am running the latest version
- [ x ] I checked the documentation and found no answer
- [ x ] I checked to make sure that this issue has not already been filed

## Description
There is the defined properly ContextProvider props loadAppContext and apiPingPath. When the result status of loadAppContext is 503, api ping is triggered and gets 503 error repeatedly, but the user screen isn't automatically changed. It seems an error occurs within the context provider.

## Environment

* UUI version: 4.9.1
* Browser name: Google Chrome Version 109.0.5414.120
* Operating System: Windows 10 Enterprise 19045.2486

**Comment by AlekseyManetov** [comment]
Try to use new approach with `useUUIServices`, which supposed that `appContext` loading will be performed on your side, for more details see this example - https://uui.epam.com/documents?id=contextProvider&mode=doc&skin=UUI4_promo&category=contexts#example_(advanced).
The `ContextProvider` component now deprecated and will be removed in feature.
