### ISSUE TITLE
[Filters Panel] No possibility to close the filter modal window by clicking on the cross icon on the mobile phone

### ISSUE THREAD

**Issue by AleksSam2020** [epam/UUI#1019]
- [x] I am running the latest version

## Description
doesn't work cross button and dropdown list on mobile phone looks different from other picker inputs
![image](https://user-images.githubusercontent.com/76586401/216617017-ddf8d7c5-b7f4-4405-a043-dfa9f683c13e.png)

**Comment by NatalliaAlieva** [comment]
Video from UUI.epam.com

https://user-images.githubusercontent.com/57751283/216816742-510ba16a-b3da-4e02-a345-fb3032baf897.mp4

**Comment by NatalliaAlieva** [comment]
Released in 5.0.0 ver.
