### ISSUE TITLE
[FiltersPanel]: hide 'add filter' button in case when all filters has 'isAlwaysVisible': true flag

### ISSUE THREAD

**Issue by AleksSam2020** [epam/UUI#1020]
## Now
Can't hide 'add filter' button
## To Do
It needs possibility to hide 'add filter' button

## Describe the solution you'd like (optional)
Hide 'add filter' button in case when all filters has 'isAlwaysVisible': true flag

**Comment by NatalliaAlieva** [comment]
Released in 5.0.0 ver.
