### ISSUE TITLE
[RichTextEditor]  No autofocus for input field in add link modal

### ISSUE THREAD

**Issue by nadiushkaNA** [epam/UUI#1030]
## Steps to Reproduce
https://user-images.githubusercontent.com/11243577/217539739-556b3b36-94af-4a05-9a3a-ead0db5c8dbe.mp4

## Actual result
no focus in input

## Expected result
autofocus after opened modal

**Comment by NatalliaAlieva** [comment]
Released in 5.1.0 ver.
