### ISSUE TITLE
[ApiContext] Relogin logic is broken in some login scenarios

### ISSUE THREAD

**Issue by jakobz** [epam/UUI#1039]
## Now

Currently, ApiContext has the following code:

// If this window is opened by another app in another window to re-login, tell it that Auth was passed ok
window.opener && window.location.pathname === this.props.apiReloginPath && window.opener.postMessage("authSuccess", "*");

This is done to make apps which perform login on server (e.g. via redirects to SSO), and doesn't handle /auth/login path themselves, to support UUI re-login feature: 
- upon detecting session lost (401 response), UUI opens another window on /auth/login path
- we expect that the server will handle the login
- after login is completed - UUI app is opened as usual on /auth/login path
- In this case, UUI signals window.opener to close this window and continue

However, if an app decides to implement /auth/login page on top of UUI, e.g. a form with login/password entry, re-login will be broken - as this window will be closed immediately by the code above, w/o actually logging-in user.

## Describe the solution you'd like (optional)

Let's remove this code:
// If this window is opened by another app in another window to re-login, tell it that Auth was passed ok
 window.opener && window.location.pathname === this.props.apiReloginPath && window.opener.postMessage("authSuccess", "*");

Let's communicate this change to apps (via change log), as following:

ApiContext: removed the code which handles /auth/login for the apps, which doesn't handle this themselves.

If an app doesn't handle /auth/login correctly, this needs to be implemented implicitly. There are several options:

1. Handle /auth/login path server-side. Server should log in user (via redirects to SSO), and - after success, return the following HTML: 
<html><script>window.opener && window.opener.postMessage("authSuccess", "*")</script></html>

2. Handle /auth/login path client-side. The simplest method is to add the following to the index.js:
window.opener && window.location.pathname === '/auth/login' && window.opener.postMessage("authSuccess", "*");

3. If an app implements UUI-based login pages, they need to run the following code after successful login: window.opener && window.opener.postMessage("authSuccess", "*") 

Let's also remove outdated docs regarding auth lost scenario. We don't need 'x-session-lost' header anymore. Replace this:

> The server is required to return 401 with the custom 'x-session-lost: true' header if auth cookie is not found or invalid during XHR call. This is required because ordinary login redirect responses can't be detected from JS during XHR calls. 

To this:

 > Authentication/session lost is detected by 401 server response.

**Comment by AlekseyManetov** [comment]
Released in 5.0.0 ver.
