### ISSUE TITLE
[TextAreal][Firefox]: long placeholder is trimmed

### ISSUE THREAD

**Issue by JuliaMV** [epam/UUI#1043]
## Steps to Reproduce

Create TextArea componet with long placeholer and autoSize prop or open a link in Mozila Firefox https://uui.epam.com/documents?category=components&id=textArea&mode=propsEditor&skin=UUI4_promo

## Actual result

Placeholder is trimmed.

![2023-02-14_17h13_53](https://user-images.githubusercontent.com/37875890/218766151-de95c1e2-a70b-44dd-a9d5-1c54f0d2d62d.png)

## Expected result

A placeholder in TextArea is visible

## Environment

* UUI version: latest
* Browser name: Firefox
* Operating System: at least WinOS

**Comment by AlekseyManetov** [comment]
This is a [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1239595) of Firefox
