### ISSUE TITLE
[Button][LinkButton][IconButton] Disabled button doesn't have `disabled` prop `true`

### ISSUE THREAD

**Issue by cpof-tea** [epam/UUI#1057]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Description

[Cloud Codesandbox](https://codesandbox.io/p/sandbox/disabled-prop-on-buttons-7hli0p?file=%2Fsrc%2FExample.test.tsx). Re-run **test** task to see failed tests.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Render `Button`/`LinkButton`/`IconButton` as disabled button (with `isDisabled={true}` prop, without `link` or `href` props)
2. Check `disabled` property

## Actual result

`disabled` is `false`

## Expected result
`disabled` is `true`

## Environment

* UUI version: 4.9.2
* Browser name: FF 110.0
* Operating System: Ubuntu 20.04

**Comment by NatalliaAlieva** [comment]
Released in 4.10.1 ver.

**Comment by vik753** [comment]
Hi everyone! We rolled back to the previous state for disabled Button/LinkButton/IconButton without the native disabled attribute. The disabled attribute broke our tooltips, at least, because the disabled attribute prevents all events on its component. To check if these components are disabled, we use the 'uui-disabled' class and aria-disabled="true" attribute.

**Comment by cpof-tea** [comment]
> The disabled attribute broke our tooltips, at least, because the disabled attribute prevents all events on its component.

Could you please, provide some sandbox example?

**Comment by vik753** [comment]
> > The disabled attribute broke our tooltips, at least, because the disabled attribute prevents all events on its component.
> 
> Could you please, provide some sandbox example?

Example: https://codesandbox.io/s/uui-forked-1w2hhr?file=/Example.tsx

**Comment by cpof-tea** [comment]
> Example: https://codesandbox.io/s/uui-forked-1w2hhr?file=/Example.tsx

I can confirm, that FE and Chromium behaves differently in this terms. FF does trigger events to show tooltip in provided example, Chromium - doesn't. 

Checked further `onmouseenter` `onmousemove` `onmouseleave` on plain `<button disabled>`.
Only `onmouseleave` triggered in FF.
In Chromium - none.

Last, not least. MDN says ([HTML attribute: disabled](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled)):

> If the disabled attribute is specified on a form control, the element and its form control descendants do not participate in constraint validation. Often browsers grey out such controls and it won't receive any browsing events, like mouse clicks or focus-related ones.

But W3C ([HTML Standard, 4.10.18.5](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#enabling-and-disabling-form-controls:-the-disabled-attribute)):

> A form control that is [disabled](https://html.spec.whatwg.org/#concept-fe-disabled) must prevent any [click](https://w3c.github.io/uievents/#event-type-click) events that are [queued](https://html.spec.whatwg.org/#queue-a-task) on the [user interaction task source](https://html.spec.whatwg.org/#user-interaction-task-source) from being dispatched on the element.

Inconsistent buggy crossbrowser behavior

**Comment by AlekseyManetov** [comment]
I believe that we should not add the "disable" attribute by default due to the issues described above. But if for some reason you still need it, you can provide it via `rawProps` for cases where it doesn't break any other behavior.
