### ISSUE TITLE
Integration with user-event doesn't work

### ISSUE THREAD

**Issue by GrigoriiBerezin** [epam/UUI#1083]
## Description

I'm trying to reproduce user click on the button, but it doesn't work at all

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Create Button component with onClick event `<Button onClick={() => console.log('Clicked')}>Test</Button>`
2. Create test and try to click on the button `user = userEvent.setup(); const b = await user.findAllByRole('button'); user.click(b[0])`

## Actual result

Empty console

## Expected result

Console should have 'Clicked' line

## Environment

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* UUI version: 4.8.5
* user-event version: 14.4.3

**Comment by AlekseyManetov** [comment]
Could you please create [codesanbox](https://codesandbox.io/s/svlt6m?file=/Example.tsx) or any other environment, that we will be able to debug this case. We don't use userEvent in our tests, so can't check this integration under our codebase.

**Comment by GrigoriiBerezin** [comment]
Sure, I've created the sandox with code for introducoing the bug, but I have found that the problem was not in Button component of epam, but in user-event setup settings. So now it works fell, sorry for that
https://codesandbox.io/s/wandering-lake-uzzy5m?file=/src/components/ButtonToClick.test.tsx
And the link to the issue on userEvent github just in case
https://github.com/testing-library/user-event/issues/1054

**Comment by AlekseyManetov** [comment]
Great! So i can close this issue?
