### ISSUE TITLE
[GlobalMenu] Component should be button

### ISSUE THREAD

**Issue by cpof-tea** [epam/UUI#1103]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Description
[Cloud Codesandbox](https://codesandbox.io/p/sandbox/globalmenu-as-a-button-30etbl?file=%2Fsrc%2FExample.test.tsx). Re-run **test** task to see failed tests.

## Steps to Reproduce

1. Render `GlobalMenu` component

## Actual result

Component rendered as non-focusable non-interactive `<div>` element

## Expected result

Component rendered as focusable interactive `<button>` element

## Environment

* UUI version: 4.10.1
* Browser name: FF 110.0.1
* Operating System: Ubuntu 20.04

**Comment by NatalliaAlieva** [comment]
Released in 5.0.0 ver.
