### ISSUE TITLE
[Tooltip] Can't use `closeOnMouseLeave="boundary"` with `closeDelay={0}`

### ISSUE THREAD

**Issue by vasilii-kovalev** [epam/UUI#1113]
## Description

When using `closeOnMouseLeave="boundary"` and  `closeDelay={0}`, the closing delay is ignored, and a default fallback is used.

## Steps to Reproduce

1. Go to this [CodeSandbox](https://codesandbox.io/s/uui-tooltip-close-delay-and-close-mouse-leave-issue-xf5lwt?file=/example.tsx:247-257)
2. Hover over "Button 1", then "Button 2", then "Button 1". It is reproduced more often when hovering over paddings of the button instead of the text content

## Actual result

The tooltips stick on the screen and hide after changing the hover target after a second or two.

## Expected result

The tooltips hide immediately after changing the hover target.

## Environment

UUI version: 4.10.1
Browser name: Google Chrome v.111.0.5563.65
Operating System: Windows 10 64-bit

## Notes

Most probably, the bug is caused by this line:
https://github.com/epam/UUI/blob/main/uui-components/src/overlays/Dropdown.tsx#L166
Since `0` is a "falsy" value, the logical OR operator (`||`) chooses the fallback instead. To fix this issue, it is necessary to change it the to nullish coalescing operator (`??`), which chooses the fallback only if the value is `null` or `undefined`.

Until it is fixed, one can use `closeDelay={1}` instead.

**Comment by vasilii-kovalev** [comment]
`closeOnMouseLeave="boundary"` is used as a workaround for this issue: https://github.com/epam/UUI/issues/1094.

**Comment by NatalliaAlieva** [comment]
Released in 4.10.2 ver.
