### ISSUE TITLE
[Picker List] Picker List with Lazy Tree don`t check parent node in modalWindow

### ISSUE THREAD

**Issue by RealOneReal** [epam/UUI#1123]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Description
In Picker List if we have checked children node and click btn to open modal -> we we don`t see checked parent node with '-'
## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1.  In picker List check some child
2.  Open modalWindow

## Actual result
![image](https://user-images.githubusercontent.com/78467676/225420931-cba12c2c-3c63-4bb5-a8f1-386f173af8eb.png)

What is the current behavior?

https://codesandbox.io/s/uui-forked-jfr905?file=/Example.tsx

## Expected result

Please describe the behavior you are expecting

Parent node should be checked with '-'

## Environment

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* UUI version: last
* Browser name: Chrome
* Operating System: Windows10

**Comment by AlekseyManetov** [comment]
Please also check the same case for PickerInput, but with some initial value from scratch. It's seems that we have the same issue too.

**Comment by RealOneReal** [comment]
> Please also check the same case for `PickerInput`, but with some initial value from scratch. It's seems that we have the same issue too.

You are right - in 'modal' editMode picker Input also work bad :
![image](https://user-images.githubusercontent.com/78467676/226120995-bf950d89-343f-495a-b97a-2e603a9574f8.png)

But in dropDown mode picker works well

**Comment by RealOneReal** [comment]
Would you please inform when we should wait fix ?

**Comment by AlekseyManetov** [comment]
Currently this issue in our backlog. Is this a critical issue for you? Could you please share your expected deadlines for the fix?

**Comment by RealOneReal** [comment]
It`s not critical bug for us, but It will be great if you can fix this issue in one of the nearest updates. Thanx.

**Comment by AlekseyManetov** [comment]
released in 5.0.0 ver.
