### ISSUE TITLE
[PickerInput]: hover doesn't appear on "parent" when pointing the mouse

### ISSUE THREAD

**Issue by NatalliaAlieva** [epam/UUI#1131]
## Steps to Reproduce

1. Open [Codesandbox](https://codesandbox.io/s/cascadesingleselection-forked-fi2top?file=/src/App.tsx).
2. Expand the whole tree.
3. Position the mouse over the "parent".

## Actual result

Hover doesn't appear on the "parent". Hover appears only on the "child".

https://user-images.githubusercontent.com/57751283/225926157-ef0e4a5e-d64f-4b04-ae27-c9e87b809850.mp4

## Expуcted result

The hover appears over both "parents" and "children". 

## Environment

* UUI version: 4.10.1
* Browser name: any
* Operating System: any

**Comment by AlekseyManetov** [comment]
Released in 5.0.0 ver.
