### ISSUE TITLE
[Modals]: controls are not visible if the modal window does not fit on the screen

### ISSUE THREAD

**Issue by mikzakh** [epam/UUI#1136]
## Description
On mobile devices modal goes beyond the visible part of the screen.

## Steps to Reproduce

1. Go to modal examples in [documentation](https://uui.epam.com/documents?id=modals&mode=doc&skin=UUI4_promo&category=components).
2. Open first 'Basic' example on mobile device (e.g. Huawei P30, Google Pixel 5).

## Actual result

![modal](https://user-images.githubusercontent.com/97105597/226400134-f08d0c38-fcd8-4c09-9fdd-513ffbd468d9.png)

## Expected result

Modal doesn't exceed visible part of the screen.

## Environment

* UUI version: 4.10.0
* Browser name: Chrome
* Operating System: Android 13

**Comment by NatalliaAlieva** [comment]
Released in 5.2.0 version.
