### ISSUE TITLE
PickerInput - impossible to use TextInput / SearchInput as a toggler

### ISSUE THREAD

**Issue by jakobz** [epam/UUI#1165]
## Steps to Reproduce

Here's sandbox: https://codesandbox.io/s/uui-picker-input-with-textinput-as-toggler-mmft9o?file=/Example.tsx

1. Type 'a' into the input
2. Dropdown opens
3. Click any city
4. Dropdown closes, and no city is not selected

Expected:
- city is selected
- dropdown shouldn't close, until I click outside 
- is we set selectionMode='single' - dropdown should close after selecting

Note that selection with keyboard still works. E.g. you can press Down and then Enter, and get items selected. I suspect we have defect in the dropdown closing logic, maybe click outside detection is broken in this case.

The most common usage for this is search input, e.g. to find a person, and redirect to some page after user selects one.
Here's an example:
https://codesandbox.io/s/uui-search-dropdown-with-navigate-on-select-02hvl5?file=/Example.tsx 

Let's add a similar example to our PickerInput docs.

**Comment by NatalliaAlieva** [comment]
Released in 5.0.0 ver.
