### ISSUE TITLE
[Rating]: remove invalid state

### ISSUE THREAD

**Issue by AlekseyManetov** [epam/UUI#1168]
## Description
Now in Rating component with `isInvalid={ true }` prop, we fill all start by red color, which make them unreachable for hover effects and visually displayed them as selected.
![image](https://user-images.githubusercontent.com/14283670/228506256-860eb02b-46ab-41a5-a3ad-f6d6a42c9ebf.png)

## Expected result
For validation it's enough to place only validation message by`LabeledInput` component, we don't need to have some additional styles for invalid mode, so we can remove `isInvalid` prop and styles which was provided by mode.

**Comment by NatalliaAlieva** [comment]
Released in 5.0.0 ver.
