### ISSUE TITLE
[FiltersPanel]: show only selected toogle isn't visible

### ISSUE THREAD

**Issue by JuliaMV** [epam/UUI#1174]
## Steps to Reproduce

Create FitlersPanel with LazyDatasource that has parameter selectAll = false.
![2023-03-29_16h11_01](https://user-images.githubusercontent.com/37875890/228824319-f1030c74-e5fb-4958-9db2-8581887362c9.png)

## Actual result
Show only selected toggle is hidden.

## Expected result
Show only selected toggle is available for users.

## Environment

* UUI version: lates
* Browser name: all
* Operating System: all

**Comment by NatalliaAlieva** [comment]
Released in 5.0.0 ver.
