### ISSUE TITLE
Reduce selectors specificity in components

### ISSUE THREAD

**Issue by vasilii-kovalev** [epam/UUI#1179]
## Now

Right now, in order to add styles according to some behavior (clickable, focusable, invalid, etc.), components have classes stacked together. That's how it looks:

![image](https://user-images.githubusercontent.com/10310491/229035309-7924631d-9fcb-4e15-b468-6225e83e8569.png)

As the picture above shows, to add some styles, related to a particular size, or mode, it is necessary to stack 3 classes in a single selector, which increases its specificity. From the user perspective, in order to override such styles, it is necessary to:
1. Use the combination of local and global (UUI) styles, like `.textInput:global(.uui-input-box)` (when using CSS Modules)
2. Use `!important` in the local styles
3. Duplicate local classes (like `.textInput.textInput.textInput`) to increase specificity
4. Combine these techniques

All that has a negative impact on the code readability and makes it fragile. Not to mention, that it also introduces the specificity fighting when it is necessary to add behavior on top of the local selectors (with already high specificity), like add custom focus/invalid state styles on top of the custom default styles.

Sometimes, for simple cases (like buttons), it is easier to use native `button` element instead of fighting that high specificity in the UUI components.

## To Do

Here's what can help to solve the problem:
1. Reduce the classes amount in the stacks. Ideally, don't stack them at all
2. Use CSS cascade (place the "focus" styles below the default ones)
3. Combine selectors with [`:where`](https://developer.mozilla.org/en-US/docs/Web/CSS/:where) if possible

**Comment by AlekseyManetov** [comment]
Thank you for your suggestion. We are working on reducing the specificity of our selectors, such as removing `.root` in some cases. However, it's not always possible to write CSS without any cascading, and we don't aim to eliminate it entirely. While we offer the `cx` prop for customization, it should only be used in rare and exceptional cases. It's important to note that such customization is not stable and can cause unexpected problems, especially when we rework our components, change the component DOM structure, or rewrite our CSS. Therefore, it's recommended to minimize the use of `cx` and avoid it whenever possible.

**Comment by vadimyen** [comment]
@vasilii-kovalev, what was your end less harmful option?

**Comment by vasilii-kovalev** [comment]
> @vasilii-kovalev, what was your end less harmful option?

1. Discuss necessity of customization with designers. I've explained the importance of sticking to what each UUI component offers (less work on the library update from front-endside + UUI Figma components can be imported into the project's Figma to make the designers' life easier, and UI more consistent, so it is a win-win situation). Now we rarely customize UUI components, so the problem became a bit less relevant, but not completely
2. In cases when customization is still needed, I stick to the combination of options 1 and 2 from my original message:
    1. Use the combination of local and global (UUI) styles, like `.textInput:global(.uui-input-box)` (when using CSS Modules)
    2. Use `!important` in the local styles (when the first option is not enough)
