### ISSUE TITLE
Pickers - 'implicit' cascade selection mode

### ISSUE THREAD

**Issue by jakobz** [epam/UUI#1180]
## Description

The PickerInputs and data sources have a ```cascadeSelection``` option.
When ```cascadeSelection=true```, selecting a parent item automatically selects all of its children.
There is also a reverse logic, where selecting the last child of a parent automatically selects the parent.
This process is recursive. 

If the data tree is large, the user can select a lot in a single click. 
For example, in our Locations dataset, a user can select all cities of a continent in a single click. 
This leads to certain issues:

- The user gets a huge list of selected items in the Picker's body, which often doesn't fit, and we collapse it to a "N selected" message. So, after selecting a single item, the user doesn't see what's exactly selected.
- In a `LazyDataSource`, on selecting a parent, we need to load the whole sub-tree recursively, which can be time-consuming and resource-expensive.
- We often put such selection values in the URL, e.g., in case of table filters value. URLs have a limited size, and huge URLs are scary and inconvenient to use.
- We often pass such arrays of selected items to the server, and there can be performance issues if they get huge.

## Solution

In many cases, the user can understand from the context that selecting a parent implicitly means that all children are selected.
For example, consider our Locations picker, which contains the tree of continents, countries, and cities.
When the user selects "France," it is enough to show only "France" in selected items.

Other app logic can be adjusted to handle this case correctly. For example, at the server, when filtering items, instead of having just ```where cityId in [1,2,3]```, we can classify selected item types and put something like ```where countryId in [1] or cityId in [2,3,4]```.

To support this case, let's do the following:

- change 'cascadeSelection' prop type from ```boolean``` to ```boolean | 'implicit' | 'explicit'```. 
   - boolean is left for compatibility, 'true' value is the same as 'explicit' - meaning that we'll keep the old behavior
   - let's document this as following
 ```
/**
 * Controls how selection (checking items) of a parent node affects selection of its all children, and vice versa.
 * - false: All nodes are selected independently (default).
 * - true or 'explicit': Selecting a parent node explicitly selects all its children. 
 *    Unchecking the last parent's child unchecks its parent.
 * - 'implicit': Selecting a parent node means that all children are considered checked. 
 *    The user sees all these nodes as checked on the UI, but they only see the selected parent in the PickerInput tags, and only the checked parent is present in the Picker's value or DataSourceState.checked array. 
 *    When the user unchecks the first children of such parent, we uncheck its parents and check all children but the unchecked one, making children selection explicit. If the last unchecked child gets checked, we remove all children from checked, returning to the implicit state when only the parent is checked.
 */
```
- in ```rebuildRows()```, when we determine if row is checked
   - if ```cascadeSelection === 'implicit'```, and the row is not checked:
   - iterate through its parents
   - if any parent is checked - mark the row as checked
   - this way, if parent is checked, we show all its children as checked, even if they aren't in selection
- in ```tree.cascadeSelection()```
  - if ```mode === 'implicit'```, then
  - if items gets checked - skip checking it's children recursively
  - if item gets unchecked - check if parent has no selected nodes. If so - select all parent nodes (non-recursively), excluding the unchecked one
- in ```LazyListView.updateChecked``` - adjust the code that loads checked item's children. In ```cascadeSelection='implicit'```, we don't need to always load all children recursively:
    - if item gets checked, we need to know all its siblings, to mark parent as selected is the last node gets checked. However, to check all nodes by hand, user needs to see them all, meaning that it's safe to assume that is the last parent's node gets checked, all its siblings are already loaded
    - if items gets unchecked, we need to load all its siblings. However, we don't need to do this recursively - only one level is required.

Let's also enable this setting on PickerInput / Lazy tree example. Consider adding more docs / examples / tests, if there'll be any good ideas on how to additionally document this.

**Comment by NatalliaAlieva** [comment]
Released in 5.0.0 ver.
