### ISSUE TITLE
[Time Picker]: Fix hours rounding if typed minutes more the 59

### ISSUE THREAD

**Issue by DzmitryTrubchyk** [epam/UUI#1207]
Now if you type in minutes field value more than 59, TimePicker will increase the hours field. Let's add 59 as max value limit for minutes and 24 or 12(depends on format) for hours.

https://uui.epam.com/documents?category=components&id=timePicker&mode=propsEditor&skin=UUI4_promo
![image](https://user-images.githubusercontent.com/44213241/230887902-25db08d0-de6c-4e4a-8c32-fe03178f843f.png)

**Comment by NatalliaAlieva** [comment]
Released in 5.0.0 ver.
