### ISSUE TITLE
[PickerBase]: add highlighting of the search `matching` results.

### ISSUE THREAD

**Issue by Kuznietsov** [epam/UUI#1240]
## Idea
Along with the functionality, described at https://github.com/epam/UUI/issues/1239, it would be very useful to add highlighting of matched parts of the text while `search` is applied.

## To be done
- Add default highlighting of the `search` results at `Pickers. 
- Add an easy way of extending the default highlighting behavior at the userland for more complex cases (such as full-text search results, received from the backend for `LazyListView`).

**Comment by jakobz** [comment]
I suggest the following implementation:
- pass current search string to PickerItem via PickerItemProps
- in PickerItem, if search is passed, and title is a plain string:
  - find all occurrences of search string in title
  - wrap them with span to highlight this occurrences (consult with designers)
- if users needs to customize highlighting behaviour, they can hook into renderItem, and replace PickerItem title prop with arbitrary highlighted React.Fragment. End-user code can look into search, and/or pass some additional info for highlighting from server via TItem's attributes

If possible, we can also extend this to handle multi-word searches - as our default search algorithm matches when all words in a string are found. E.g. search='js prog' would find '**js** advanced **prog**ramming'. However, this can complicate algorithm, and is not widely used, so let's do this only if there's a simple solution.

**Comment by NatalliaAlieva** [comment]
@Kuznietsov Please add highlighting of the search to the modal view as well.

**Comment by NatalliaAlieva** [comment]
Released in ver. 5.1.2.
