### ISSUE TITLE
[PickerInput]: add default footer with 'Clear' button for single pickers

### ISSUE THREAD

**Issue by AlekseyManetov** [epam/UUI#1256]
## Now
Picker with single selection doesn't have any footer
## To Do
Let's add default footer with 'Clear' action for PickerInput with `selectionMode='single'`. If there is no selection, 'Clear' button will be disabled. 
Also let's leave 'Clear All' button for multi picker, even if `selectAll` functionality disabled via DataSource.

**Comment by NatalliaAlieva** [comment]
Released in 5.0.0 ver.
