### ISSUE TITLE
[PickerBase] dataSourceState updating issue

### ISSUE THREAD

**Issue by MSt1ch** [epam/UUI#1268]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Description

The dataSourceState is not updated after initialization, if a list of values arrives in the props.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. open any PickerModal component with some initial selected items
2. click on the Show only selected button
3. you will see an empty result instead of the selected items

## Actual result

What is the current behavior?

You should see selected items instead of the empty result text

* UUI version: latest
* Browser name: all
* Operating System: all

**Comment by AlekseyManetov** [comment]
Released in 5.0.0 ver.
