### ISSUE TITLE
Update color palete for Loveship and Promo

### ISSUE THREAD

**Issue by AlekseyManetov** [epam/UUI#1270]
## To Do
Update color palete according to the design specs - https://www.figma.com/file/XvNqYvKrGf8PP1wCedPVQu/UUI-Components-Main-Branch-(Sandbox)?node-id=2123-471275&t=UqeP3Ek9DjTAdIEc-0

Update color variables in themes, @epam/assets package and ./assets folder inside skins.

Also this change will affect some components color props:
- In `Button` for "night500" and "gray50", mark them as deprecated and bind them in styles to "night600/gray60". Add a new "gray" value that refers to "gray60". In property explorer leave only 'gray' value.
- In `Tooltip` for "night900" and "gray90", mark them as deprecated and bind them in styles to "night800/gray80". Add a new "gray" value that refers to "gray80". In property explorer leave only 'gray' value.

**Comment by NatalliaAlieva** [comment]
Released in 5.0.0 ver.
