### ISSUE TITLE
Replace the react-custom-scrollbars package

### ISSUE THREAD

**Issue by dsv-sergey** [epam/UUI#13]
**Description**

It is necessary to change the react-custom-scrollbars package since owner abandoned updates. Last release v4.2.1 - Oct 28, 2017

**Describe the solution you'd like**

Intended replacement packages

1. https://github.com/sakhnyuk/rc-scrollbars
2. https://github.com//RobPethick/react-custom-scrollbars-2

**Comment by alex9pro** [comment]
Great idea! We are waiting new Scrollbars. Original package did fantastic job, but a little outdated now..
