### ISSUE TITLE
Auth: Make relogin after 401 configurable or add link to relogin in modal window

### ISSUE THREAD

**Issue by oleksapro** [epam/UUI#1320]
Hello! We regularly revisit the issue of re-login upon receiving a 401 error and opening a new tab. Due to the fact that browsers may block programmatic opening of new tabs or users may have blocked this in their settings, we receive complaints from users regarding this issue.

It may be worthwhile to add a link to the reloginPath in the modal window and/or provide the ability to configure the behavior to use automatic tab opening or for the user to open it through a link in the modal window.

![image](https://github.com/epam/UUI/assets/7101211/59e5e95c-3856-4382-ae9d-24f11dd0d768)

**Comment by NatalliaAlieva** [comment]
Released in 5.7.0 ver.
