### ISSUE TITLE
[PickerInput]: reset 'Show only selected' toggler to the default value

### ISSUE THREAD

**Issue by AlekseyManetov** [epam/UUI#1324]
## Now
When user turns on 'Show only selected' toggler and closes picker, then when he opening picker one more time - 'Show only selected' toggler remains switched on.
## To Do
Let's reset 'Show only selected' toggler value to  the 'false' on PickerInput close.

**Comment by NatalliaAlieva** [comment]
Released in 5.1.1 ver.
