### ISSUE TITLE
[API]: Allow set duration in 'notification' mode in apiDefinition

### ISSUE THREAD

**Issue by oleksapro** [epam/UUI#1330]
Hi! We get request from business analyze to keep notification in case of server API error until users close it by themselves (duration: forever).

For now it is impossible to configure API notification behavior.

Could you extend apiDefinition request API and allow to configure notification duration?

**Comment by AlekseyManetov** [comment]
I propose to add such customization via `ErrorHandler` component. Now `ErrorHandler` hardcode the handler for the notification type errors, let's add  `onNotificationError?: (errors: ApiCallInfo[]) => void;` prop using which it will be possible to provide custom callback which will handle notification type of error, for example:
```
 onNotificationError = { (errors) => 
   errors.forEach((c) => {
      uuiNotifications.show((notificationProps: INotification) => (
          <ErrorNotification { ...notificationProps }>
              <Text size="36">
                  {c.responseData && c.responseData.errorMessage}
              </Text>
          </ErrorNotification>
      ), { duration: 'forever', position: 'bot-right' });
  });
}
```
