### ISSUE TITLE
Table is a little shifted after pinning any column

### ISSUE THREAD

**Issue by Yuliya12389** [epam/UUI#1335]
**Steps to reproduce**:
1. Go to https://uui.epam.com/documents?id=advancedTables&mode=doc&skin=UUI4_promo&category=tables
2. Open "Configure columns" modal window
3. Pin any column -> Save changes
4. Observe table

**Actual result**: Table is a little shifted
**Expected result**: Table is not shifted

Browser name: Chrome, Edge

https://github.com/epam/UUI/assets/90705779/5e635b33-f097-495e-9d43-917489a40f47

**Comment by AlekseyManetov** [comment]
Hi @Yuliya12389, could you please clarify what do you mean by 'Table shifted'? A can't recognize any non expected shifts by your video. Note, that it's expected that columns changes their positions, when you pin them - if you pin some column, this column will be moved to first position(we rendered it into another sticky container).
