### ISSUE TITLE
[RichTextEditor]: uncaught error after pasting a list

### ISSUE THREAD

**Issue by mikzakh** [epam/UUI#1339]
## Description

Uncaught error in the console after pasting a list.

## Steps to Reproduce

1. Open rich text editor page in [docs](https://uui.epam.com/documents?id=richTextEditor&mode=doc&skin=UUI4_promo&category=components).
2. Create a list
![first](https://github.com/epam/UUI/assets/97105597/03578830-2caa-4048-9193-6f9cbdf8bd8d)
3. Select all
![second](https://github.com/epam/UUI/assets/97105597/953c47d9-ff6c-4307-a9c4-b441ef96fce4)
4. Cut
![third](https://github.com/epam/UUI/assets/97105597/f98870fa-a9bc-4114-92d4-a25d2fd55f53)
5. Paste

## Actual result

Uncaught Error: A schema rule could not be normalized after sufficient iterations. This is usually due to a `rule.normalize` or `plugin.normalizeNode` function of a schema being incorrectly written, causing an infinite loop.
  

## Expected result

List is pasted without an error.

## Environment

* UUI version: 4.10.0
* Browser name: Chrome
* Operating System: Windows 10

**Comment by NatalliaAlieva** [comment]
Released in 5.1.0 ver.
