### ISSUE TITLE
Clear entered text after user selects some item for multiselect

### ISSUE THREAD

**Issue by Alexandr-Kaz** [epam/UUI#1357]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x ] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed

## Expected result

Clear text

## Environment
![изображение_2023-05-22_132217557](https://github.com/epam/UUI/assets/129818601/ef7e231a-fc02-4152-be30-d5f3e0727408)

* UUI version: 4.10.2
* Browser name: All
* Operating System: window

**Comment by AlekseyManetov** [comment]
Please provide more detailed description and steps for reproduce. Also it will be nice if you could create a codesandbox example with this case, you can use this one as a base - https://codesandbox.io/s/0nlhcx?file=/Example.tsx.
