### ISSUE TITLE
[ApiContext]: customization for error-handling

### ISSUE THREAD

**Issue by JuliaMV** [epam/UUI#1359]
## Now
UUI-library has very convenient functionality with handling api errors and covers different behavior depend on status code (401, 50x).  Currently we have tree options to handle api errors: **page**, **notification**, **manual**. For two of them (page and notification) we couldn't add any additional callback to customize application behavior. But if we choose manual all api errors for particular request should be handled on application side.

## To Do
Would be great if UUI-library team propose **additional API** that will allow applications add own callbacks on error or **semi-manual** mode that will cover 401 and other build-in cases but for others error-codes the logic may be added on application side.

**Comment by NatalliaAlieva** [comment]
Released in 5.7.0 ver.
