### ISSUE TITLE
[FiltersPanel]: move picker title to the header in mobile view

### ISSUE THREAD

**Issue by AleksSam2020** [epam/UUI#1374]
## Now
![image](https://github.com/epam/UUI/assets/76586401/e8171905-be6f-440e-977c-976ddbbc850f)

## Describe the solution you'd like (optional)
Move picker title to the header in filters mobile view, like it works in PickerInput component:
<img width="476" alt="image" src="https://github.com/epam/UUI/assets/14283670/fd2df088-fbcf-4653-a510-7fa8ace2c8ac">

**Comment by NatalliaAlieva** [comment]
Released in 5.0.1 ver.
