### ISSUE TITLE
Input stays focused in case of outside click

### ISSUE THREAD

**Issue by stanislavec** [epam/UUI#1385]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Description

Click outside input field doen't cause blur event on field in case if field is inside Dropdown.

## Steps to Reproduce

Try to wrap input fields with Dropdown container. So, fields could be inside Dropdown.

## Actual result

What is the current behavior?

[EPM_UUI_Dropdown_bug.webm](https://github.com/epam/UUI/assets/34837948/6056661b-6edd-4d2c-a186-da13b85078b7)

As I checked, the reason may be `isInteractedOutsideDropdown` function ([source code](https://github.com/epam/UUI/blob/main/uui-components/src/overlays/Dropdown.tsx)). 

## Expected result

Click outside input causes Blur event, so field starts to be unfocused.  

## Environment

* UUI version: 4.10.2
* Browser name: Chrome
* Operating System: MacOS

**Comment by vik753** [comment]
My investigation found that after the 'clickOutside' event, the React remading DOM faster than the 'onClick' event is bubbling to target DOM Node. We can fix it to add timeout into the Dropdown/clickOutsideHandler method, but it's not the best decision. We will investigate this problem one more time in nearest future.

**Comment by NatalliaAlieva** [comment]
Released in 5.5.0 ver.
