### ISSUE TITLE
[RangeDatePicker] "Month/Year" filter data isn't displayed after clearing filters

### ISSUE THREAD

**Issue by AndreiGordeev1** [epam/UUI#1394]
## Prerequisites

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Click on "Clear All" button
2. Click on "Month/Year" 

## Actual result

Data on the pop-up isn't displayed.
[Codesandbox](https://codesandbox.io/s/uui-forked-9ovz68?file=/Example.tsx) example.

https://github.com/epam/UUI/assets/129832039/08dbdf35-cddf-4a28-9c7f-074b37876af4

## Expected result

Months and year are displayed on the pop-up

## Environment

* UUI version: 4.10.2
* Browser name: Chrome
* Operating System: Windows

**Comment by AlekseyManetov** [comment]
I guess it's something wrong with your realisation of `onClearAll` handler, i've tried to comment  `this.setState({ inFocus: "from" }); - and it's worked.
`
