### ISSUE TITLE
[Rating]: rating is displayed as 0.5, with the initial value equal to 0 in steps of 0.5

### ISSUE THREAD

**Issue by NatalliaAlieva** [epam/UUI#1411]
## Steps to Reproduce
1. Open [Codesandbox](https://codesandbox.io/s/uui-forked-gd3458?file=/Example.tsx).
2. Verify how many stars are displayed by default

## Actual result
A value of 0 displays half of the star.
![value=0 step=0 5 shown as 0 5](https://github.com/epam/UUI/assets/57751283/05466ff1-379e-4e08-8790-da212b41af43)

## Expected result
With a value of 0, all stars are not fiiled.

## Environment
* UUI version: 5.0.0
* Browser name: any
* Operating System: any

**Comment by Djarrieta** [comment]
Hello! Can you please assign this one to me? I am already sending the PR.

**Comment by Djarrieta** [comment]
This is the related [PR](/epam/UUI/pull/1452).
There is also a [demo video](https://www.youtube.com/watch?v=SeOdyf72ljo)

**Comment by NatalliaAlieva** [comment]
Hello, @Djarrieta! 
Could you please add in the Property Explore value=0?

**Comment by Djarrieta** [comment]
Yes @NatalliaAlieva , I can do that. I am going to do it in a new PR. I let you know when it is send.

**Comment by NatalliaAlieva** [comment]
> Yes @NatalliaAlieva , I can do that. I am going to do it in a new PR. I let you know when it is send.

Thank you!

**Comment by NatalliaAlieva** [comment]
Hi @Djarrieta ,

During testing your fix, I found another one:

https://github.com/epam/UUI/assets/57751283/a606daf4-a23a-4737-a385-7e1659641572

Could you please see this case too?

**Comment by Djarrieta** [comment]
It is the same issue solved in [the first PR](https://github.com/epam/UUI/pull/1452) , it has no been merge in the main branch yet, at least in production. As soon as it is merged, it is not going to be a problem any more.

**Comment by AlekseyManetov** [comment]
I've cherry picked this commit to the develop branch. @NatalliaAlieva, please check this case again. @Djarrieta, please create PR to the 'develop' branch next time.

**Comment by Djarrieta** [comment]
I got it, I was following the ["Fork-and-Pull" Git workflow](https://github.com/susam/gitpr) as the docs says. Next time will be Develop branch, no problem.

**Comment by AlekseyManetov** [comment]
It's a generic approach, in our case we use develop branch as main for development and merge develop to the main only before the release. You can read our guidelines for PR here - https://github.com/epam/UUI/blob/main/CONTRIBUTING.md#creating-a-pull-request

**Comment by NatalliaAlieva** [comment]
> I've cherry picked this commit to the develop branch. @NatalliaAlieva, please check this case again. @Djarrieta, please create PR to the 'develop' branch next time.

Now everything is correct.

**Comment by NatalliaAlieva** [comment]
Released in 5.1.1 ver.
