### ISSUE TITLE
[PickerInput]: fails in case with horizontal scrollable list

### ISSUE THREAD

**Issue by MSt1ch** [epam/UUI#1418]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Description

when the width of the dropdown is limited and a horizontal scroll appears. It is important to scroll quickly when doing so. A library error appears:
 "Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops."
 
## Steps to Reproduce

https://github.com/epam/UUI/assets/17798957/2cc28dbb-5824-4107-bea2-c7062da89ee8

Please provide detailed steps for reproducing the issue.

https://codesandbox.io/s/uui-forked-p6rvh5

* UUI version: 4.10.2
* Browser name: All
* Operating System: All

**Comment by JuliaMV** [comment]
This issue also reproduces when datatables is rendered with visible scrollbars.

**Comment by NatalliaAlieva** [comment]
Released in 5.2.0 version.
