### ISSUE TITLE
[Table] Add column description to table header and column configuration modal

### ISSUE THREAD

**Issue by DzmitryTrubchyk** [epam/UUI#1423]
Table view, header cell
- Add tooltip while hovering for all table header columns. Use delay for opening 800ms. [Figma link](https://www.figma.com/file/cAd3iaIW4JxJapIVTrE96b/UUI-%E2%80%93-Tables-(Demo-%26-Examples)?type=design&node-id=4917%3A583412&t=DqjQDX2UTsdYTizz-1). Screenshot:
![image](https://github.com/epam/UUI/assets/44213241/8850a064-2f15-4a7c-8b69-4e74be9951ae)

Configure columns modal: Add 2nd line description
- Add description text below title. [Figma link](https://www.figma.com/file/cAd3iaIW4JxJapIVTrE96b/UUI-%E2%80%93-Tables-(Demo-%26-Examples)?type=design&node-id=4949-580109&t=DqjQDX2UTsdYTizz-4). Screenshot:
![image](https://github.com/epam/UUI/assets/44213241/6b03a709-26b0-4d51-bc13-7f0b289232b1)

**Comment by DzmitryTrubchyk** [comment]
On table demo salary should be Title case (Salary) https://uui-dev.epm-ppa.projects.epam.com/demo?id=filteredTable&page=1&pageSize=40&presetId=-1

![Image](https://github.com/epam/UUI/assets/44213241/d57d83b9-9e77-4dba-a775-2e6e6a5baae4)

**Comment by DzmitryTrubchyk** [comment]
Vertical sizes are incorrect. Please, check all paddings, lineheight of types, to fit with design @vik753 

![Image](https://github.com/epam/UUI/assets/44213241/4b74f18b-32a0-496a-80e1-64824ec37d0b)

**Comment by NatalliaAlieva** [comment]
Released in 5.1.1 ver.
