### ISSUE TITLE
[TimePicker]: minutes that are not multiples of their addition step are not rounded up to a step

### ISSUE THREAD

**Issue by NatalliaAlieva** [epam/UUI#1424]
## Description
If User changes minutes in the TimePicker that are not multiples of a step (for example, step = 5 and User specifies 23 minutes), then the system will not round the values.

## Steps to Reproduce
1. Open [TimePicker](https://uui.epam.com/documents?category=components&id=timePicker&mode=propsEditor&skin=UUI3_loveship) component.
2. Set minutesStep property = 5 OR set it by default (5 min).
3. Set the value of minutes not a multiple of the minutesStep = 23.
4. Click on the Up or Down arrow in the TimePicker area.

## Actual result
System adds the minutes specified in the minutesStep. The value becomes 28 and 18 correspondingly.

https://github.com/epam/UUI/assets/57751283/665ef772-b1a9-4f38-b127-1c6ecbfc31bc

## Expected result
System rounds the minutes value to the nearest multiple. The value becomes 30 and 20 correspondingly.

## Environment
* UUI version: 5.0.1
* Browser name: any
* Operating System: any

**Comment by dalalvarun** [comment]
Hi @NatalliaAlieva 
I would like to work on this. Please assign this to me.
Also, one thing I want to clarify is that if minutesStep=15 and the user enters 05:37 PM as the input, should it round it off to 05:30 PM or  05:45 PM?

**Comment by AlekseyManetov** [comment]
Hi @dalalvarun, I've assigned this issue to you, please read our [contributing guild](https://github.com/epam/UUI/blob/main/CONTRIBUTING.md) before the start. 
>  I want to clarify is that if minutesStep=15 and the user enters 05:37 PM as the input, should it round it off to 05:30 PM or 05:45 PM?
It's should round to the 05:45, therefore always rounding up.

**Comment by dalalvarun** [comment]
@AlekseyManetov Done with the changes - #1426 
Please check and let me know if any changes needed😄

**Comment by NatalliaAlieva** [comment]
Released in 5.1.0 ver.
