### ISSUE TITLE
[Labeled Input] Safari: Artefact in inputs 

### ISSUE THREAD

**Issue by Margaryta-Maletz** [epam/UUI#1425]
## Prerequisites
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Steps to Reproduce
1. Open in Safari: Label Input -> Property Explorer -> Form. https://uui.epam.com/documents?category=components&id=labeledInput&mode=propsEditor&skin=UUI4_promo
2. Place cursor to the input field and input 2-3 letters

## Actual result
The popup with a double hint appears. The icon in the right corner appears.
The screenshot attached.
<img width="1440" alt="Screenshot 2023-06-22 at 08 48 36" src="https://github.com/epam/UUI/assets/78261193/68a5a322-0294-4a4c-a8d8-ab4b0ce87685">

## Expected result
The same as in Google Chrome. Only written text appears.
The screenshot attached.
<img width="1419" alt="Screenshot 2023-06-22 at 09 00 21" src="https://github.com/epam/UUI/assets/78261193/2d8a4fe5-2479-4b77-ac89-7fcfb182a81b">

## Environment

* UUI version: 4.10.2
* Browser name: Safari
* Operating System: MacOs

**Comment by AlekseyManetov** [comment]
This is looks like native safari behavior, it's detected type of input according to labeled and propose suggestions for you. In Chrome and other browsers you can configure this behavior via `autocomplete` prop. But  it seems that Safari ignore this prop, so we can't disable it - https://stackoverflow.com/questions/22661977/disabling-safari-autofill-on-usernames-and-passwords
