### ISSUE TITLE
[Dropdown Menu]: align open submenu to 1st item in dropdown list

### ISSUE THREAD

**Issue by NatalliaAlieva** [epam/UUI#1436]
Align opened submenu by 1st item in dropdown, rather than dropdown container.
https://www.figma.com/file/lXOupesvjg7g53YKmznInc/UUI-improvements?node-id=7%3A1463&mode=dev

![image](https://github.com/epam/UUI/assets/57751283/89d667f5-e2e2-41a2-9370-b5181d99da5f)

**Comment by DzmitryTrubchyk** [comment]
Can we align also the bottom items, with the same logic as for top items? @NatalliaAlieva 

![Image](https://github.com/epam/UUI/assets/44213241/ac62dc97-679e-411a-8db8-b34a3ac8d0c6)

**Comment by NatalliaAlieva** [comment]
Released in 5.1.1 ver.
