### ISSUE TITLE
[Docs]: add example of custom list with DataSources 

### ISSUE THREAD

**Issue by AlekseyManetov** [epam/UUI#1438]
## Description
Let's add one more example to the [Usage in components](https://uui.epam.com/documents?category=dataSources&id=dataSources-usage&skin=UUI4_promo) datasource page. This example will describe how to implement your own list based on DataSources and VirtualList component.
Draft version: https://codesandbox.io/s/uui-lazyds-virtuallist-custom-items-8l6vl3?file=/Example.tsx

**Comment by NatalliaAlieva** [comment]
Released in 5.9.2 ver.
