### ISSUE TITLE
[Alert]: improvement according to the design specs

### ISSUE THREAD

**Issue by OlegKryvokobylskyi** [epam/UUI#1461]
### Now
There is no possibility to choose between a size 36 and a size 48.

### To Do
Add size 36 so User can choose between sizes 36 and 48.
Link to [Loveship (UUI3)](https://www.figma.com/file/M5Njgc6SQJ3TPUccp5XHQx/Loveship-aka-UUI3-(Components)?type=design&node-id=15770-362256&mode=design&t=shGpLHD9FBD7wZxb-0)
Link to [Promo (UUI4)](https://www.figma.com/file/UyChXPLmyv5zMrOU37KdUL/Promo-aka-UUI4-(Components)?type=design&node-id=32893-434109&mode=design&t=0rVfYcXUSXriN1mb-0)

### Now
For default 48 size paddings  -  12px 18px 12px 12px;
![image](https://github.com/epam/UUI/assets/129292145/a28f1bfc-5ef5-4b95-a24e-2e5c3e18ec76)

### To Do
Paddings should be according to Figma, see below:
For Default - Hight 48px, paddings should be - 9, 18, 9, 12.
For Compact - Hight 36px, paddings should be - 3, 9, 3, 9.

Link to [Loveship (UUI3)](https://www.figma.com/file/M5Njgc6SQJ3TPUccp5XHQx/Loveship-aka-UUI3-(Components)?type=design&node-id=32-0&mode=design&t=cm7tDSx7i6IujtaH-0)
Link to [Promo (UUI4)](https://www.figma.com/file/UyChXPLmyv5zMrOU37KdUL/Promo-aka-UUI4-(Components)?type=design&node-id=32893-434109&mode=design&t=MgUN6a3w53qfc7fS-0)

**Comment by DIWAKARKASHYAP** [comment]
i want to contribute in this , can i start ?

**Comment by AlekseyManetov** [comment]
@DIWAKARKASHYAP I've assigned it to you. Please, read our contribution guide before start

**Comment by DIWAKARKASHYAP** [comment]
ok

**Comment by DIWAKARKASHYAP** [comment]
i want some help @AlekseyManetov , where i can find the style(css/scss) file ?

**Comment by AlekseyManetov** [comment]
@DIWAKARKASHYAP it's near the component:  uui/components/overlays/Alert.module.scss

**Comment by DIWAKARKASHYAP** [comment]
@AlekseyManetov Do I need to create a new prop? for size 36 and 48 , here 👇
![image](https://github.com/epam/UUI/assets/94478026/4d3d2858-5de2-440e-9960-3d250ea2dc68)

**Comment by AlekseyManetov** [comment]
Yes, you need to add new prop to the component and then add it to the Property Explorer. Also it would be nice to have example in documentation with both sizes.

**Comment by DIWAKARKASHYAP** [comment]
got it

**Comment by DIWAKARKASHYAP** [comment]
@AlekseyManetov where i can find key of AlertProps 
![image](https://github.com/epam/UUI/assets/94478026/eee29e14-ad2d-4507-b379-0f80d845fdc7)

**Comment by DIWAKARKASHYAP** [comment]
@AlekseyManetov actually i completed the coding part but i want to update the documentation , and i am stuck to find this 👇api documentation folder
![image](https://github.com/epam/UUI/assets/94478026/0c05e1ba-73ad-4847-bd81-738a489b60cd)

**Comment by AlekseyManetov** [comment]
@DIWAKARKASHYAP  Please read this section in contribution.md - https://github.com/epam/UUI/blob/main/CONTRIBUTING.md#api-block

**Comment by DIWAKARKASHYAP** [comment]
oh sorry, i forget this

**Comment by DzmitryTrubchyk** [comment]
Hey! I performed design review, see details below:

- Someting wrong with the height of all sizes
36 px size actually is 48 px
![image](https://github.com/epam/UUI/assets/44213241/06e6847c-9758-404a-82f8-19b9b67b1824)

and 48 px actually is 66 px
![image](https://github.com/epam/UUI/assets/44213241/c7d8eb9c-c06d-4697-b7d2-e95fa15981b8)

36 and a size 48 means that component should be matched to this height in px. If paddings from task description does not match, please, change them to fit height 36 and 48 px for corresponding property name.
CC @DIWAKARKASHYAP, @AlekseyManetov

**Comment by NatalliaAlieva** [comment]
Released in ver. 5.1.2.
