### ISSUE TITLE
[Control Group]: improvement according to the design specs

### ISSUE THREAD

**Issue by OlegKryvokobylskyi** [epam/UUI#1464]
### Now
No examples described  with prefix, and suffix with inputs:
![image](https://github.com/epam/UUI/assets/129292145/ebbd5dca-dfde-4467-8d63-7da4ecf90e36)

### To Do
Add examples with prefix, suffix with inputs (then confirm result with design)
https://www.figma.com/file/ozuZOZNqKMUGiwLKYlsfkT/UUI-%E2%80%93-Forms%3A-Text-Input-(Sandbox)?type=design&node-id=616-344660&mode=design&t=L7KKVVAXafMs7NYa-0

**Comment by NatalliaAlieva** [comment]
Released in 5.2.0 version.
