### ISSUE TITLE
[PickerInput]: Selected value resets on first render with AsyncDataSource and valueType="entity"

### ISSUE THREAD

**Issue by oleksapro** [epam/UUI#1469]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Description

Selected value resets on first render in AsyncDataSource and valueType="entity"

## Steps to Reproduce

1. PickerInput with valueType="entity" and AsyncDataSource
2. Set initial value

https://codesandbox.io/s/uui-pickerinput-asyncdatasource-clears-value-jx4xpf?file=/Example.tsx

## Actual result

Value resets on first render

## Expected result

Initial value stays in picker

**Comment by NatalliaAlieva** [comment]
Released in 5.1.1 ver.
