### ISSUE TITLE
[Numeric Input]: improvement according to the design specs

### ISSUE THREAD

**Issue by OlegKryvokobylskyi** [epam/UUI#1472]
### Now
Max size=48

![image](https://github.com/epam/UUI/assets/129292145/980500e7-12c1-42df-85d1-d6b2259e6907)

### To Do
Max size should be 42. Deprecated 48 size with dev warning and remove in future versions.

### Now
Error state doesn't exist

### To Do
Add isInvalid prop to the Property Explorer

See design:
Link to [Loveship (UUI3)](https://www.figma.com/file/M5Njgc6SQJ3TPUccp5XHQx/Loveship-aka-UUI3-(Components)?type=design&node-id=8270%3A270961&mode=design&t=DOBLAlfo6uOLXwuI-1)
Link to [Promo (UUI4)](https://www.figma.com/file/UyChXPLmyv5zMrOU37KdUL/Promo-aka-UUI4-(Components)?type=design&node-id=14786%3A269629&mode=design&t=u1QAuYc99KS3EnxL-1)

### Now
Resizable context PE doesn't exist

### To Do
Add Resizable context(Resizable Tab) to the Property Explorer

**Comment by DIWAKARKASHYAP** [comment]
@AlekseyManetov i want to work on this

**Comment by DzmitryTrubchyk** [comment]
Design Review
strange property none
![image](https://github.com/epam/UUI/assets/44213241/04f57843-dbce-43f8-808c-6f936868fcdd)

**Comment by NatalliaAlieva** [comment]
Released in 5.5.0 ver.
