### ISSUE TITLE
[Range Date Picker]: improvement according to the design specs

### ISSUE THREAD

**Issue by OlegKryvokobylskyi** [epam/UUI#1473]
### Now
Max size=48
![image](https://github.com/epam/UUI/assets/129292145/6a3ec636-f79b-4736-b1a9-acc3780182cf)

### To Do
48 size should be deprecated
Max size should be 42

### To Do
Change example where footer with presets:
https://www.figma.com/file/M41fdci2Y1ErJ17NrJxLDp/Design-Review?type=whiteboard&node-id=5-226&t=7tKCszKarGFF3SNQ-0

See design:
Link to [Loveship (UUI3)](https://www.figma.com/file/M5Njgc6SQJ3TPUccp5XHQx/UUI3-(Components)?type=design&node-id=5034-159031&t=nfIfyjsVu7Pq741R-4)
Link to [Promo (UUI4)](https://www.figma.com/file/UyChXPLmyv5zMrOU37KdUL/Promo-aka-UUI4-(Components)?type=design&node-id=271%3A85318&mode=design&t=u1QAuYc99KS3EnxL-1)

Fix footer, add footer types for calendar
Make a basic footer for property explorer

**Comment by DzmitryTrubchyk** [comment]
Calendar dropdown doesn't open. I see "Something went wrong..." screen and can't review changes @vik753 

![Image](https://github.com/epam/UUI/assets/44213241/8280ff59-f8c8-48fc-9477-b3debc668924)

**Comment by NatalliaAlieva** [comment]
> screen

Fixed on dev.

**Comment by NatalliaAlieva** [comment]
Released in 5.1.1 ver.
