### ISSUE TITLE
[Tag]: improvement according to the design specs

### ISSUE THREAD

**Issue by OlegKryvokobylskyi** [epam/UUI#1475]
### Now

![image](https://github.com/epam/UUI/assets/129292145/498e827a-655e-4165-8e2a-bddc6a9ec322)

### To Do
Frontend: 

Please do changes according to following design specification:

 [Figma Link](https://www.figma.com/file/dYwal6PrxrPQWg1lL6ijpn/UUI-Specifications?type=design&node-id=2618%3A664798&mode=design&t=o0dCipFDvwkxEcb0-1)

**Comment by DIWAKARKASHYAP** [comment]
please check PR #1522

**Comment by DzmitryTrubchyk** [comment]
Design Review:

1. Tag only with label. Check horizontal paddings in 24, 30 and 36 sizes. They must be 6px, not 12 in 24 and 30 size. In 36 size they must be 9 px

![Image](https://github.com/epam/UUI/assets/44213241/bec76b2c-4480-4f45-9b2a-b8bd9a9ac421)

2. There is on 48 size on design (to discuss)

**Comment by NatalliaAlieva** [comment]
Released in 5.5.0 ver.
