### ISSUE TITLE
[Text Area]: improvement according to the design specs

### ISSUE THREAD

**Issue by OlegKryvokobylskyi** [epam/UUI#1476]
### Now
Max size=48
![image](https://github.com/epam/UUI/assets/129292145/33a4a172-e47f-4024-908a-25e27719b94e)

### To Do
Deprecated 48 size with dev warning and remove in future versions.
Max size should be 42. 

Link to [Loveship (UUI3)](https://www.figma.com/file/M5Njgc6SQJ3TPUccp5XHQx/Loveship-aka-UUI3-(Components)?type=design&node-id=8270-274655&mode=design&t=3mjV8zPxiZ068JSj-0)
Link to [Promo (UUI4)](https://www.figma.com/file/UyChXPLmyv5zMrOU37KdUL/Promo-aka-UUI4-(Components)?type=design&node-id=14926-274341&mode=design&t=PuTxiNHRAvxgqeSe-0)

**Comment by DIWAKARKASHYAP** [comment]
assign this to me , i want to work on this

**Comment by DIWAKARKASHYAP** [comment]
i want to work on this

**Comment by DIWAKARKASHYAP** [comment]
is i need to remove 48 from here👇, right
![image](https://github.com/epam/UUI/assets/94478026/258c2253-ec66-4898-ac22-13085d5d6e6a)

**Comment by NatalliaAlieva** [comment]
Released in 5.5.0 ver.
