### ISSUE TITLE
[Text Input]: improvement according to the design specs

### ISSUE THREAD

**Issue by OlegKryvokobylskyi** [epam/UUI#1477]
### Now
![image](https://github.com/epam/UUI/assets/129292145/9299a6b6-3024-4806-847f-d73f28583c55)

### To Do
Add 60 size. [Design is here (Figma)](https://www.figma.com/file/QRO2FGW5MPNPuSTfJuB8Uo/UUI-%E2%80%93-Button%2C-Text-Inputs-60-size-(Sandbox)?type=design&node-id=1145%3A77839&mode=design&t=6QwlgXnXaMRcUlg9-1)

Link to [Loveship (UUI3)](https://www.figma.com/file/M5Njgc6SQJ3TPUccp5XHQx/Loveship-aka-UUI3-(Components)?type=design&node-id=137-0&mode=design&t=e96gVoOeajkmQSlW-0)

Link to [Promo (UUI4)](https://www.figma.com/file/UyChXPLmyv5zMrOU37KdUL/Promo-aka-UUI4-(Components)?type=design&node-id=137-0&mode=design&t=z6bsNdnwdVy7XmCn-0)

## Case №2
Add example Label Input + Text Input.

**Comment by DIWAKARKASHYAP** [comment]
did you mean, add size 60 here 👇
![image](https://github.com/epam/UUI/assets/94478026/f99a0bab-ca4f-47d5-a22b-579d9189928c)

**Comment by DzmitryTrubchyk** [comment]
Hey! Yes, but design is In progress. It's better to postpone this task untill design will be approved (2-4 days)

> did you mean, add size 60 here 👇 , right ? ![image](https://user-images.githubusercontent.com/94478026/254979623-f99a0bab-ca4f-47d5-a22b-579d9189928c.png)

**Comment by DzmitryTrubchyk** [comment]
Hey @DIWAKARKASHYAP, we've prepared design for this task. Please, find [Button 60 size here (Figma)](https://www.figma.com/file/QRO2FGW5MPNPuSTfJuB8Uo/UUI-%E2%80%93-Button%2C-Text-Inputs-60-size-(Sandbox)?type=design&node-id=1145%3A77839&mode=design&t=6QwlgXnXaMRcUlg9-1)

**Comment by DzmitryTrubchyk** [comment]
@DIWAKARKASHYAP, I am sorry, text input  was in progress that time, my bad. [Here is the link to text input ](https://www.figma.com/file/QRO2FGW5MPNPuSTfJuB8Uo/UUI-%E2%80%93-Button%2C-Text-Inputs-60-size-(Sandbox)?type=design&node-id=1230%3A15700&mode=design&t=GTJJLpVetvRrcs5d-1)

**Comment by NatalliaAlieva** [comment]
Released in 5.5.0 ver.
