### ISSUE TITLE
[FiltersPanel]: Displaying the number of selected elements from the list

### ISSUE THREAD

**Issue by 9vit917** [epam/UUI#1480]
## Now
We have fixed max-width for wrapper(300px) and if will choice option with too big length
![image](https://github.com/epam/UUI/assets/24899335/896dc21b-2549-4c2e-8188-15094e152ac8)
we will fill in the entire possible length for component and when we select the second one we will see the situation where we have two options but can see only first with three dots.  
![image](https://github.com/epam/UUI/assets/24899335/2d97b070-5727-4656-8193-67295d51f250)
And finally when we select third option we will see the shortened view for the first option and '+1 items'  
there is a visual bug turns out (a shortened version of the first item and + 1 item, looks like two items for quick viewing without opening a dropdown)
![image](https://github.com/epam/UUI/assets/24899335/b5b1bf21-51a5-4ad2-bb96-4207017ffe57)

## To Do
Could you please make "+N items" appear after more than one item is selected, or please make a length limit per item in a quick preview, which would be approximately (first ite..., second it... +2 items) 

Thank you

**Comment by NatalliaAlieva** [comment]
Released in 5.1.1 ver.
