### ISSUE TITLE
[MainMenu]: Nested menu item has no hover effect

### ISSUE THREAD

**Issue by AlekseyManetov** [epam/UUI#1485]
### Actual result: 

<div type='discussions-op-text'>

<sup>Originally posted by **not-SAINT** July 10, 2023</sup>
Hi here.
We found out that hover color in nested menu item is the same for normal stage after lib upgrade up to latest version.
background-color: var(--uui-main_menu-dropdown-bg) //  #1d1e26  - normal state
background-color: var(--uui-main_menu-hover) // #1d1e26  - hover state
![image](https://github.com/epam/UUI/assets/60464016/9ca68991-6679-4aed-8fa5-1a66ffd41bee)
Previous version (4.*.*) has values: 
background-color: var(--dropdown-body-background-color) // #1d1e26  - normal state
background-color: var(--dropdown-item-background-color) // #303240 - hover state 
![image](https://github.com/epam/UUI/assets/60464016/4b799ca6-5c84-45db-9a61-30aa81b033c0)

Same state [here](https://uui.epam.com/documents?id=mainMenu&mode=doc&skin=UUI4_promo&category=components).
</div>

### Expected result:
Make hover effect according to the design spec: https://www.figma.com/file/dYwal6PrxrPQWg1lL6ijpn/UUI-Specifications?type=design&node-id=951-551385&mode=design&t=4sL8LrlNGheskWAX-0

**Comment by NatalliaAlieva** [comment]
Released in 5.1.1 ver.
