### ISSUE TITLE
[DataTable]: getColumns config error

### ISSUE THREAD

**Issue by JuliaMV** [epam/UUI#1495]
## Steps to Reproduce
Create a Datatable and save columns config in Local Storage. Add new column to the table.
Try to update columns config through configure columns  modal.

## Actual result
Application is crashed with error
![2023-07-14_13h43_01](https://github.com/epam/UUI/assets/37875890/70ec7837-152d-4e35-ac50-dc18bcbe9b35)

## Expected result
Error handling on UUI side

## Environment

* UUI version: 4.10.2
* Browser name: any
* Operating System: any

**Comment by NatalliaAlieva** [comment]
Released in ver. 5.1.2.
