### ISSUE TITLE
[Data Table]: Unable to resize fixed column

### ISSUE THREAD

**Issue by anna-klempach** [epam/UUI#1509]
## Prerequisites (optional)

Have a Data Table with one column property `fix` set to "left" and `allowColumnsResizing` set to true.
To see the full effect, screen width should be less than the width of the table.

## Steps to Reproduce

1. Hover the border between the fixed column header and the header of the next column, wait for the col-resize cursor to appear.
2. Drag the cursor to resize the column.
3. Observe that the column is not resized.
4. Check the console. Observe the error:
 
![image](https://github.com/epam/UUI/assets/47563276/8972d212-7f7c-42f7-8a06-a70ae8f963e2)

5. Stop dragging the column. Scroll the table horizontally. Observe the column is not fixed any more.
6. Observe the column can now be resized successfully.

## Actual result

Trying to resize a column fixed to left causes TypeError:
 `Uncaught TypeError: Cannot read properties of null (reading 'getBoundingClientRect')
    at DataTableHeaderCell.onResize
`
After the error the column is not fixed any more.

Please, check this sandbox for the reproduction if the issue. Try resizing the "Name" column: [[Data Table]: Unable to resize fixed column](https://codesandbox.io/s/data-table-unable-to-resize-fixed-column-dv7cfg)

Please, check the video for more details:

https://github.com/epam/UUI/assets/47563276/dd4909f6-7ed9-4a5b-84c7-a9ab45e94bf7

## Expected result
If a column is fixed left and Data Table has `allowColumnsResizing` set to true, the column should be resizable the same way as not fixed columns.

## Environment

* UUI version: 5.1.0 in Sandbox, 4.10.1 in Project
* Browser name: Google Chrome
* Operating System: Windows 10

**Comment by NatalliaAlieva** [comment]
Released in 5.1.3 ver.
