### ISSUE TITLE
[PickerInput]: footer doesn't visible in case of modal view with windows scaling 

### ISSUE THREAD

**Issue by JuliaMV** [epam/UUI#1518]
## Steps to Reproduce

1. Display settings should be 125% or reduce window height using resize.
2. Create PickerInput on Modal form and open dropdown.
https://uui.epam.com/documents?id=modals&mode=doc&skin=UUI4_promo&category=components
![2023-07-21_11h01_52](https://github.com/epam/UUI/assets/37875890/23891481-7c17-44d6-b815-4fb021315e97)

## Actual result
Picker footer is hidden outside the viewport and in order to reach it users have to scroll all items (could be difficult with huge items amount)

## Expected result
Footer with controls like "clear all", "select all" is visible on the screen.

## Environment
* UUI version: latest
* Browser name: at least Chrome
* Operating System: Windows with display settings 125% (that is recommended and used by lot of users)

**Comment by AlekseyManetov** [comment]
Currently, we do not have a specific solution for this problem, as the picker body's height is larger than the available free space on top or bottom of the picker. We are facing the challenge of fitting something that is inherently unfittable within the given constraints. As a workaround, we can suggest passing a smaller body height using the dropdownHeight prop to ensure it fits within the screen in this specific case.
