### ISSUE TITLE
[Badge]: improvement according to the design specs

### ISSUE THREAD

**Issue by OlegKryvokobylskyi** [epam/UUI#1537]
### To Do

Align component with design spec (a lot of changes):

Link to [Figma (Specification)](https://www.figma.com/file/dYwal6PrxrPQWg1lL6ijpn/UUI-Specifications?type=design&node-id=856%3A404145&mode=design&t=6Lc38Ub0bkyPAQcy-1)

Link to [Loveship (UUI3) Component](https://www.figma.com/file/M5Njgc6SQJ3TPUccp5XHQx/Loveship-aka-UUI3-(Components)?type=design&node-id=18507%3A299513&mode=design&t=s6KVxqAeewXhLUUd-1)

Link to [Promo (UUI4) Component](https://www.figma.com/file/UyChXPLmyv5zMrOU37KdUL/Promo-aka-UUI4-(Components)?type=design&node-id=13766%3A251862&mode=design&t=tHQ34RyqKdJOeRu3-1)

**Comment by DzmitryTrubchyk** [comment]
Performed design review, see comments below:

1. Let's enable info color at 1st opening
![Image](https://github.com/epam/UUI/assets/44213241/ae17b7f5-9307-4e56-8599-f2250746bc5c)

2. Solid, Neutral option, counter should be white 

![Image](https://github.com/epam/UUI/assets/44213241/ff8ebce2-2f4f-4de6-9f47-08ec43f8126d)

3. All options, incorrect view, close action should be removed from badges 

![Image](https://github.com/epam/UUI/assets/44213241/f6f5dc65-3d3b-47ec-a96a-92f797a63168)

4. There is no 48 size on design (maybe remove, to discuss)

![Image](https://github.com/epam/UUI/assets/44213241/e7fc4385-37a0-4ef3-9ddf-59742fe01845)

5. Solid options, incorrect view. Indicator should not be shown on solid fill. It's correct only for outline fill

![Image](https://github.com/epam/UUI/assets/44213241/62b764c0-05ca-49a8-9bd0-4d3e50de3958)

6. Check count indicator (informer) tokens on design, can be differencies

**Comment by DzmitryTrubchyk** [comment]
@vik753, @AlekseyManetov, please check comment above

**Comment by DzmitryTrubchyk** [comment]
If checkmark _Show theme specific props_ turned off, I expect to see badge in Info color 
![image](https://github.com/epam/UUI/assets/44213241/b5cbf81d-e76a-4221-8ee8-0371336fab4e)

**Comment by NatalliaAlieva** [comment]
We still have discrepancies between the design and implementation. They will be corrected as part of the new task.

**Comment by NatalliaAlieva** [comment]
Released in 5.5.0 ver.
