### ISSUE TITLE
Consider updating existing Vite template

### ISSUE THREAD

**Issue by nandordudas** [epam/UUI#1541]
## Now

https://github.com/epam/UUI/tree/main/templates/uui-vite-template

## To Do

https://github.com/nandordudas/epam-uui-vite-vitest

- please check usage of Vitest (stubs and mocks)
- please check api definition improvement, where api paths are type safe

## Describe the solution you'd like (optional)

There are no concrete solutions, only examples of use.

Please note that the repository is under development and the code may change. When I have free time, I do a few things. I might open pull requests in the future for some code parts.

Thanks for your work on this project 🙇

**Comment by siarheiyelin** [comment]
Hello, 
- I'm not sure regarding the migration from Jest to Vitest. The latter is still 10x times less popular comparing to Jest at the moment (https://npmtrends.com/jest-vs-vitest) So, it seems that keeping the example with Jest has more value. What do you think?
- we wanted to keep this template as simple as possible, so there is no API definition in it. I.e. there is nothing to improve in terms of typing.

**Comment by nandordudas** [comment]
Jest cannot
- test types
- run benchmark
- has easy setup
- manage workspaces
- ...

Vitest can.

Sorry, but npmtrends got me - my heart, my soul - 😆

https://npmcharts.com/compare/vitest,jest?interval=30&log=true
https://npmcharts.com/compare/react,vue?log=true&interval=30

**Comment by siarheiyelin** [comment]
Hello @nandordudas, do you have capacity to contribute and create PR with migration of uui-vite-template to Vitest?

**Comment by nandordudas** [comment]
Hello,
at the end of the week, I think yes.

Do you have any specific requests on the pr or just replace jest with vitest on it?

**Comment by siarheiyelin** [comment]
Hello, no specific requests. Just replace Jest with Vitest. Existing test should successfully pass.

**Comment by AlekseyManetov** [comment]
Hi @nandordudas, do you have any updates regarding update our template to VItest? Maybe you need some help from our side?

**Comment by nandordudas** [comment]
Oh, I'm so sorry. I totally forget it, mea maxima culpa!

I schedule this to the current week.

**Comment by NatalliaAlieva** [comment]
Released in 5.2.0 version.
