### ISSUE TITLE
[PickerInput]: Not display selected value in single selection mode when item id is 0 or false

### ISSUE THREAD

**Issue by torchik-slava** [epam/UUI#1556]
## Steps to Reproduce

1. Create an options list with item, which has id (0 or false).
2. Select option with id 0 or false in picker input

## Actual result

![image](https://github.com/epam/UUI/assets/43167841/e2a01839-86b1-4d5a-9871-7bee8704add4)
[Sandbox link](https://codesandbox.io/s/uui-forked-7prtqw?file=/Example.tsx)

Placeholder instead of selected value

## Expected result

Selected value

## Environment

* UUI version: 5.1.1
* Browser name: Chrome
* Operating System: Windows

**Comment by NatalliaAlieva** [comment]
Released in ver. 5.1.2.
