### ISSUE TITLE
[DataPickerFooter]: is not imported from @epam/loveship v 5.1.0

### ISSUE THREAD

**Issue by Natallia-SN91** [epam/UUI#1565]
## Steps to Reproduce

1. Install @epam/loveship version 5.1.0
2. Try to import DataPickerFooter: import { DataPickerFooter } from "@epam/loveship";

## Actual result

TS2305: Module '"@epam/loveship"' has no exported member 'DataPickerFooter'.
Note: import { PickerFooterProps } from "@epam/uui-core" works well.

## Expected result

 import { DataPickerFooter } from "@epam/loveship" without mistakes;

## Environment

* UUI version: 5.1.0
* Browser name: Chrome: Chrome
* Operating System: Windows

**Comment by NatalliaAlieva** [comment]
Released in ver. 5.1.2.
