### ISSUE TITLE
[Picker Input]: Unexpected 'v' icon is displayed

### ISSUE THREAD

**Issue by Margaryta-Maletz** [epam/UUI#1589]
Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Description (optional)

**This section may be deleted**

Please provide a clear and concise summary, highlighting the main issue or problem encountered.

## Steps to Reproduce

1. Open https://codesandbox.io/s/2c5vtf?file=/Example.tsx
2. Add minCharsToSearch={3}- in both PickerInput components
3. Observe the result
![image](https://github.com/epam/UUI/assets/78261193/94d32b36-df70-402a-acd0-b5d558e9a79b)

## Actual result

field is displayed with 'v' icon
![image](https://github.com/epam/UUI/assets/78261193/80884c73-bdb2-49f2-840a-c9f618a327f2)

## Expected result

field is displayed without 'v' icon
![image](https://github.com/epam/UUI/assets/78261193/914897d7-13ad-460a-9aa4-512790df6521)

## Environment

* UUI version: UUI3_loveship 5.1.0
* Browser name: Google Chrome
* Operating System: Windows

**Comment by AlekseyManetov** [comment]
I supposed that we need to remove this icon when `maxCharsToSearch > 0` prop provided.

**Comment by NatalliaAlieva** [comment]
Released in 5.2.0 version.
