### ISSUE TITLE
[Picker Input]: Incorrect top and bottom padding in drop-down list with two lines text

### ISSUE THREAD

**Issue by Margaryta-Maletz** [epam/UUI#1593]
Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Steps to Reproduce

1. Open the drop-down list
2. Check the distance between boundaries and text of the two-line

## Actual result
![image](https://github.com/epam/UUI/assets/78261193/2466cea2-ed6f-4e46-93fd-4c12725c6f4e)
![image](https://github.com/epam/UUI/assets/78261193/1c2a866a-d7e0-4aa5-b68a-c3a8b6dc97f0)

## Expected result
![image](https://github.com/epam/UUI/assets/78261193/5e9c7f8d-e300-47f8-b450-e892a93937fa)
![image](https://github.com/epam/UUI/assets/78261193/b0bfbfdf-83f7-4b3f-ac77-9df7181fa0d0)

## Environment

* UUI version: UUI3_loveship 5.1.0
* Browser name: Google Chrome
* Operating System: Windows

**Comment by NatalliaAlieva** [comment]
Released in 5.2.0 version.

**Comment by Margaryta-Maletz** [comment]
This bug is still reproduced.
