### ISSUE TITLE
[Labeled Input]: White background of the Info-tooltip is displayed instead of gray

### ISSUE THREAD

**Issue by Margaryta-Maletz** [epam/UUI#1594]
## Description (optional)
Default style of info-tooltip is **gray**
![image](https://github.com/epam/UUI/assets/78261193/a2f8cb0e-6496-470a-b68d-154674982475)

## Steps to Reproduce

1. Open Labeled Input
2. Add attribute info
3. Hover on info-tooltip

## Actual result
Style of info-tooltip is **white**
![image](https://github.com/epam/UUI/assets/78261193/de837964-c6a2-4af8-943c-5c350baf5f71)

## Expected result

Style of info-tooltip is **gray**

## Environment

* UUI version: UUI3_loveship 5.1.0
* Browser name: Google Chrome
* Operating System: Windows

**Comment by NatalliaAlieva** [comment]
Released in 5.1.3 ver.
