### ISSUE TITLE
Scaling icons

### ISSUE THREAD

**Issue by DzmitryTrubchyk** [epam/UUI#1597]
## Change current approach of assets from dedicated size of icon to one common icon asset to be scaled for every viewbox

[Link to Design](https://www.figma.com/file/C8ocLGXmyS7o0BLRrmC9X5/UUI-Assets-(Sandbox)?type=design&node-id=8432%3A24744&mode=design&t=Z9uZYQRn87H4ldIb-1)
![image](https://github.com/epam/UUI/assets/44213241/42363336-4c60-4ab1-9bd0-57333331b639)

**Comment by NatalliaAlieva** [comment]
Released in 5.7.0 ver.
