### ISSUE TITLE
[LabeledInput]: add possibility to customize validationMessage with rich text 

### ISSUE THREAD

**Issue by ghost** [epam/UUI#1601]
## Now
Built-in validation message supposed to be used as string property to a component, so there is not opportunity to customise it, eg. include link to support. 
_Validation message example_: **Something went wrong please contact [support.com](/#)**.

## To Do
Introduce option for the customisation of validation messages.

## Describe the solution you'd like (optional)
Could be an option with the custom rendering or simply changing type to ReactNode.

**Comment by NatalliaAlieva** [comment]
Released in 5.4.0 version.
