### ISSUE TITLE
[Presets]: add the ability to add a modal confirmation window when deleting a preset

### ISSUE THREAD

**Issue by NatalliaAlieva** [epam/UUI#1610]
## Description
Please add a confirmation modal window, since User may accidentally delete a preset without the possibility of restoring it.

**Comment by AlekseyManetov** [comment]
I propose that we modify the `onPresetDelete` function to return a promise. Only after this promise is resolved, we will proceed with the preset deletion on the frontend. This approach allows those who need it to implement a modal confirmation dialog. If the action is canceled within the promise (using reject), no deletion will occur. For those who don't require this extra step, they can simply call the API in this callback directly.

**Comment by DzmitryTrubchyk** [comment]
**Text for modal**

Title: Delete preset
Text: Preset_name will be deleted and can't be restored.

Actions: Cancel/Delete

**Comment by NatalliaAlieva** [comment]
Released in 5.4.0 version.
