### ISSUE TITLE
[Badge]: hover effect is visible in some cases when onClick prop is not provided (Loveship)

### ISSUE THREAD

**Issue by torchik-slava** [epam/UUI#1622]
## Description

Hover effect is visible when 'onClick' prop is not provided,  but 'fill' prop is 'white' or 'none'.

## Steps to Reproduce

1. Open property explorer for Loveship [Link](https://uui.epam.com/documents?category=components&id=badge&mode=propsEditor&skin=UUI3_loveship)
2. Set 'fill' to 'white' or 'none' 
3. Check hover effect

## Actual result

There is hover effect.

## Expected result

There is no hover effect.

## Environment

* UUI version: 5.1.2
* Browser name: Chrome
* Operating System: Windows

**Comment by NatalliaAlieva** [comment]
Released in 5.1.3 ver.
