### ISSUE TITLE
[Accordion]: isOpen value of renderTitle function does not follow this.props.value updates

### ISSUE THREAD

**Issue by aloeugene** [epam/UUI#1623]
## Description

If I'm passing a custom `renderTitle` function to render the title the way I need to, its `isOpen` value doesn't contain the correct and up-to-date `this.props.value` prop. Instead, it is using a local `this.state.opened` value, which is not updated via `this.props.onValueChange`.

Lines in the code I'm referring to:
[Wrong value passed to the `renderTitle`](https://github.com/epam/UUI/blob/main/uui-components/src/layout/Accordion.tsx#L75C38-L75C38)
[Already existing up-to-date value of `this.props.value`](https://github.com/epam/UUI/blob/main/uui-components/src/layout/Accordion.tsx#L63)

## Steps to Reproduce

**Codesandbox example: https://codesandbox.io/s/xenodochial-cloud-syr7fh?file=/src/Example.tsx**

1. Use Accordion component from UUI
2. Pass `value` and `onValueChange` props
3. Pass `renderTitle` prop, which underlying component should operate based on `isOpen` state passed to the function
4. Click the Accordion couple times to close/open it
5. Observe how the `isOpen` value stays the same as initially passed via the `value` prop

## Actual result

What is the current behavior?

`renderTitle => isOpen` value doesn't react to changes from outside, which updates `this.props.value` prop.

## Expected result

`renderTitle => isOpen` value contains up-to-date `this.props.value` value and reacts to `this.props.onValueChange` changes.

## Environment

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* UUI version: provided Sandbox example is using `latest` version of UUI; local codebase I'm working in is (temporarily) tied to `4.11.0-alpha.1`
* Browser name: Arc 1.5.1 (Chromium Engine Version 116.0.5845.110)
* Operating System: MacOS Ventura 13.5

**Comment by NatalliaAlieva** [comment]
Released on 5.1.3 ver.
