### ISSUE TITLE
[PickerInput] Increase custom rendering options

### ISSUE THREAD

**Issue by vasilii-kovalev** [epam/UUI#1627]
## Now

We have a warning message (that we display only the first X items, and the user should use search if they haven't found what they needed) above options in the dropdown menu. Something like this:
![image](https://github.com/epam/UUI/assets/10310491/f8d959cf-0f64-4934-9026-b6c8edb8b22d)
In order to do that, we have to build a custom picker input using `Dropdown` component with a lot of customization.

## To Do

1. Add ability to render header (the area above the options) or even the whole dropdown (like `renderBody` in `Dropdown`). In the second case, it would be great to have as less customization for users to do as possible, if they only need to add something without touching the options list
2. Create an appropriate example in the documentation

**Comment by AlekseyManetov** [comment]
I believe that such customizations are beyond the scope of this component and can add unnecessary complexity. `PickerInput` is intended to be a straightforward user experience component and supposed to be a black-box, with the exception of some popular customizations like `renderRow` and `renderFooter`. I suggest to think about any other workaround outside the `PickerInput`.

For your specific case, it might be a good solution to use the `minCharsToSearch` prop, which displays the body after the user enters a minimum number of symbols in the search field. 
Additionally, you can implement lazy loading for the list, allowing users to scroll down and find the item they need. This is a common default pattern in `PickerInput`, and users are already familiar with it, so there's no need for additional tips or messages
