### ISSUE TITLE
[DataTableRow]: Table row ignores `rawProps` property data

### ISSUE THREAD

**Issue by vasilii-kovalev** [epam/UUI#1628]
## Description

`DataTableRow` ignores `rawProps` property data (for example, data attributes). Code example:

```typescript
<DataTable
  {...view.getListProps()}
  getRows={view.getVisibleRows}
  value={value}
  onValueChange={onValueChange}
  columns={productColumns}
  headerTextCase="upper"
  renderRow={(rowProps) => {
    return (
      <DataTableRow
        {...rowProps}
        // The property's value below is ignored.
        rawProps={{
          ...rowProps.rawProps,
          "data-testid": "row-test-id"
        }}
      />
    );
  }}
/>
```

## Steps to Reproduce

1. Go to this [CodeSandbox](https://codesandbox.io/s/uui-data-table-row-ignores-raw-props-issue-22wktq?file=/Example.tsx)
2. Check rows elements' attributes in DOM

## Actual result

Rows elements don't have `data-testid` attribute. This attribute is not assigned to anything in the DOM.

## Expected result

Rows elements have `data-testid` attribute with value, defined in the example source code.

## Environment

* UUI version: 5.1.2
* Browser name: Google Chrome v.116.0.5845.112
* Operating System: Windows 10 64-bit

**Comment by NatalliaAlieva** [comment]
Released in 5.4.0 version.
