### ISSUE TITLE
[DropdownMenuButton]: incorrect behavior with isActive for same pathname and different search value

### ISSUE THREAD

**Issue by nadiushkaNA** [epam/UUI#1634]
## Steps to Reproduce
![2023-09-04_12h23_20](https://github.com/epam/UUI/assets/11243577/3da30fb1-1a54-425d-b6f6-45c91d3d060c)

https://codesandbox.io/s/uui-forked-53cvyf?file=/Example.tsx

## Actual result

highlighted all items with same pathname if use link, using isActive props don't help

## Expected result

isActive props should be prioritised

**Comment by NatalliaAlieva** [comment]
Released in 5.4.0 version.
