### ISSUE TITLE
[ErrorHandler]: 502 error screen is shown for error 503

### ISSUE THREAD

**Issue by dpalii** [epam/UUI#1637]
Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

## Steps to Reproduce

1. Go to this code sandbox https://codesandbox.io/s/wild-sun-wd8h5q?file=/src/Example.tsx
2. Click on "Throw (502)" button
3. Click on "Throw (503)" button

## Actual result

When error with status 502 is thrown, a default error page is shown.
When error with status 503 is thrown, a page for 502 error is shown.

## Expected result

The error page should match the status code of the error.

## Environment

* UUI version: 5.1.2
* Browser name: MS Edge
* Operating System: Windows

**Comment by AlekseyManetov** [comment]
Hi @dpalii, we'll fix the 503 error page, but for the 502 error code, we'll use the default error page due to its rarity.

**Comment by NatalliaAlieva** [comment]
Released in 5.2.0 version.
