### ISSUE TITLE
[Dropdown]: dropdowns overlap each other

### ISSUE THREAD

**Issue by mylostandromeda** [epam/UUI#1649]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Steps to Reproduce
1. Place vertically two dropdowns that have props like:  
`<Dropdown placement='right-start' openOnHover closeOnMouseLeave='boundary' />`

2. Hover between them.

## Actual result
Dropdowns overlap each other  when you hover between them:
![image](https://github.com/epam/UUI/assets/49440391/8b2c638a-63f1-4680-a107-3248635defe8)

## Expected result
Dropdowns don't have to overlap each other.

* UUI version: 5.1.2
* Browser name: Google Chrome
* Operating System: Windows

**Comment by AlekseyManetov** [comment]
To avoid such behavior you need to manage dropdowns opened state by yourself and close one dropdown when another opened. Here the example how to move state management to your side - https://uui.epam.com/documents?id=dropdown&mode=doc&skin=UUI4_promo&category=components#handle_dropdown_state_by_yourself.
