### ISSUE TITLE
[useForm]: form does not recover from isInProgress state when onSave is rejected

### ISSUE THREAD

**Issue by cpof-tea** [epam/UUI#1652]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Description

`onSave` sets `isInProgress=true`, but does not set `isInProgress=false` back if `onSave` is rejected

## Steps to Reproduce

[Codesandbox](https://codesandbox.io/s/form-not-recovered-from-in-progress-state-3jprfv?file=/Example.tsx)

1. Type required fields
2. Click Save button
3. Verify isInProgress message

## Actual result

Keeps `isInProgress=true` if `onSave` is rejected

## Expected result

Set `isInProgress=false` if `onSave` is rejected

## Environment

* UUI version: 5.1.2
* Browser name: FF 116.0.3
* Operating System: Ubuntu 20.04

**Comment by NatalliaAlieva** [comment]
Released in 5.2.0 version.
