### ISSUE TITLE
[DropdownMenuButton]: Icon looks like it is active, when btn is disabled

### ISSUE THREAD

**Issue by torchik-slava** [epam/UUI#1663]
## Steps to Reproduce

1. Add DropdownMenu with DropdownMenuButton to the page
2. Add icon prop to DropdownMenuButton 
3. Add isDisabled prop to DropdownMenuButton
4. Validate icon color of DropdownMenuButton 

## Actual result

The icon looks like it is active (has different color from text)

Example: Delete btn on screenshots below:
![image](https://github.com/epam/UUI/assets/43167841/2c2d4835-e01b-493d-8ef5-0e00b5eb431a)

## Expected result

The icon looks disabled (has same color as text)

## Environment

* UUI version: 5.1.3
* Browser name: Chrome
* Operating System: Windows

**Comment by dalalvarun** [comment]
Please assign this to me.

**Comment by NatalliaAlieva** [comment]
Temporary merged on  QA env.

**Comment by AlekseyManetov** [comment]
released in 5.2.0
