### ISSUE TITLE
[Docs]: Notifications and modal windows persist when moving between pages

### ISSUE THREAD

**Issue by vasilii-kovalev** [epam/UUI#1670]
## Description

Notifications and modal windows persist when moving between pages using browser "Back"/"Forward" buttons or by clicking on header tabs if the screen is not locked.

## Steps to Reproduce

1. Open the page with Modal Context example: https://uui.epam.com/documents?id=modalContext&mode=doc&skin=UUI4_promo&category=contexts
2. Check that browser "Back" button (near the address bar) is enabled. If not, open any other page on the site and reach the Modal Context page using search bar on the components tab to collect visit history and enable the "Back" button
3. Open the modal window
4. Click on the "Back" button and observe the page
5. Repeat steps 1-4 for Notification Context page: https://uui.epam.com/documents?id=notificationContextDoc&mode=doc&skin=UUI4_promo&category=contexts. In this case, the problem can be reproduced by clicking on the tabs in the header as well

## Actual result

Notifications and modal windows persist when moving between pages.

## Expected result

Notifications and modal windows are closed when leaving the page where they were displayed on.

## Environment

* UUI version: current UUI documentation version
* Browser name: Google Chrome v.117.0.5938.89
* Operating System: Windows 10 64-bit

## Notes

We faced this issue on our project, so it is not a documentation problem only. I didn't want to create a dedicated CodeSandbox example, since your documentation can be used for reproducing the bug 🙂. As far as I understand, there is no automatic out-of-the-box solution for that yet, but maybe during fixing this bug, you'll decide to create one. A React Hook, at least, that would look like this:
```typescript
import {
  useEffect,
} from "react";
import {
  useUuiContext,
} from "@epam/uui-core";

const closeOverlays = (): void => {
  const {
    uuiModals,
    uuiNotifications,
  } = useUuiContext();

  useEffect(
    () => {
      return () => {
        uuiModals.closeAll();

        uuiNotifications.clearAll();
      };
    },
    [
      uuiModals,
      uuiNotifications,
    ],
  );
};
```

Also, in order to avoid working with several entities, a single function can be provided, like `useUuiContext().closeOverlays`/`svc.closeOverlays`.

**Comment by AlekseyManetov** [comment]
I'm not sure that we should have such behavior by default, because in some cases you need to change the url but leave the notification or some modal, for example if you don't make a redirect, but just change some url params. 
Anyway you can implement this behavior on your side, like in your example in notes section, using `closeAll` method of modal and notification contexts.
