### ISSUE TITLE
[PickerInput]: Backspace removes selected value

### ISSUE THREAD

**Issue by oleksapro** [epam/UUI#1705]
## Steps to Reproduce

1. PickerInput with `selectionMode=multi` and `searchPosition=body`

## Actual result

Typing Backspace button removes selected value

[picker-input-backspace-issue.webm](https://github.com/epam/UUI/assets/7101211/04977ebb-20d0-4572-9416-2731340e4260)

## Expected result

Backspace button clears only search input value.

## Environment

* UUI version: 5.2.0
* Browser name: Chrome
* Operating System: Windows

**Comment by NatalliaAlieva** [comment]
Released in 5.4.0 version.
