### ISSUE TITLE
[Rich text editor]: incorrect displaying of tables in Firefox

### ISSUE THREAD

**Issue by dlabkou-epm** [epam/UUI#1718]
Steps to reproduce:
- using Firefox open UUI demo website
- resize table columns
- observe following
![image](https://github.com/epam/UUI/assets/130451924/d24f291f-cae5-4588-bed6-9e8d6b0ab995)

**Comment by NatalliaAlieva** [comment]
Hello @dlabkou-epm !
A similar case is described in [this](https://github.com/epam/UUI/issues/1422) ticket, case No. 7.
