### ISSUE TITLE
[DataTable]: missing `role=table` attribute

### ISSUE THREAD

**Issue by cpof-tea** [epam/UUI#1732]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Description

`DataTable` missing `role=table` attribute

## Steps to Reproduce

[Codesandbox](https://codesandbox.io/s/datatable-missing-role-table-ll2h78)

1. Verify console output for `querySelector("[role=table]")` assertion or check with devtools manually

## Actual result

No presence of `role=table`

## Expected result

Presence of `role=table`

## Environment

* UUI version: 5.2.0
* Browser name: FF 119.0
* Operating System: Ubuntu 20.04

## Comment

Issue introduced in `5.2.0`

**Comment by NatalliaAlieva** [comment]
Released in 5.4.0 version.
