### ISSUE TITLE
[Tooltip]: Value tooltips move with the mouse pointer

### ISSUE THREAD

**Issue by aleksandr-konovalov** [epam/UUI#1740]
STR:
1. Log into the Feedback portal
2. Open any requested review in the Waiting for feedback tab on the Give feedback page
3. Hover your mouse over any value in the Optional section and scroll up or down

AR: The tooltip sticks and moves with the mouse pointer
[Screen Recording 2023-10-02 at 10.51.21.mov](https://jira.epam.com/jira/secure/attachment/3189237/3189237_Screen+Recording+2023-10-02+at+10.51.21.mov)

ER: The tooltip disappears as soon as it is moved with the mouse pointer

* UUI version: 5.1.3
* Browser name: Google Chrome
* Operating System: MacOS Ventura

[EPMRVMA-34395](https://jira.epam.com/jira/browse/EPMRVMA-34395)

**Comment by NatalliaAlieva** [comment]
Hello @aleksandr-konovalov!

Could reproduce this issue on our [site](https://uui.epam.com/documents?category=components&id=tooltip&mode=doc&skin=UUI4_promo) OR create a CodeSandbox example?

**Comment by NatalliaAlieva** [comment]
Not actual.
