### ISSUE TITLE
[Slider]: Sliders set their values when the User moves the mouse over them one by one

### ISSUE THREAD

**Issue by aleksandr-konovalov** [epam/UUI#1741]
Write feedback page/Optional section: Sliders set their values when the User moves the mouse over them one by one

Steps:

Log in to the application
Go to the 'Give feedback' page > 'Give feedback' button
Find any user to give  feedback -> Click 'Give' button
Go down to the optional section
Move quickly your mouse across the sliders from bottom to top
 

AR: Sliders set their values (please see the video below)

[2023-09-15_11h48_23.mp4](https://jira.epam.com/jira/secure/attachment/3167534/3167534_2023-09-15_11h48_23.mp4)

ER: Sliders should not set their values when the User moves the mouse over them one by one

* UUI version: 5.1.3
* Browser name: Google Chrome
* Operating System: MacOS Ventura

[EPMRVMA-34154](https://jira.epam.com/jira/browse/EPMRVMA-34154)

**Comment by NatalliaAlieva** [comment]
Hello @aleksandr-konovalov!

Could you create a CodeSandbox example?

**Comment by NatalliaAlieva** [comment]
Not actual.
