### ISSUE TITLE
[sass/dart-sass] Update to the latest version and fix warnings

### ISSUE THREAD

**Issue by nadiushkaNA** [epam/UUI#175]
**Description**

with "sass": "1.32.0" on the project and UUI 4v ( with "sass": "1.26.11")
we view repeatable warnings. it looks like

![image](https://user-images.githubusercontent.com/11243577/130992485-fff6f1fe-eb2f-48a4-908f-377cf18f6440.png)

**Describe the solution you'd like**

- update to the last version ( 1.38.1 was released)
- fix warnings

**Comment by dsv-sergey** [comment]
Wait for release
