### ISSUE TITLE
[PickerList]: cascadeSelection property doesn't work with search

### ISSUE THREAD

**Issue by andrjak** [epam/UUI#1750]
## Description

A PickerList configured for cascade selection, stops working if the root category is selected from the search.

## Steps to Reproduce

1. Create PickerList with cascadeSelection=true and selectionMode='multi'
2. Use Search to find root item, with some children
3. Reset the search to see the selected item

## Actual result

Nested locations are not selected
https://github.com/epam/UUI/assets/41628215/9b6e917c-e65a-446e-a2ba-81e0b4c0e7e9

## Expected result

Nested locations must be selected

## Environment

* UUI version: 5.2.0
* Browser name: any
* Operating System: any

**Comment by NatalliaAlieva** [comment]
Released in 5.5.0 ver.
