### ISSUE TITLE
Update Assets/Download section on uui site

### ISSUE THREAD

**Issue by DzmitryTrubchyk** [epam/UUI#1756]
## Update outdated data of Design assets

- Remove multiswitch
- Remove Sketch
- Change logo to Figma
Figma svg logo:
![figma](https://github.com/epam/UUI/assets/44213241/d45faee6-ec0d-4eb1-a771-ac34439fdad5)

- Change texts
**UUI Components Library**
4 theme placed in one library: Loveship Light,  Loveship Dark, Promo and Electric

**UUI Assets Library**
Icons, logotypes, cursors

**UUI Patterns**
Templates guidelines

**UUI Illustrtations**
Illustrtations pack in addition (promo images, empty states, etc.)

- Add one more figma link, place 1st in the 2nd row
**UUI Component Guidelines**
Guidelines of UUI component

See details in a screenshot below
![image](https://github.com/epam/UUI/assets/44213241/70fecc21-1f7a-4019-b1f0-bd1e10f30356)

**Comment by NatalliaAlieva** [comment]
Released in 5.4.0 version.
