### ISSUE TITLE
[Modal]: lose overflow hidden when modal open in modal

### ISSUE THREAD

**Issue by AleksSam2020** [epam/UUI#1792]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Steps to Reproduce
Open modal on the screen less than 725px and height of layout more than height of viewport. 
In this modal open modal with ddl. 
When you closed ddl modal, overflow: hidden disappears from body, despite main modal still is opened.
This behavior allows scrolling under modal blocker (it depends on layout). 

## Actual result
overflow: hidden is absent

## Expected result
overflow: hidden is present

https://github.com/epam/UUI/assets/76586401/32584fae-fe3f-4bd9-9e04-866e879f2ba7

UUI version is 5.4.0

**Comment by NatalliaAlieva** [comment]
Released in 5.5.0 ver.
