### ISSUE TITLE
[DataTable]: page crashes on ColumnsConfigurationModal opening

### ISSUE THREAD

**Issue by torchik-slava** [epam/UUI#1800]
## Description (optional)

Page crashes when on ColumnsConfigurationModal opening when DataTable has column with prop `fix: "right"`.

## Steps to Reproduce

1. Fix  colum to right (one more column except required last column for configuration icon).
2. Open ColumnsConfigurationModal. 

![chrome_YSiS5f4Qax](https://github.com/epam/UUI/assets/43167841/4bf41b67-67fa-454a-8312-e63b00c199a5)

## Actual result

Page crashes 

## Expected result

Page work properly

## Environment

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* UUI version: 5.4.1 or 5.4.0 (Sandbox example)
* Browser name: Chrome
* Operating System: Windows

**Comment by AlekseyManetov** [comment]
Released in 5.4.2
