### ISSUE TITLE
[PIckerInput]: bad scroll auto-scaling behaviour for desktop

### ISSUE THREAD

**Issue by MSt1ch** [epam/UUI#1806]
## Prerequisites (optional)

**This section may be deleted**

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Description (optional)

**This section may be deleted**

Please provide a clear and concise summary, highlighting the main issue or problem encountered.

## Steps to Reproduce

https://github.com/epam/UUI/assets/17798957/1ac9d92b-57c4-4acc-8d7e-4c49e4c68050

demo video when picker was broken during scrolling. Can't reproduce into UUI official site.

https://youtu.be/NGzN9g7Ytiw

![Screenshot 2023-12-04 at 13 36 44](https://github.com/epam/UUI/assets/17798957/1f227b5e-e079-43b6-b7ba-b40bbf9b9b04)
![Screenshot 2023-12-04 at 13 37 18](https://github.com/epam/UUI/assets/17798957/ab1b5730-3113-4db5-8886-f71ceb04d6f6)

demo link:
https://codesandbox.io/p/sandbox/uui-forked-w8g8x5?file=%2FExample.tsx%3A63%2C37

## Expected result

My expectation that width of picker body is never changed.

Please describe the behavior you are expecting.

## Environment

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* UUI version: latest
* Browser name: all
* Operating System: all

**Comment by AlekseyManetov** [comment]
Released in 5.4.2
