### ISSUE TITLE
[DataTable, ColumnsConfigurationModal]: pinned right table columns are not displayed in ColumnsConfigurationModal

### ISSUE THREAD

**Issue by torchik-slava** [epam/UUI#1825]
## Description (optional)

When a table column is pinned to the right, it disappears from the list of columns in the ColumnsConfigurationModal.

## Steps to Reproduce

1. Pin colum to right.
2. Open ColumnsConfigurationModal.
3. Check if there is a pinned column in the list

![chrome_0xWJV8bu82](https://github.com/epam/UUI/assets/43167841/597f51d8-3337-404b-a2d3-47434b9226c3)

## Actual result

Pinned column is not in the list of columns

## Expected result

Pinned column is in the list of columns

## Environment

* UUI version: 5.4.2
* Browser name: Chrome
* Operating System: Windows

**Comment by NatalliaAlieva** [comment]
Released in 5.7.0 ver.
