### ISSUE TITLE
Wrong Fonts in Safari

### ISSUE THREAD

**Issue by ldudanova** [epam/UUI#185]
# Expected Behavior

In menu of iHIB and in other components like buttons should be used Source Sans Pro

# Current Behavior

Theres Times New Roman instead of Source Sans Pro

## Steps to Reproduce
![Fonts](https://user-images.githubusercontent.com/61585545/131657768-9b230089-62e4-40f8-9fb2-7af33045cd60.png)

## Context

The library is used in iHUB and CST projects.

* UUI version: ^4.2.0
* Browser name: Safari
* Operating System: iOS

**Comment by ldudanova** [comment]
![Fonts](https://user-images.githubusercontent.com/61585545/131657858-4746aac6-45dc-455d-9f17-6d3bbd2c55a0.png)

**Comment by dsv-sergey** [comment]
@ldudanova Hi! Have you [imported](https://uui.epam.com/documents?id=gettingStarted&mode=doc&skin=UUI4_promo) all the required styles into the index file?

![image](https://user-images.githubusercontent.com/33173033/135067235-bdbcfd3c-f9a4-46f8-a46f-c759bb8eab7f.png)
