### ISSUE TITLE
[Badge]: Counter is not centered on Windows with scale 125%

### ISSUE THREAD

**Issue by ialeksandrovich** [epam/UUI#1852]
## Prerequisites (optional)

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Description (optional)

Counter is not centered on Windows with scale 125%

![1](https://github.com/epam/UUI/assets/18554835/59ae86ad-9f9b-4ae7-8033-94413ea213ee)

## Environment

* UUI version: 5.4.2
* Browser name: Chrome
* Operating System: Windows

**Comment by NatalliaAlieva** [comment]
Released in 5.8.0 ver.
