### ISSUE TITLE
[RTE]: Unpredictable click-to-focus area

### ISSUE THREAD

**Issue by cpoftea** [epam/UUI#1856]
## Prerequisites

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

## Description

RTE textarea field has unpredictable clickable area for click-to-focus functionality. Here's the example, when yellow color highlights exact area where you can click RTE textarea to focus editor.

![Screen Shot 2023-12-15 at 18 09 12](https://github.com/epam/UUI/assets/29537473/22c764b6-452b-418f-8180-83927342d411)
![Screen Shot 2023-12-15 at 18 09 37](https://github.com/epam/UUI/assets/29537473/1f2c48d1-b04f-4827-a47e-8908a8de9e18)

Also, some videos showing that editor blurs clicking outside of text blocks.
![Peek 2023-12-15 19-04.webm](https://github.com/epam/UUI/assets/29537473/0c888332-647e-4555-b9c5-56dbe2fa8b71)
![Peek 2023-12-15 19-042.webm](https://github.com/epam/UUI/assets/29537473/3e9594d4-b8d4-4493-aae3-9c461d030791)

## Environment

* UUI version: 5.4.2
* Browser name: FF 120.0
* Operating System: Ubuntu 20.04

**Comment by NatalliaAlieva** [comment]
Released in 5.5.0 ver.

**Comment by cpoftea** [comment]
Still reproducible at 5.6.0
[Peek 2024-03-07 17-36.webm](https://github.com/epam/UUI/assets/29537473/93ee569a-6c48-46e0-8034-d74228d1f454)

**Comment by NatalliaAlieva** [comment]
Released in 5.7.0 ver.
