### ISSUE TITLE
[APIContext.uploadFile]: fails with runtime error if error response is not JSON

### ISSUE THREAD

**Issue by voroshkov** [epam/UUI#1865]
Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Description (optional)

Implementation of `APIContext.uploadFile` assumes that returned error contains a JSON response:
https://github.com/epam/UUI/blob/3020d24c6ab960efbe903a8baae24969b6e5c412/uui-core/src/services/ApiContext.ts#L365C104-L365C104
But this is not always true and leads to runtime error (if response is HTML, for example), which cannot be caught in the calling code and doesn't allow to recognize that the upload process failed.

## Steps to Reproduce

Use standard upload file example, but change the upload URL to, say, `www.google.com` and try uploading a file

## Actual result

Runtime error: `SyntaxError JSON.parse: unexpected character at line 1 column 1 of the JSON data`

## Expected result

Error should be caught by `catch` method of a `promise` returned from `uploadFile` method, containing the message corresponding to HTTP error code (?)

**Comment by AlekseyManetov** [comment]
@voroshkov, thanks for creating this issue. However, I think we shouldn't take any action on it. Replacing the API with another one, like Google, is not applicable in this case. If you are using our `APIContext.uploadFile`, you should adhere to the contract of this method, which is supposed to be consistent with our file upload components, like FileCard, that rely on this contract. Therefore, you can't return anything other than JSON from your API using this method. Moreover, TypeScript will not allow you to do so.

However, if you need to have a different contract, you can simply implement your own file upload API and use it directly.
