### ISSUE TITLE
[PickerInput]: search results with 'Show only selected' toggle on

### ISSUE THREAD

**Issue by mikzakh** [epam/UUI#1867]
## Description (optional)

Search with 'Show only selected' toggle on does not filter list of picker values.

## Steps to Reproduce

1. Go to [property explorer](https://uui.epam.com/documents?category=components&id=pickerInput&mode=propsEditor&isSkin=true&theme=loveship) of PickerInput component.
2. Set selectionMode to "multi".
3. Choose "SELECT ALL" and "Show only selected" in PickerInput example.
4. Try to search any language (e.g. English).

## Actual result

![pickerinput](https://github.com/epam/UUI/assets/97105597/65492964-d3af-4019-8898-ae713f8185bf)

## Expected result

List of picker input values is filtered according to search string like it works with 'Show selected' toggle of.

![pickerinput1](https://github.com/epam/UUI/assets/97105597/15d635ee-7214-4da6-888b-77c87829b02b)

## Environment

* UUI version: 5.4.3
* Browser name: any
* Operating System: Windows

**Comment by NatalliaAlieva** [comment]
Released in 5.5.0 ver.
