### ISSUE TITLE
Count Indicator. Improve component based on design review

### ISSUE THREAD

**Issue by DzmitryTrubchyk** [epam/UUI#1869]
1. Change value to a number, eg. 99

![Image](https://github.com/epam/UUI/assets/44213241/dfca6501-0d05-4bad-99a2-07a862f225d5)

2. Make gray option like default, in the 1st opening of a property explorer

![Image](https://github.com/epam/UUI/assets/44213241/6f8f96fa-a8a3-4a4d-9075-273ffa441cc7)

3. Strange value, check. Looks like it's broken, shows just number without bg

![Image](https://github.com/epam/UUI/assets/44213241/df49a922-bd33-4629-aa0d-7d917101e3d0)

4. Count indicators with opacity we decided do not implement? To discuss

![Image](https://github.com/epam/UUI/assets/44213241/fb738835-e4ce-433c-b781-fd21bd82ab04)

**Comment by vik753** [comment]
It's already fixed in develop branch. All cases from above.

**Comment by NatalliaAlieva** [comment]
Released in 5.5.0 ver.
