### ISSUE TITLE
'-clickable'  on the dropdown icon, although onClick is  absent

### ISSUE THREAD

**Issue by drobov1k** [epam/UUI#187]
in https://github.com/epam/UUI/blob/main/uui-components/src/inputs/TextInput.tsx#L137

**Comment by dsv-sergey** [comment]
@drobov1k Hi, do you mean that the '-clickable' class should be absent on the cancelIcon if the props onCancel is not passed?

**Comment by dsv-sergey** [comment]
@drobov1k this is done for fake clicking on the dropdown icon
