### ISSUE TITLE
[Modals]: close modal window after changing URL

### ISSUE THREAD

**Issue by NatalliaAlieva** [epam/UUI#1895]
## Now
The modal window remains open even though User leaves the page.

https://github.com/epam/UUI/assets/57751283/ba645b29-0cb9-4a72-9325-a91e6d49ca89

## To Do
The modal window closes automatically if the user leaves the page on which it was triggered.

## Describe the solution you'd like

Let's add new `closeOnRouterChange` prop for `ModalBlocker`, which will manage this behavior, default value will be `closeOnRouterChange={ true }`.

**Comment by vasilii-kovalev** [comment]
Related: https://github.com/epam/UUI/issues/1670

**Comment by NatalliaAlieva** [comment]
Released in 5.7.0 ver.
