### ISSUE TITLE
Icons - better name icon variable in generated code

### ISSUE THREAD

**Issue by jakobz** [epam/UUI#1927]
## Now

On the [Icons page](https://uui.epam.com/documents?id=icons&category=assets), I can copy the icon import code. It looks like this:
```
import { ReactComponent as myIcon } from '@epam/assets/icons/loaders/circle_loader_30.svg';
```

The imported name is always 'myIcon', and we expect user to rename it.

## To Do

Let's generate a better name for the var based on the icon name. For example:
```
circle_loader_30 => circleLoaderIcon
action-currency-18 => actionCurrencyIcon
```

**Comment by NatalliaAlieva** [comment]
Released in 5.7.0 ver.
