### ISSUE TITLE
[Tooltip]: Vertical paddings difference with design

### ISSUE THREAD

**Issue by oleksapro** [epam/UUI#1939]
I have mentioned difference between vertical paddings in Tooltip with design files in figma:

### Design:
Vertical paddings equal **3px**

![image](https://github.com/epam/UUI/assets/7101211/b0bdbf02-7672-4aa2-b008-2cbeda25bdb7)

### Tooltip
Vertical paddings equal **6px**

![image](https://github.com/epam/UUI/assets/7101211/6d286658-26e6-4c7c-9cfc-76acebb84572)

**Comment by OlyaEmelianovich** [comment]
tested in dev 
padding: 3px 12px


![Image](https://github.com/epam/UUI/assets/156677349/f2f29e69-ef70-40bc-b665-1c879bbe44d8)
![Image](https://github.com/epam/UUI/assets/156677349/8dbafc2a-a48b-472e-b3c6-b79bddb3f6d7)

**Comment by NatalliaAlieva** [comment]
Released in 5.6.0 ver.
