### ISSUE TITLE
[DropSpot]: add possibility to provide ReactNode for infoText

### ISSUE THREAD

**Issue by AlekseyManetov** [epam/UUI#1948]
## To Do
Let's change type for `infoText` from `string` to `ReactNode` to be able to provide custom markup like this:
![image](https://github.com/epam/UUI/assets/14283670/33358895-e817-4d77-a6bf-5557cd41c7ae)

Also let's align paddings with [design](https://www.figma.com/file/M5Njgc6SQJ3TPUccp5XHQx/UUI-Components?node-id=502%3A85528&mode=dev).

**Comment by NatalliaAlieva** [comment]
Released in 5.6.0 ver.
