### ISSUE TITLE
[Snackbar] (Loveship only): Missing styles for "Close all notifications" button

### ISSUE THREAD

**Issue by cpof-tea** [epam/UUI#1955]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Description

`@epam/loveship` package has custom `Snackbar` with "Close all notifications" button.
Starting from `v5` button has missing styles.

v4.10.2
![2024-01-29_15-01-54_1706529294_413x269_scrot](https://github.com/epam/UUI/assets/29537473/c222a06e-cb29-4ac8-8563-8de8ffa0398d)

v5.5.0
![2024-01-29_15-01-03_1706529303_417x257_scrot](https://github.com/epam/UUI/assets/29537473/32d5b94d-22f9-40ee-928e-2d0838b26441)

## Steps to Reproduce

1. Open devbox
2. Click "Open notification" button few times
3. Visually verify styles presence on "Close all notifications" button.

* [v5.5.0 devbox with missing styles](https://codesandbox.io/p/devbox/loveship-v5-5-0-missing-close-notifications-button-styles-497d33?file=%2Fsrc%2FExample.tsx%3A22%2C1)
* [v4.10.2 devbox with styles](https://codesandbox.io/p/devbox/loveship-v4-10-2-close-notifications-button-styles-present-vwlqnq?file=%2Fsrc%2FExample.tsx)

## Actual result

Button has missing styles

## Expected result

Button with styles

## Environment

* UUI version: 5.5.0
* Browser name: FF 121.0.1
* Operating System: Ubuntu 20.04

**Comment by NatalliaAlieva** [comment]
Released in 5.6.0 ver.
