### ISSUE TITLE
[PE]: dropdown can be opened/closed when the "isDisabled" property is enabled

### ISSUE THREAD

**Issue by NatalliaAlieva** [epam/UUI#1959]
## Steps to Reproduce
1. Open [Dropdown](https://uui.epam.com/documents?id=dropdown&mode=propsEditor&isSkin=true&category=components) component.
2. Set isDisabled = true.
3. Try to open/close dropdown.

## Actual result
Dropdown opens/closes.

https://github.com/epam/UUI/assets/57751283/83ccaf10-f24e-4a08-9646-b8245cb86459

## Expected result
Dropdown doesn't respond to clicks or hover.

## Environment
* UUI version: 5.4.3
* Browser name: any
* Operating System: any

**Comment by AlekseyManetov** [comment]
The `isDisabled` prop is derived from the `IEditable` interface, inherited in `DropdownProps`. However, most of the `IEditable` props are not required in the Dropdown, such as `isDisabled`, `isInvalid`, `validationMessage`, and others. The Dropdown only requires the `value` and `onValueChange` props. We need to find a way to split the `IEditable` interface into more atomic parts and use only the necessary props in the Dropdown.

**Comment by NatalliaAlieva** [comment]
Released in 5.6.0 ver.
