### ISSUE TITLE
[RTE]: Issues with link editing

### ISSUE THREAD

**Issue by OlyaEmelianovich** [epam/UUI#1968]
## Description
JS duplicates when the link is changed for slate.js

## Steps to Reproduce
1. Open https://uui.epam.com/
2. Open RTE component 
3. Highlight slate.js and change the link for it
**note:** need to select only part of the link, not the whole one. the bug is only for words when there is a dot.
4. Click on Save button
## Actual result
Double JS is displayed when changing the link for slate.js

https://github.com/epam/UUI/assets/156677349/68aa7519-94d7-416f-b1f3-ce616abc0bff

## Expected result
After link change for slate.js  no double js is displayed 

## Description
Redirect to the wrong link after link change for source here and slate js

## Steps to Reproduce
1. Open https://uui.epam.com/
2. Open RTE component 
3. Highlight slate.js and change the link for it
4. Click on Save button
5. Toggle View mode 
6. Click on slate.js and source here 
## Actual result
 The user redirects to the wrong links 

https://github.com/epam/UUI/assets/156677349/83f0f1ad-67fb-48ec-a5d3-4202ae1bc423

 ## Expected result
 The user should redirects to the changed link
Note: browser specific, reproduced only in Safari

## Description
Symbols disappeared after word highlighting with symbols

## Steps to Reproduce
1. Open https://uui.epam.com/
2. Open RTE component 
3. Highlight source here with symbols near to the word and change the link for it
4. Click on Save button 
 ## Actual result
 Symbols disappeared after link change 

https://github.com/epam/UUI/assets/156677349/7774f7fe-735b-422a-af04-b747dbeb1180

 ## Expected result
 Symbols should not disappear after link change

**Comment by NatalliaAlieva** [comment]
One new case has been moved to a separate [ticket](https://github.com/epam/UUI/issues/1986).

**Comment by NatalliaAlieva** [comment]
Released in 5.6.0 ver.
