### ISSUE TITLE
[Paginator, PE]: Component remains enabled when "isDisabled" property set to true

### ISSUE THREAD

**Issue by AlexeySychEpam** [epam/UUI#1971]
## Steps to Reproduce

1. Open/use [Paginator](https://uui.epam.com/documents?category=components&id=paginator&mode=propsEditor&isSkin=true&theme=loveship) component ([sandbox](https://codesandbox.io/p/sandbox/uui-forked-fskmxm))
2. Set isDisabled == true
3. Try to change page

## Actual result

Page still can be changed

https://github.com/epam/UUI/assets/130760323/76b40ec5-8485-4255-b7f2-b0860e9fdefc

https://github.com/epam/UUI/assets/130760323/b920a339-5951-4205-a626-e5f80fe12ec9

## Expected result

Page can not be changed, component grayed out

## Environment

* UUI version: 5.5.1
* Browser name: any
* Operating System: any

**Comment by NatalliaAlieva** [comment]
Released in 5.7.0 ver.
