### ISSUE TITLE
[PickerInput]: Component stays in focused state when clicking outside

### ISSUE THREAD

**Issue by oleg96** [epam/UUI#1989]
## Steps to Reproduce

1. Open/use [PickerInput](https://uui.epam.com/documents?id=pickerInput&mode=doc&isSkin=null&category=components&theme=loveship) component ([sandbox](https://codesandbox.io/p/sandbox/uui-n7qc76))
2. Select value from dropdown list
3. Click outside the component
4. Clear selection using X button
5. Try to loose focus by clicking outside of the component

## Actual result

The component stays in focused state

https://github.com/epam/UUI/assets/3322605/52775d93-a411-485f-8f23-6257e2fc34a4

https://github.com/epam/UUI/assets/3322605/bb32a641-154f-48b8-aeab-ddb02bf03acf

## Expected result

The component loose focus when the user clicks outside of it. Blue border around the PickerInput dissappears

## Environment

* UUI version: 5.5.1
* Browser name: any
* Operating System: any

**Comment by NatalliaAlieva** [comment]
Released in 5.7.0 ver.
