### ISSUE TITLE
[PickerList]: incorrect caption alignment

### ISSUE THREAD

**Issue by nadiushkaNA** [epam/UUI#1997]
## Actual result

![image](https://github.com/epam/UUI/assets/11243577/8cf12375-8df9-4287-967b-8309b84d63bd)

## Expected result

![image](https://github.com/epam/UUI/assets/11243577/ae77bdb1-04a4-432b-9168-13ef61454225)

**Comment by NatalliaAlieva** [comment]
Released in 5.7.0 ver.
