### ISSUE TITLE
[LabeledInput]: Property 'Tooltip' is ignored

### ISSUE THREAD

**Issue by YuriiSkorniakov** [epam/UUI#2000]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Description

The `Tooltip` property is ignored when passed to the `LabeledInput` component.

## Steps to Reproduce

1. Pass a custom Tooltip component to the `LabeledInput` via the `Tooltip` property.

## Actual result

The default library Tooltip is shown.

## Expected result

A custom Tooltip component is shown instead of the default one.

## Environment

* UUI version: 5.6.0
* Browser name: any
* Operating System: any

**Comment by NatalliaAlieva** [comment]
Released in 5.7.0 ver.
