### ISSUE TITLE
[Dropdown]: Warning on opening Dropdown in React Strict mode

### ISSUE THREAD

**Issue by YuriiSkorniakov** [epam/UUI#2002]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Steps to Reproduce

1. Open Dropdown menu in React Strict mode.

## Actual result

![Screenshot 2024-02-15 at 16 56 13](https://github.com/epam/UUI/assets/22319490/65082d77-3240-4cf3-8312-859ecb2a1b93)

## Expected result

There is no warning.

## Environment

* UUI version: 5.6.0
* Browser name: any
* Operating System: any

**Comment by NatalliaAlieva** [comment]
Released in 5.7.0 ver.
