### ISSUE TITLE
[DataTable]: selectAll checkbox visible in header with rowOptions checkbox isVisible - false

### ISSUE THREAD

**Issue by siarhei-epam** [epam/UUI#2017]
## Description (optional)

SelectAll checkbox visible in header with rowOptions checkbox isVisible - false. ArrayDataSource used for display data.

## Steps to Reproduce

https://codesandbox.io/p/sandbox/uui-forked-46tkn7?file=%2FExample.tsx%3A24%2C1

## Actual result

SelectAll checkbox visible in header with rowOptions checkbox isVisible - false.

## Expected result

SelectAll checkbox invisible in header with rowOptions checkbox isVisible - false

* UUI version: 5.6.0

**Comment by AlekseyManetov** [comment]
Released in 5.9.0
