### ISSUE TITLE
[Docs] Make examples with data fetching more clear

### ISSUE THREAD

**Issue by vasilii-kovalev** [epam/UUI#2019]
## Now

It is mostly related to data source usages.
For example, I want to understand, what parameters are essential for lazy loading on scroll in `PickerInput`, and what values should be returned by the server.
Currently, in some cases the parameters are put in `svc.api.demo.<entity>` functions, which are returned from the `api` functions. It takes time to debug it and understand how it works and what it returns.
Here's a code snippet of one of the `PickerInput` component's examples:
https://uui.epam.com/documents?id=pickerInput&mode=doc&isSkin=null&category=components#lazy_list
<img width="743" alt="Code snippet of lazy list example for picket input component" src="https://github.com/epam/UUI/assets/10310491/6886bdb6-7e58-444d-af0c-290d74dd67fa">

I understand, that these functions can be useful, but their current usage in the code snippets is inconvenient to deal with when learning components' functionality.

## To Do

Consider the following options:

* Avoid `svc.api.demo.<entity>` at least for simple cases. Maybe, return a `Promise.resolve(values)` with values defined in the same code snippet, if it makes sense and easy to implement
* Destructure parameters before passing them to `svc.api.demo.<entity>` functions. Also, destructure the result before returning it in the `api` function

**Comment by Kuznietsov** [comment]
@vasilii-kovalev, thanks for your suggestion.

Till that time, I hope these docs will help you: https://uui.epam.com/documents?id=dataSources-lazy-dataSource&mode=doc&isSkin=null&category=dataSources.

**Comment by AlekseyManetov** [comment]
I believe we should include links to the relevant DataSource documentation pages in examples that utilize them, at least.

**Comment by NatalliaAlieva** [comment]
Released in 5.7.0 ver.
