### ISSUE TITLE
[RTE]: unpossible type from first click if editor has placeholder

### ISSUE THREAD

**Issue by nadiushkaNA** [epam/UUI#2022]
## Description

- no default text, only placeholder

## Steps to Reproduce

1. reload page
2. click to input
3. click to input again

## Actual result

user can type only after second click

https://github.com/epam/UUI/assets/11243577/7d127928-4110-424e-9295-3da824e705fc

## Expected result

user can type right after

## Environment

https://codesandbox.io/p/sandbox/uui-forked-797d25?file=%2Findex.tsx%3A10%2C25

**Comment by NatalliaAlieva** [comment]
Released in 5.7.0 ver.
