### ISSUE TITLE
[Blocker] Change the animation time of the spinner

### ISSUE THREAD

**Issue by Egor-Alexandrovich** [epam/UUI#2023]
## Now
 timeout={ { enter: 2000, exit: 1000 } }>

## To Do
timeout={ { enter: 2000, exit: 500 } }>

**Comment by AlekseyManetov** [comment]
After consultations with our Design team, we are decided to decrease exit animation time to 200ms.

**Comment by NatalliaAlieva** [comment]
Released in 5.7.0 ver.
