### ISSUE TITLE
[FlexRow] Add `borderTop` property

### ISSUE THREAD

**Issue by vasilii-kovalev** [epam/UUI#2029]
## Now

Currently, if you want to add a top border, like `ModalFooter` has, you have to add custom styles for `FlexRow`. `topShadow` doesn't suit, because it looks differently.
It is useful for building a footer with control, which is not a part of a modal window. Using modal window-related components for building non-modal window component looks inappropriate.

## To Do

1. Add `borderTop` property to `FlexRow`
2. Remove specific `borderTop` property implementation in `ModalFooter`, because it is build on top of `FlexRow`

**Comment by NatalliaAlieva** [comment]
Released in 5.7.0 ver.
