### ISSUE TITLE
[Docs] Refine "none" values on Property Explorer pages

### ISSUE THREAD

**Issue by vasilii-kovalev** [epam/UUI#2030]
## Now

I've noticed, that [Property Explorer page](https://uui.epam.com/documents?category=components&id=flexRow&mode=propsEditor&isSkin=true&theme=loveship) for `FlexBox` component has "none" value for `size` property, while in fact developers should pass `null` value to avoid adding `min-height`.

It is misleading, because:
1. Before [this commit](https://github.com/epam/UUI/commit/8e91cc82769550a421e7ce7a71770173afba4fb7#diff-5f5f20fa13b454db090e513b8e10f3fd5f748a613ad06412324f9614d633a9f0), it was actually possible to pass a string "none" as a value. Now it is not the case
2. When clicking "View code" at the bottom of the page, one can see `size={null}` passed to the component, not `size="none"`

## To Do

1. Use actual value names in the options' selector on Property Explorer page instead of aliases. At least for the `FlexRow` component, but would be better to review other components as well
3. Review and fix other aliased values, if any

**Comment by vasilii-kovalev** [comment]
Additionally, you may want to come to a unified approach of resetting values. For example, always using `null` or "none". Currently, `background` property in `FlexRow` component's [type definition](https://github.com/epam/UUI/blob/main/loveship/components/layout/FlexItems/FlexRow.tsx#L11) contains value "none" for resetting the value, while `size` has `null` for that. So why to have different values in different components with the same meaning?

**Comment by NatalliaAlieva** [comment]
Released in 5.7.0 ver.
