### ISSUE TITLE
[uui-theme-electric]: Electric theme tokens are not included in the css bundle

### ISSUE THREAD

**Issue by sliim35** [epam/UUI#2035]
## Prerequisites (optional)

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Description (optional)

It seems that theme tokens are not bundled with **electric** theme
`node_modules/@epam/(electric|promo)/styles.css`

### Promo
<img width="983" alt="image" src="https://github.com/epam/UUI/assets/26935057/b118fc4c-c8a5-457e-8f31-9bb5c7737ca0">

### Electric
<img width="702" alt="image" src="https://github.com/epam/UUI/assets/26935057/b57a7649-b1d1-4ef7-96f8-4bba45390f92">

## Steps to Reproduce

1. Follow this [guide](https://uui.epam.com/documents?id=gettingStarted) 
2. Install dependencies
```bash
npm install @epam/uui-core @epam/uui-components @epam/uui
npm install @epam/electric @epam/promo
```
3. Import styles
```tsx
import '@epam/uui-components/styles.css';
import '@epam/uui/styles.css';

import '@epam/electric/styles.css';
import '@epam/promo/styles.css';
```
4. Change class on `body` to either `uui-theme-promo` or `uui-theme-electric`

## Actual result

Electric theme does not work

## Expected result

Electric theme works

## Environment

https://stackblitz.com/edit/vitejs-vite-sa4tvz?file=src%2FApp.tsx

**Comment by AlekseyManetov** [comment]
Hi @sliim35, yes, you should also add one more import with theme for electric skin. I will also add this point to the documentation. Thanks.
