### ISSUE TITLE
[PickerInput]: searchPosition="body" triggers page scroll on dropdown close

### ISSUE THREAD

**Issue by mikzakh** [epam/UUI#2036]
## Description

Issue might be related to [this one](https://github.com/epam/UUI/issues/2005). Similar behavior with scrolling is observed in the case when PickerInput has `searchPosition="body"`.

## Steps to Reproduce

1. Go to [PickerInput docs](https://uui.epam.com/documents?category=components&id=pickerInput&mode=doc&isSkin=true&theme=loveship#search_positions) 'Search positions' section
2. Open pickers body and scroll page

## Actual result

Unintended page scrolling on picker with `searchPosition="body"` dropdown close.

https://github.com/epam/UUI/assets/97105597/ebf20165-5678-440e-8d38-78d5a825d28d

## Expected result

Prevent page from scrolling.

**Comment by NatalliaAlieva** [comment]
Released in 5.7.0 ver.
