### ISSUE TITLE
[DatePicker]: doesn't trigger onValueChange if clear input manually

### ISSUE THREAD

**Issue by AHrakovich** [epam/UUI#2051]
## Description (optional)

If clear input of DatePicker manually, it doesn't trigger onValueChange prop. So that user sees empty input but state wasn't changed, and form validation works unexpectedly.

## Steps to Reproduce

[Codesandbox link](https://codesandbox.io/p/sandbox/uui-forked-z4vkjf?file=%2FExample.tsx%3A6%2C21&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clth81s3j00073b6hhfoz8vl2%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clth81s3j00033b6hegglqv3r%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clth81s3j00043b6hitv50iu8%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clth81s3j00063b6hxspfbry5%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clth81s3j00033b6hegglqv3r%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clth81s3j00023b6h9zwz4h6d%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FExample.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A6%252C%2522startColumn%2522%253A21%252C%2522endLineNumber%2522%253A6%252C%2522endColumn%2522%253A21%257D%255D%257D%255D%252C%2522id%2522%253A%2522clth81s3j00033b6hegglqv3r%2522%252C%2522activeTabId%2522%253A%2522clth81s3j00023b6h9zwz4h6d%2522%257D%252C%2522clth81s3j00063b6hxspfbry5%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clth81s3j00053b6hgx1p6mb8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clth81s3j00063b6hxspfbry5%2522%252C%2522activeTabId%2522%253A%2522clth81s3j00053b6hgx1p6mb8%2522%257D%252C%2522clth81s3j00043b6hitv50iu8%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clth81s3j00043b6hitv50iu8%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

step 1: set date via DatePicker
step 2: clear input manually

https://github.com/epam/UUI/assets/129852632/b5a6bdb8-d699-459f-a571-94ccd68e58cf

## Actual result

the **onValueChange** prop value wasn't called

## Expected result

the value changed, the **onValueChange** prop is called

## Environment

* UUI version: 5.6.0
* Browser name: Google Chrome (122.0.6261.112)

**Comment by NatalliaAlieva** [comment]
Released in 5.8.0 ver.
