### ISSUE TITLE
[DatePicker]: the year view allows to set the negative value

### ISSUE THREAD

**Issue by AHrakovich** [epam/UUI#2052]
## Description (optional)

**year view** allows to set the negative values 

Assumption: actually maybe fixed via filter prop of the DatePicker

Please provide a clear and concise summary, highlighting the main issue or problem encountered.

## Steps to Reproduce

1. Open DatePicker
2. Move via buttons to negative years

![image](https://github.com/epam/UUI/assets/129852632/1212dcc1-5224-4552-9d13-d794e1c0c5f8)

## Actual result

I can choose the negative value for year

## Expected result

I can't choose years less than 0

## Environment

* UUI version: 5.6.0
* Browser name: Google Chrome (122.0.6261.112)

**Comment by NatalliaAlieva** [comment]
Released in 5.8.0 ver.
