### ISSUE TITLE
[PickerInput, Form]: Incorrect validation behavior when valueType=='entity'

### ISSUE THREAD

**Issue by AlexeySychEpam** [epam/UUI#2053]
## Preconditions

1. Use PickerInput with valueType === 'entity'
2. Initialize it by formLens
3. Set formLens metadata to validate field from PickerInput as required and validationOn === 'change'

## Steps to Reproduce

1. Choose any value in PickerInput
2. Clear value by clicking 'x' button
3. Validation message appears -> Correct behavior
4. Try to change value again
5. Validation message disappears before user clicks any value -> Incorrect behavior

Note: when valueType === 'id' Input validation have correct behavior

[Sandbox with example](https://codesandbox.io/p/sandbox/uui-forked-l8w33r?file=%2FExample.tsx%3A10%2C10)

## Actual result

Validation message disappears while choosing new value

https://github.com/epam/UUI/assets/130760323/39fb9319-cdfc-4085-be69-5da679ec5a06

## Expected result

Validation message persists while new value picked

## Environment

* UUI version: 5.6.0
* Browser name: any
* Operating System: any

**Comment by NatalliaAlieva** [comment]
Released in 5.8.0 ver.
