### ISSUE TITLE
[RTE]: image can be edit in View mode

### ISSUE THREAD

**Issue by NatalliaAlieva** [epam/UUI#2057]
## Description
User can resize picture in the View mode.

## Steps to Reproduce
1. Open [RTE](https://uui.epam.com/documents?id=richTextEditor&mode=doc&isSkin=null&category=components) component.
2. Turn on View mode.
3. Try to edit 

## Actual result
User can edit the picture in View mode.

https://github.com/epam/UUI/assets/57751283/c877cb31-6918-40dc-81dc-05e9bc582be3

## Expected result
The picture can't be edit in View mode.

## Environment
* UUI version: 5.6.1
* Browser name: any
* Operating System: any

**Comment by alok-i** [comment]
hello , wanted to contribute to this issue as an open-source contribution.
As seen in the image the options are available when NOT in view mode , in view mode only resizing is happening , do we need to stop that as well?
<img width="919" alt="Screenshot 2024-03-20 at 11 00 07" src="https://github.com/epam/UUI/assets/57743250/2b684049-52fb-437c-aad1-e8f04b58b7a2">

**Comment by AlekseyManetov** [comment]
@alok-i Thank you for your proactivity! However, our team has already addressed this issue. You're welcome to choose another one to contribute to. We greatly appreciate any contributions.

**Comment by NatalliaAlieva** [comment]
Released in 5.7.0 ver.
