### ISSUE TITLE
[Tooltip]: In modal window Tooltip does not have zIndex

### ISSUE THREAD

**Issue by alex9pro** [epam/UUI#206]
# Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Expected Behavior

User can see Tooltip in modal window

# Current Behavior

Tooltip hidden under modal window

## Steps to Reproduce

1. Add Tooltip in modal
2. Hover on Tooltip
3. Tooltip hidden

In Tooltip component there is not  `static contextType = UuiContext;`

## Context

After switching to new Context

* UUI version: 4.2.1

**Comment by jonybekov** [comment]
Hi. @okrypets Any news about this issue? I see you silently closed it

**Comment by okrypets** [comment]
On Friday 17.09.2021, the release rolled forward to version 4.2.3. Have you updated your version?

**Comment by jonybekov** [comment]
Yes! Issue has been resolved! Thanks!
