### ISSUE TITLE
[Blocker]: Links might be clicked when blocker enabled

### ISSUE THREAD

**Issue by alekse1ka** [epam/UUI#2063]
Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Steps to Reproduce

1. Place Button/Form/LinkButton
2. Place the Blocker component with the 'isEnabled' (true) prop.
3. Links might be clicked and links on top of the Blocker component (zIndex issues?)

## Actual result
<img width="1220" alt="image" src="https://github.com/epam/UUI/assets/26390508/515a22c5-e55e-4889-8d4b-0191c7267f25">

## Expected result

Links are blocked by the Blocker component and links might not be clicked

## Environment

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* UUI version: "@epam/uui": "^5.6.1"
* Browser name: Version 122.0.6261.112 (Official Build)
* Operating System: MacOS 14.3.1 (23D60)
* Framework/Library: "react": "^18.2.0"

**Comment by AlekseyManetov** [comment]
Could you please provide a codesandbox with reproduction of this bug. I've tried to make the same variant as on your screenshot, but there everything works fine - https://codesandbox.io/p/sandbox/uui-forked-mfjs9x.

**Comment by AlekseyManetov** [comment]
I couldn't open your sandbox, it seems that you didn't make it public. However, I guess I understand what you changed :)
If you place the blocker before the blocked content in the HTML, it actually will not overlap the content. To avoid this, you should place it after the content. Alternatively, you can add an appropriate `zIndex` to the Blocker on your own using the `cx` prop.

**Comment by AlekseyManetov** [comment]
I don't think it's weird, this is just one possible way. The only one method how we can make the blocker overlay the content is by setting a zIndex value. However, we can't set it from UUI side because we don't know the context in which the Blocker will be used. For example, it might be used in modals with a higher zIndex, and this could break blocker overlapping.
