### ISSUE TITLE
[DataTable]: Component changes sorting when size reduced to minimum

### ISSUE THREAD

**Issue by oleg96** [epam/UUI#2069]
## Steps to Reproduce

1. Open/use [DataTable](https://uui.epam.com/documents?id=tablesOverview&mode=doc&isSkin=null&category=tables) component ([sandbox](https://codesandbox.io/p/sandbox/uui-g4mjvd?file=%2FExample.tsx))
2. Resize column to the min size

## Actual result

On mouse up the sorting changed

https://github.com/epam/UUI/assets/3322605/6a6c3243-3e35-497d-8f42-39ec98a610b9

https://github.com/epam/UUI/assets/3322605/caf987b1-f052-4dff-b47f-9a6ace361b1d

## Expected result

Sorting does not changed when resize finished

## Environment

* UUI version: 5.6.0
* Browser name: any
* Operating System: any

**Comment by NatalliaAlieva** [comment]
Released in 5.7.0 ver.
