### ISSUE TITLE
[DropdownMenuBody]: style prop doesn't applied

### ISSUE THREAD

**Issue by JuliaMV** [epam/UUI#207]
Example from https://uui.epam.com/documents?category=components&id=dropdownMenu&mode=doc&skin=UUI4_promo doesn't work correctly. 

![2021-09-09_12h56_00](https://user-images.githubusercontent.com/37875890/132665395-9807bfdb-c082-4ba5-b08d-69f53d83067c.png)
![2021-09-09_12h55_42](https://user-images.githubusercontent.com/37875890/132665401-9514265e-0ac0-4494-9ba9-ae05435dc8ce.png)

**Comment by JuliaMV** [comment]
issue is reproduced in 4.2.5 version

**Comment by okrypets** [comment]
> issue is reproduced in 4.2.5 version

This has been fixed again and will be in version 4.2.6
