### ISSUE TITLE
[Slider]: incorrect display step in label and tooltip when step is 0.1 when slider has min = 0  and max = 1

### ISSUE THREAD

**Issue by EvgeniyOlesh** [epam/UUI#2078]
## Description

Slider show incorrect value in tooltip and label when step is 0.1 and min = 0 and max = 1

## Steps to Reproduce

1. Create element with next properties: 
```
<Slider
    min={0}
    max={1}
    step={0.1}
    splitAt={0.1}
    showTooltip
    value={0.4}
    onValueChange={(newValue) => { ... }}
 />
```
2. check steps in 0.3, 0.6, 0.7

## Actual result

![image](https://github.com/epam/UUI/assets/161004929/6a18fbd1-1712-4655-a939-3e53fe52d238)

## Expected result

All step display correctly with 0.1 step

## Environment

* UUI version: 5.5.6
* Browser name: any
* Operating System: any

**Comment by NatalliaAlieva** [comment]
Released in 5.8.0 ver.
