### ISSUE TITLE
[PickerInput]: opening a body with prop valueType "entity" triggers changing an "unknown" value to" null"

### ISSUE THREAD

**Issue by siarhei-epam** [epam/UUI#2081]
## Steps to Reproduce

1. set props - valueType: "entity", selectionMode: "single", value: "undefined", dataSource: any
2. open body
3. hover over any element in the body

## Actual result

value changes to "null"

## Expected result

value stay "undefined"

## Environment

* UUI version: 5.6.1

**Comment by NatalliaAlieva** [comment]
Released in 5.7.0 ver.
