### ISSUE TITLE
[DropdownMenu]: no color change on click after switching between components

### ISSUE THREAD

**Issue by oleg96** [epam/UUI#2103]
## Steps to Reproduce

1. Open/use [DropdownMenu](https://uui.epam.com/documents?id=dropdownMenu&mode=doc&isSkin=null&category=components&theme=loveship) component ([sandbox](https://codesandbox.io/p/sandbox/uui-82nn4j?file=%2FExample.tsx))
2. Click at first DropdownMenu dots
3. Click at second DropdownMenu dots

## Actual result

At first click component color changes. When user switches between components, there is no color change on click event

https://github.com/epam/UUI/assets/3322605/7730acd8-1684-4981-b9c5-124764793421

https://github.com/epam/UUI/assets/3322605/35081e67-bfde-466b-aedc-354224f19e2e

## Expected result

Color change occures independently from previous clicks place

## Environment

* UUI version: 5.7.0
* Browser name: any
* Operating System: any

**Comment by NatalliaAlieva** [comment]
Hello @oleg96 !

How can we contact you directly to discuss this issue?

**Comment by AlekseyManetov** [comment]
@oleg96 Or elaborate on which color is not changes, I didn't catch it from your video. Thanks.

**Comment by AlekseyManetov** [comment]
@oleg96 I'm closing it for now. Feel free to reopen it, when you have more details.
