### ISSUE TITLE
Typography for Electric theme, change H1, H2 text styles

### ISSUE THREAD

**Issue by DzmitryTrubchyk** [epam/UUI#2106]
For **Electric theme only**, update text headline styles:
- H1 change from **600** to **400**
- H2 change from **700** to **600**

[Open in Figma](https://www.figma.com/design/M5Njgc6SQJ3TPUccp5XHQx/UUI-Components?node-id=53488-302897&t=bTL7BLwbue1EVPDh-4)

Other properties leave as is

**Comment by vik753** [comment]
We are waiting for the designer's approval.

**Comment by DzmitryTrubchyk** [comment]
@vik753, the task description is finished, so, you can take it

**Comment by vik753** [comment]
@DzmitryTrubchyk the Figma doesn't match your description. Fix the Figma examples, please.

**Comment by NatalliaAlieva** [comment]
> @DzmitryTrubchyk the Figma doesn't match your description. Fix the Figma examples, please.

Yes, in [this](https://www.figma.com/design/M5Njgc6SQJ3TPUccp5XHQx/UUI-Components?node-id=29821-19589&t=0PwxdpcioH605nMe-0) part of the design, the font weight values have not been updated yet.
<img width="720" alt="Screenshot 2024-08-05 at 11 44 13" src="https://github.com/user-attachments/assets/db0fbe86-99fd-4616-b9ff-8777577449d3">

**Comment by NatalliaAlieva** [comment]
Released in 5.9.0 ver.
