### ISSUE TITLE
Update current surface tokens, according to design

### ISSUE THREAD

**Issue by DzmitryTrubchyk** [epam/UUI#2120]
What was changed

- Tokens inherited from in dark/light theme (check Json file)

Json file
[Theme 4.json](https://github.com/epam/UUI/files/14901934/Theme.4.json)

Design, dark theme https://www.figma.com/file/M5Njgc6SQJ3TPUccp5XHQx/UUI-Components?type=design&node-id=31506%3A6909&mode=design&t=b4UWTe6Zwd54NboT-1

White theme https://www.figma.com/file/M5Njgc6SQJ3TPUccp5XHQx/UUI-Components?type=design&node-id=30934%3A165024&mode=design&t=b4UWTe6Zwd54NboT-1

**Comment by DzmitryTrubchyk** [comment]
Design Review:
Everything is good, but have ti think how to show colors with opacity

now it's a bit cinfusing
![Image](https://github.com/epam/UUI/assets/44213241/66d7b723-8eca-49f1-b891-ba54c0c794bb)

correct color property 

![Image](https://github.com/epam/UUI/assets/44213241/b2302881-60fa-499a-bf8a-7c7eb3729baf)

**Comment by AlekseyManetov** [comment]
> Everything is good, but have ti think how to show colors with opacity

In Themes we don't use RGBA value for the tokens, we use HEX, therefore we can display only hex value in documentation

**Comment by NatalliaAlieva** [comment]
Released in 5.8.0 ver.
