### ISSUE TITLE
Improve Status Indicator, according to design

### ISSUE THREAD

**Issue by DzmitryTrubchyk** [epam/UUI#2122]
What was changed
- Dot size in 12 and 24 component sizes
Link to the design https://www.figma.com/file/M5Njgc6SQJ3TPUccp5XHQx/UUI-Components?type=design&node-id=18328%3A299803&mode=design&t=EkHephVToQJqCOEk-1

**Comment by NatalliaAlieva** [comment]
Released in 5.8.0 ver.
