### ISSUE TITLE
Electric theme: Get back accent green button

### ISSUE THREAD

**Issue by DzmitryTrubchyk** [epam/UUI#2127]
Change accent button to green (emerald)
Design https://www.figma.com/file/M5Njgc6SQJ3TPUccp5XHQx/UUI-Components?type=design&node-id=27633%3A199611&mode=design&t=b4UWTe6Zwd54NboT-1
Json
[Theme 4.json](https://github.com/epam/UUI/files/14901979/Theme.4.json)

![image](https://github.com/epam/UUI/assets/44213241/f1b5eaa2-c177-4625-82d7-55dee62447cb)

**Comment by NatalliaAlieva** [comment]
Released in 5.8.0 ver.
