### ISSUE TITLE
Avatar: Add 96 and 120 sizes

### ISSUE THREAD

**Issue by DzmitryTrubchyk** [epam/UUI#2166]
Add 96 and 120 avatar sizes
[Design](https://www.figma.com/file/M5Njgc6SQJ3TPUccp5XHQx/UUI-Components?type=design&node-id=69-12951&mode=design&t=ROlSbd1dgo8UPNVx-4)

**Comment by NatalliaAlieva** [comment]
It was decided to implement the ability to set any avatar size by entering a number into a numeric input field.

**Comment by NatalliaAlieva** [comment]
Released in 5.8.0 ver.
