### ISSUE TITLE
Tokens page: Align ordering of Surfaces, text and other tokens with Json

### ISSUE THREAD

**Issue by DzmitryTrubchyk** [epam/UUI#2167]
**New req, keep alphabet ordering**

Old req:
_Align sorting of core tokens inside category (eg. Surfaces) with Json_

**Comment by DzmitryTrubchyk** [comment]
_Text-bg-higlight_ must be the last one
![Image](https://github.com/epam/UUI/assets/44213241/b6829870-eeee-4ca4-8651-bd7593839a9e)

**Comment by NatalliaAlieva** [comment]
Released in 5.8.0 ver.
