### ISSUE TITLE
[Button]: Align white buttons according to design. Add white buttons to all themes

### ISSUE THREAD

**Issue by DzmitryTrubchyk** [epam/UUI#2174]
[Find design here](https://www.figma.com/file/M5Njgc6SQJ3TPUccp5XHQx/UUI-Components?type=design&node-id=48766-160954&mode=design&t=iY29VKnIXFTVxqRJ-4)

![image](https://github.com/epam/UUI/assets/44213241/50991ccd-157e-4cf6-90df-1cbdc102ba77)

Loveship Light, Promo, Electric:

<img width="426" alt="image" src="https://github.com/epam/UUI/assets/95909531/fc82fbcb-e348-4c59-8f53-6d886abf4661">

`"button-white": {
      "button-bg-color": {
        "value": "{core.neutral.neutral-0}",
        "type": "color"
      },
      "button-bg-color-hover": {
        "value": "{core.neutral.neutral-10}",
        "type": "color"
      },
      "button-bg-color-active": {
        "value": "{core.neutral.neutral-30}",
        "type": "color"
      },
      "button-bg-color-halftone": {
        "value": "rgba({core.neutral.neutral-0}, 15%)",
        "type": "color"
      },
      "button-bg-color-halftone-hover": {
        "value": "rgba({core.neutral.neutral-0}, 22%)",
        "type": "color"
      },
      "button-bg-color-halftone-active": {
        "value": "rgba({core.neutral.neutral-0}, 29%)",
        "type": "color"
      },
      "button-border-color": {
        "value": "{core.neutral.neutral-0}",
        "type": "color"
      },
      "button-border-color-hover": {
        "value": "{core.neutral.neutral-0}",
        "type": "color"
      },
      "button-border-color-active": {
        "value": "{core.neutral.neutral-0}",
        "type": "color"
      },
      "button-bg-color-disabled": {
        "value": "rgba({core.neutral.neutral-0}, 10%)",
        "type": "color"
      },
      "button-border-color-disabled": {
        "value": "rgba({core.neutral.neutral-0}, 30%)",
        "type": "color"
      },
      "button-caption-color": {
        "value": "{core.neutral.neutral-70}",
        "type": "color"
      },
      "button-caption-halftone-color": {
        "value": "{core.neutral.neutral-0}",
        "type": "color"
      },
      "button-caption-color-disabled": {
        "value": "rgba({core.neutral.neutral-0}, 40%)",
        "type": "color"
      }
    }`

Loveship Dark:

<img width="414" alt="image" src="https://github.com/epam/UUI/assets/95909531/3a483dce-b40d-4dad-b8b9-5bfaa91a5d8d">

`"button-white": {
      "button-bg-color": {
        "value": "{core.neutral.neutral-0}",
        "type": "color"
      },
      "button-bg-color-hover": {
        "value": "{core.neutral.neutral-10}",
        "type": "color"
      },
      "button-bg-color-active": {
        "value": "{core.neutral.neutral-20}",
        "type": "color"
      },
      "button-bg-color-halftone": {
        "value": "rgba({core.neutral.neutral-0}, 15%)",
        "type": "color"
      },
      "button-bg-color-halftone-hover": {
        "value": "rgba({core.neutral.neutral-0}, 22%)",
        "type": "color"
      },
      "button-bg-color-halftone-active": {
        "value": "rgba({core.neutral.neutral-0}, 29%)",
        "type": "color"
      },
      "button-border-color": {
        "value": "{core.neutral.neutral-0}",
        "type": "color"
      },
      "button-border-color-hover": {
        "value": "{core.neutral.neutral-0}",
        "type": "color"
      },
      "button-border-color-active": {
        "value": "{core.neutral.neutral-0}",
        "type": "color"
      },
      "button-bg-color-disabled": {
        "value": "rgba({core.neutral.neutral-0}, 10%)",
        "type": "color"
      },
      "button-border-color-disabled": {
        "value": "rgba({core.neutral.neutral-0}, 30%)",
        "type": "color"
      },
      "button-caption-color": {
        "value": "{core.neutral.neutral-70}",
        "type": "color"
      },
      "button-caption-halftone-color": {
        "value": "{core.neutral.neutral-0}",
        "type": "color"
      },
      "button-caption-color-disabled": {
        "value": "rgba({core.neutral.neutral-0}, 40%)",
        "type": "color"
      }
    },`

**Comment by und3rtak3rz** [comment]
Loveship Light, Promo, Electric:
`"button-white": {
      "button-bg-color": {
        "value": "{core.neutral.neutral-0}",
        "type": "color"
      },
      "button-bg-color-hover": {
        "value": "{core.neutral.neutral-10}",
        "type": "color"
      },
      "button-bg-color-active": {
        "value": "{core.neutral.neutral-30}",
        "type": "color"
      },
      "button-bg-color-halftone": {
        "value": "rgba({core.neutral.neutral-0}, 15%)",
        "type": "color"
      },
      "button-bg-color-halftone-hover": {
        "value": "rgba({core.neutral.neutral-0}, 22%)",
        "type": "color"
      },
      "button-bg-color-halftone-active": {
        "value": "rgba({core.neutral.neutral-0}, 29%)",
        "type": "color"
      },
      "button-border-color": {
        "value": "{core.neutral.neutral-0}",
        "type": "color"
      },
      "button-border-color-hover": {
        "value": "{core.neutral.neutral-0}",
        "type": "color"
      },
      "button-border-color-active": {
        "value": "{core.neutral.neutral-0}",
        "type": "color"
      },
      "button-bg-color-disabled": {
        "value": "rgba({core.neutral.neutral-0}, 10%)",
        "type": "color"
      },
      "button-border-color-disabled": {
        "value": "rgba({core.neutral.neutral-0}, 30%)",
        "type": "color"
      },
      "button-caption-color": {
        "value": "{core.neutral.neutral-70}",
        "type": "color"
      },
      "button-caption-halftone-color": {
        "value": "{core.neutral.neutral-0}",
        "type": "color"
      },
      "button-caption-color-disabled": {
        "value": "rgba({core.neutral.neutral-0}, 40%)",
        "type": "color"
      }
    }`

Loveship Dark:
`"button-white": {
      "button-bg-color": {
        "value": "{core.neutral.neutral-0}",
        "type": "color"
      },
      "button-bg-color-hover": {
        "value": "{core.neutral.neutral-10}",
        "type": "color"
      },
      "button-bg-color-active": {
        "value": "{core.neutral.neutral-20}",
        "type": "color"
      },
      "button-bg-color-halftone": {
        "value": "rgba({core.neutral.neutral-0}, 15%)",
        "type": "color"
      },
      "button-bg-color-halftone-hover": {
        "value": "rgba({core.neutral.neutral-0}, 22%)",
        "type": "color"
      },
      "button-bg-color-halftone-active": {
        "value": "rgba({core.neutral.neutral-0}, 29%)",
        "type": "color"
      },
      "button-border-color": {
        "value": "{core.neutral.neutral-0}",
        "type": "color"
      },
      "button-border-color-hover": {
        "value": "{core.neutral.neutral-0}",
        "type": "color"
      },
      "button-border-color-active": {
        "value": "{core.neutral.neutral-0}",
        "type": "color"
      },
      "button-bg-color-disabled": {
        "value": "rgba({core.neutral.neutral-0}, 10%)",
        "type": "color"
      },
      "button-border-color-disabled": {
        "value": "rgba({core.neutral.neutral-0}, 30%)",
        "type": "color"
      },
      "button-caption-color": {
        "value": "{core.neutral.neutral-70}",
        "type": "color"
      },
      "button-caption-halftone-color": {
        "value": "{core.neutral.neutral-0}",
        "type": "color"
      },
      "button-caption-color-disabled": {
        "value": "rgba({core.neutral.neutral-0}, 40%)",
        "type": "color"
      }
    },`

**Comment by NatalliaAlieva** [comment]
Released in 5.8.0 ver.
