### ISSUE TITLE
Inline svg instead of SVG sprite

### ISSUE THREAD

**Issue by alex9pro** [epam/UUI#219]
**Description**

Every page has svg sprite with bunch of icons 114 items.

I see some disadvantages in this approach
- usually on page used just some of them +-10 and other useless
- it takes time for browser to process them all and append in DOM
- in every test we have this looong sprite (with react-testing-library), it complicates test's debugging 

**Describe the solution you'd like**

I'd ask you to consider possibility use svg inline in-place svg icons

**Comment by AlekseyManetov** [comment]
HI, we will change our webpack svg loader to load icons as react components in nearest release.
