### ISSUE TITLE
[Form]: Form validation message translate

### ISSUE THREAD

**Issue by AlexDormash** [epam/UUI#2197]
Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [x] I checked to make sure that this issue has not already been filed
- [x] I checked the documentation and found no answer

## Steps to Reproduce

1. Trigger validation message
2. Change the language(while validation message is active)
3. Validation message is still on previous language

## Actual result

Validation message is on previous language
![image](https://github.com/epam/UUI/assets/28618368/d36ba81c-732d-4eb3-922d-c602fc973945)

## Expected result

Validation message is on selected language
![image](https://github.com/epam/UUI/assets/28618368/13eeb69e-2273-4d3c-b6cc-14815e539e22)

## Environment

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* UUI version: 5.6.1
* Browser name: Chrome
* Operating System: Windows OS

**Comment by AlekseyManetov** [comment]
UUI components do not have any subscription to localization changes. Localization is stored in the global `i18n` variable, and changing it does not trigger an app update itself. Therefore, it's required to reload the app when the language is changed on your side. For example, you can store the selected language in the URL, and a URL change will trigger an app update.
