### ISSUE TITLE
PickerList: Switcher [Show only selected] moved to 'Off' value when select some value from search and move switcher to 'On' position

### ISSUE THREAD

**Issue by LobkovichH** [epam/UUI#2209]
## Prerequisites (optional)

**This section may be deleted**

Please answer the following questions for yourself before submitting an issue.

- [V] I am running version 5.7.1
- [V] I checked the documentation and found no answer
- [V] I checked to make sure that this issue has not already been filed

## Steps to Reproduce

1.Click [Show all]
2.type some value in search field
3.check some checkbox
4.move switcher [Show only selected] to 'On' position

## Actual result

What is the current behavior?

To provide more details please include screenshots, video, animated GIFs, or minimal code snippets where appropriate.

Current result:

Switcher [Show only selected] moved to 'Off' value

Expected result:

Switcher moved into 'On' position, only selected items are displayed

## Environment

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* UUI version: 5.7.1.

https://github.com/epam/UUI/assets/168416743/31d5abaa-7a9d-4e2d-a561-04b4a7b4b2ec

* Google Chrome:
* Operating System: Windows 11

**Comment by NatalliaAlieva** [comment]
Released in 5.8.0 ver.
