### ISSUE TITLE
PickerList: wrong selected values in case of nested nodes selected

### ISSUE THREAD

**Issue by LobkovichH** [epam/UUI#2210]
## Prerequisites (optional)

**This section may be deleted**

Please answer the following questions for yourself before submitting an issue.

- [V] I am running the latest version
- [V] I checked the documentation and found no answer
- [V] I checked to make sure that this issue has not already been filed

## Description (optional)

Parent node with selected child node is displayed instead of only parent node in case if user selected child node firstly and then selected parent node (cascadeSelection: 'implicit')

## Steps to Reproduce

1. expand list and select only child node
2. Click [Select]
3. Expand list and select  parent node to which child is belong 
4. Click [Select]

## Actual result

Parent and Child node are selected

## Expected result

Only parent node is selected

## Environment

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* UUI version: 5.7.1.
* Browser name: Google Chrome
* Operating System: Windows 11

https://github.com/epam/UUI/assets/168416743/7ca02f60-5052-455f-9a7b-4ea5b68e1d9c

**Comment by NatalliaAlieva** [comment]
Released in 5.8.0 ver.
