### ISSUE TITLE
[Filtered Table]: Align demo pattern with Figma, fix minor bugs

### ISSUE THREAD

**Issue by DzmitryTrubchyk** [epam/UUI#2222]
## During design review some inconsistencies and poor UX were found
* UUI version: current production
* Browser name: Chrome
* Operating System: MacOS

List of improvements:

1. Change current bg on filtering panel to surface-main. [See on Design](https://www.figma.com/file/cAd3iaIW4JxJapIVTrE96b/UUI-%E2%80%93-Tables-%26-Filters-(Demo-%26-Examples)?type=design&node-id=6560-62665&mode=design&t=BtvMMoOxG0prrRan-4)
![image](https://github.com/epam/UUI/assets/44213241/694ca9bc-f67b-4d5d-b5f9-936f87adfc45)

2. Delete colon mark from filter tag for multi select, after filter deselection, see details to reproduce:
- Apply any item in filter, colon mark appears right before selected item name (correct behavior)
![image](https://github.com/epam/UUI/assets/44213241/a4f0aa19-d148-48e8-93b9-fa68c534c9f6)

- When I deselect applied filter item, colon mark still placed inside filter tag, but filter items list is empty
![image](https://github.com/epam/UUI/assets/44213241/449a10f6-a22b-4a2d-af19-f612b3d2579f)

3. In the 1st table screen (after 1st page opening), decrease columns width according to design, for avoiding too much empty space. [See on design](https://www.figma.com/file/cAd3iaIW4JxJapIVTrE96b/UUI-%E2%80%93-Tables-%26-Filters-(Demo-%26-Examples)?type=design&node-id=6427-42779&mode=design&t=BtvMMoOxG0prrRan-4)

As is:
![image](https://github.com/epam/UUI/assets/44213241/2aa09699-7c85-44d3-84c0-30e22f1e8eac)

As should be:
![image](https://github.com/epam/UUI/assets/44213241/d900808b-d883-4098-aaa4-d5087c93a496)

4. Change Manager link style to regular. **Turned into [separate issue](https://github.com/epam/UUI/issues/2276)

5. Rename columns and filters:
Profile Status → Status
Profile Type → Type

[See details on design](https://www.figma.com/file/cAd3iaIW4JxJapIVTrE96b/UUI-%E2%80%93-Tables-%26-Filters-(Demo-%26-Examples)?type=design&node-id=6560-62666&mode=design&t=MD5pCRDG3Glpc4o4-4)

6. Change delete icon, [according to design](https://www.figma.com/file/cAd3iaIW4JxJapIVTrE96b/UUI-%E2%80%93-Tables-%26-Filters-(Demo-%26-Examples)?type=design&node-id=6581-76693&mode=design&t=MD5pCRDG3Glpc4o4-4)
![image](https://github.com/epam/UUI/assets/44213241/bd71fc8d-d2a9-4be2-8fcb-d8839b909127)

7. Remove fllter mark from all table headers, if it's active
![image](https://github.com/epam/UUI/assets/44213241/1c26995b-8ac5-4a12-b36e-a1055ffdfdfc)

**Comment by AlekseyManetov** [comment]
case 5 fixed by https://github.com/epam/UUI/pull/2314

**Comment by NatalliaAlieva** [comment]
The delete icon near 'remove filter' needs to be changed.
<img width="565" alt="Screenshot 2024-07-02 at 21 50 59" src="https://github.com/epam/UUI/assets/57751283/a07f9f99-e0c7-4975-a0d9-369c8bfcfdbf">

**Comment by NatalliaAlieva** [comment]
Released in 5.8.2 ver.
