### ISSUE TITLE
Chevron icon: Update icon pack with improved chevron icons (TBD) and minor improvements

### ISSUE THREAD

**Issue by DzmitryTrubchyk** [epam/UUI#2228]
## Currently, the chevron icon size is smaller, than other ones. 
It's needed to change these icons, for making better visual weight balance between assets and UI part, consequently

Please, find updated icon pack here (TBD)

Differences between components. [Figma link](https://www.figma.com/file/ozuZOZNqKMUGiwLKYlsfkT/UUI-%E2%80%93-Forms%3A-Text-Input-(Sandbox)?type=design&node-id=1420%3A16245&mode=design&t=rWhL75uGDcE04jlH-1):
![image](https://github.com/epam/UUI/assets/44213241/72f8c039-1f66-43d3-8fa9-1d9c096bee79)

Differences in application example. [Figma link](https://www.figma.com/file/ozuZOZNqKMUGiwLKYlsfkT/UUI-%E2%80%93-Forms%3A-Text-Input-(Sandbox)?type=design&node-id=1421-58017&mode=design&t=rWhL75uGDcE04jlH-4):
![image](https://github.com/epam/UUI/assets/44213241/24636591-984d-47d7-a0a9-be53216063c8)
![image](https://github.com/epam/UUI/assets/44213241/4647357c-f494-407d-93f4-081e0acce09a)

The rest changes:
- Outline variant added for content-person_group

**Comment by NatalliaAlieva** [comment]
I have collected all questions and comments in the [file](https://docs.google.com/document/d/1tcLAtphMKCl9PqEiBkKuKaGcyv9wB1C80toIvQQUq5E/edit). 
@DzmitryTrubchyk, @AlekseyManetov please take a look at it.

**Comment by NatalliaAlieva** [comment]
Released in 5.9.0 ver.
