### ISSUE TITLE
[Date Range Picker]: improvements according to design

### ISSUE THREAD

**Issue by NataliiaSkorobohatova** [epam/UUI#2244]
**Loveship Dark theme**.
Change the background color in the dropdown according the design - _surface-main_ `#272833`

<img width="761" alt="Screenshot 2024-05-14 at 17 49 31" src="https://github.com/epam/UUI/assets/166697099/7edcc8f1-9d94-4ca6-a1ca-1b76c32f4cf0">

[Find design here](https://www.figma.com/design/M5Njgc6SQJ3TPUccp5XHQx/UUI-Components?node-id=50381-80141&t=F9DrdGTTclTySJ0T-4)

**Comment by NatalliaAlieva** [comment]
Hi @DzmitryTrubchyk,
It is necessary to determine where the correct colors for the divider are. On the frontend we have **Loveship Dark:** #474A59; **Loveship Light, Promo, Electric:** #CED0DB, and in Figma **Loveship Dark:** #383B4A; **Loveship Light, Promo, Electric:** #E1E3EB.
<img width="946" alt="Screenshot 2024-05-20 at 15 17 18" src="https://github.com/epam/UUI/assets/57751283/be957fca-bb0f-49aa-84e0-9e5f18dfd2fd">

**Comment by NatalliaAlieva** [comment]
Released in 5.8.0 ver.
