### ISSUE TITLE
[Time Picker]: improvements according to design 

### ISSUE THREAD

**Issue by NataliiaSkorobohatova** [epam/UUI#2249]
**All themes**.
Change the two dots color in the dropdown according the design - _text-tetriary_ (for **Loveship Light, Promo, Electric** theme `#6C6F80`, for **Loveship Dark** `#ACAFBF`)

<img width="631" alt="Screenshot 2024-05-14 at 20 01 28" src="https://github.com/epam/UUI/assets/166697099/3609a9a2-2d33-4ec2-a56c-a1b74bc06046">

[Find design here](https://www.figma.com/file/M5Njgc6SQJ3TPUccp5XHQx/UUI-Components?type=design&node-id=50420-100348&mode=design&t=4OmFFOGKtnhGf2YZ-4)

**Comment by NatalliaAlieva** [comment]
Released in 5.8.0 ver.
