### ISSUE TITLE
[DataTable]: unable to unpin column when it has isAlwaysVisible attribute

### ISSUE THREAD

**Issue by oleg96** [epam/UUI#2258]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Steps to Reproduce

Open the sandbox with DataTable example [UUI Codesandbox](https://codesandbox.io/p/sandbox/uui-forked-yydwtv?file=%2FExample.tsx%3A14%2C53&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clw90fkbo00073b6kmnaqmyjr%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clw90fkbo00033b6k9u2box28%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clw90fkbo00043b6kfth8f08o%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clw90fkbo00063b6kxpa97m1p%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clw90fkbo00033b6k9u2box28%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clw90fkbn00023b6kw5girk5g%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FExample.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A14%252C%2522startColumn%2522%253A53%252C%2522endLineNumber%2522%253A14%252C%2522endColumn%2522%253A53%257D%255D%257D%255D%252C%2522id%2522%253A%2522clw90fkbo00033b6k9u2box28%2522%252C%2522activeTabId%2522%253A%2522clw90fkbn00023b6kw5girk5g%2522%257D%252C%2522clw90fkbo00063b6kxpa97m1p%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clw90fkbo00053b6ky1vve7th%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clw90fkbo00063b6kxpa97m1p%2522%252C%2522activeTabId%2522%253A%2522clw90fkbo00053b6ky1vve7th%2522%257D%252C%2522clw90fkbo00043b6kfth8f08o%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clw90fkbo00043b6kfth8f08o%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D).

1. Open Configure columns
2. Move Name column to pinned section
3. Try to move Name column back to not pinned section

## Actual result

It is not possible to move column back to not pinned section if it has isAlwaysVisible attribute

https://github.com/epam/UUI/assets/3322605/a1f760f1-99aa-4a2b-8a1d-905fe45d8e23

## Expected result

It is possible to move column back to not pinned section if it has isAlwaysVisible attribute, and not possible to move it into Hidden in table

## Environment

* UUI version: 5.7.2
* Browser name: any
* Operating System: any

**Comment by AlekseyManetov** [comment]
We have decided to adjust the logic for the `isAlwaysVisible` prop. When this prop is enabled, the column will not be allowed to be pinned/unpinned, moved, or unchecked. Additionally, if the fix value is not specified, we will always forcibly fix the column to the left. We believe that typically, when the `isAlwaysVisible` value is set, it indicates a column without which the table would not make sense, and in such cases, it should always remain static in place.

**Comment by NatalliaAlieva** [comment]
Released in 5.8.0 ver.
