### ISSUE TITLE
Button, fixed or fill property with icon left: change icon position according to design

### ISSUE THREAD

**Issue by DzmitryTrubchyk** [epam/UUI#2277]
## Now. Icon leaves with left pinned position
![image](https://github.com/epam/UUI/assets/44213241/a0f6db14-ed8d-4acc-b8eb-f8256a970f5a)

## To Do. Keep icon right near caption
![image](https://github.com/epam/UUI/assets/44213241/4b6cedcf-0aef-4965-a049-26ce6af89a13)

[**Open in Figma**](https://www.figma.com/design/M5Njgc6SQJ3TPUccp5XHQx/UUI-Components?node-id=51207-296116&t=unvOSbKBLu8PwEIo-4)

**Comment by NatalliaAlieva** [comment]
Released in 5.8.0 ver.
