### ISSUE TITLE
Dropdown Menu, Table, Picker Input: Align components with design

### ISSUE THREAD

**Issue by DzmitryTrubchyk** [epam/UUI#2284]
## Improve UI part according to design

1. Important! Apply such change for pack of components: Dropdown Menu, Picker Input, Data Table

- Change hover color to surface-higher (F5F6FA for all light themes, 303240 for Loveship Dark) for every theme

**[Open in Figma](https://www.figma.com/design/M5Njgc6SQJ3TPUccp5XHQx/UUI-Components?node-id=51364-261962&t=wvj8llhTjwJXF7DM-1)**

Loveship, eg. Dropdown Menu:
As is:
![image](https://github.com/epam/UUI/assets/44213241/b257ae08-a335-4826-a3ba-94b068a89d9e)

As should be: 
![image](https://github.com/epam/UUI/assets/44213241/31a20dea-174b-49e8-8ecd-b115e3aa7b30)

2. Dropdown Menu:

- Place tick mark fixed right
- Change color to: Light themes — info-50, Loveship Dark — info-60 (make this change for picker Input too)
**[Open in Figma](https://www.figma.com/design/M5Njgc6SQJ3TPUccp5XHQx/UUI-Components?node-id=51364-261965&t=wvj8llhTjwJXF7DM-4)**

As is:
![image](https://github.com/epam/UUI/assets/44213241/a3aed1b0-d45f-4d2e-b88f-44285e53839b)

As should be:
![image](https://github.com/epam/UUI/assets/44213241/dcd86bb2-223d-4c5c-9486-c4e657195b95)

**Comment by NataliiaSkorobohatova** [comment]
**Dropdown Menu:**

- **Loveship Light, Promo, Electric theme.**
Change the divider color in the Dropdown Menu according the design - _divider-light_ `#E1E3EB`
<img width="710" alt="Screenshot 2024-06-03 at 13 29 56" src="https://github.com/epam/UUI/assets/166697099/d308385f-962a-4006-a180-1d31f81dad2c">


- **Loveship Dark theme.**
Change the divider color in the Dropdown Menu according the design - _divider-light_ `#383B4A`

<img width="711" alt="Screenshot 2024-06-03 at 13 30 31" src="https://github.com/epam/UUI/assets/166697099/f365294d-cc44-4672-a58a-4b122ab7c0f0">

**Comment by NatalliaAlieva** [comment]
Released in 5.8.0 ver.
