### ISSUE TITLE
[DataTable]: Incorrect first column width if showFoldAll setted

### ISSUE THREAD

**Issue by oleg96** [epam/UUI#2294]
## Prerequisites (optional)

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Steps to Reproduce

Open the sandbox with DataTable example [UUI Codesandbox](https://codesandbox.io/p/sandbox/uui-forked-5vw858).

## Actual result

If showFoldAll attribute setted, first column name is truncated

https://github.com/epam/UUI/assets/3322605/6fc5e1cf-c2f1-4711-8173-66e43c59cb85

## Expected result

If showFoldAll attribute setted, no truncation occurs for first column name

https://github.com/epam/UUI/assets/3322605/2dbab94c-881f-4cec-add6-293b16d4a32a

## Environment

* UUI version: 5.7.2
* Browser name: any
* Operating System: any

**Comment by AlekseyManetov** [comment]
It's expected behavior; the first column doesn't have enough space to fit the column caption. To resolve this, set a larger width for the first column, e.g., 150px. It's your responsibility as the component user to define appropriate column widths so that the table appears as expected.
