### ISSUE TITLE
Icon Button, Text area, Badge: Minor improvements of components and PE

### ISSUE THREAD

**Issue by DzmitryTrubchyk** [epam/UUI#2296]
## Icon button

1. Select "_action-account-fill_" icon by default (to make component visible at once)
2. Set _onClick_ property to _callback_ by default

## Text area

Set min height for component height, based on component size (eg. 24 text area size = 24 px min height)

## Badge

1. Count indicator property: delete variants with text, keep only numbers. Create 2 properties:

- 9
- 19
- 99+

As is:
![image](https://github.com/epam/UUI/assets/44213241/3e4f4a2d-7834-453d-8038-a188a630f16d)

As should be:
![image](https://github.com/epam/UUI/assets/44213241/1b3bbc98-be68-4de6-b710-b681f2175fdb)
![image](https://github.com/epam/UUI/assets/44213241/20dc796c-3f13-4858-be5a-113ed730fced)

2. Add 3 px to left side of left icon. [Open in Figma](https://www.figma.com/design/M5Njgc6SQJ3TPUccp5XHQx/UUI-Components?node-id=48724-148232&t=er6tcH5fsdIHFlQF-4)

**Comment by NatalliaAlieva** [comment]
Released in 5.8.0 ver.
