### ISSUE TITLE
UUI Site: Update preview and states for White color property

### ISSUE THREAD

**Issue by DzmitryTrubchyk** [epam/UUI#2304]
As is. White color preview invisible, looks a bit confusing in every state (inactive/active)
![image](https://github.com/epam/UUI/assets/44213241/2e261b72-cce6-4009-adb5-6449cc9bbd5d)

As should be. Add correct styles [Open in Figma](https://www.figma.com/design/tWlMuoqDg2kEFHGV42oi0u/UUI-Site?node-id=2581-1206&t=xWdXi14PNy4qyTqT-1)

![image](https://github.com/epam/UUI/assets/44213241/df1de675-ed4e-45bf-a5f6-fee61d4262f6)

**Comment by NatalliaAlieva** [comment]
Released in 5.8.0 ver.
