### ISSUE TITLE
[PickerInput]: remove picker footer while search is active

### ISSUE THREAD

**Issue by AlekseyManetov** [epam/UUI#2321]
## Now
Now when user type search he still able to use 'Select All' or 'Show only selected' actions, but we can't apply this actions separately for search results, we can do it only for the whole list.

<img width="489" alt="image" src="https://github.com/epam/UUI/assets/14283670/ff7cb1f1-19a2-492d-aad6-c3eba867c6bb">

## To Do
Let's remove picker footer with this actions, when some search value is typed

<img width="467" alt="image" src="https://github.com/epam/UUI/assets/14283670/9a715239-aa67-4cb4-a0b5-d248f6823f25">

**Comment by NatalliaAlieva** [comment]
Need to remove footer while searching for single select too

**Comment by NatalliaAlieva** [comment]
Released in 5.9.0 ver.
