### ISSUE TITLE
Text Inputs. Add inline mode

### ISSUE THREAD

**Issue by DzmitryTrubchyk** [epam/UUI#2341]
Add border for invalid state on frontend for all inputs:

- Text input
- Picker Input
- Text Area
- Search Input
- Date Picker
- Date Range Picker
- Time Picker
- Numeric Input

**[Design in Figma](https://www.figma.com/design/M5Njgc6SQJ3TPUccp5XHQx/UUI-Components?node-id=53344-179899&t=SX5HOor6OC2YDRcE-4)** 
![image](https://github.com/epam/UUI/assets/44213241/cc769e50-7ff2-42e3-a05d-be9367dde280)

**Comment by NatalliaAlieva** [comment]
Released in 5.8.2 ver.
