### ISSUE TITLE
[Header]: Incorrect tabs behavior when they are hidden in the three-line menu

### ISSUE THREAD

**Issue by shanaeva** [epam/UUI#2382]
## Prerequisites (optional)

**This section may be deleted**

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

## Description (optional)

**This section may be deleted**

https://jira.epam.com/jira/browse/EPMRVMA-36358

## Steps to Reproduce

Please provide a step-by-step explanation of how the bug can be reproduced. 
Include specific actions, input, or conditions that trigger the issue. Give a sample code if you can. You can use our [UUI Codesandbox](https://codesandbox.io/s/uui-bddgvi?file=/src/Example.tsx) template for it.

1. Step 1
2. Step 2
3. ...

## Actual result

What is the current behavior?

To provide more details please include screenshots, video, animated GIFs, or minimal code snippets where appropriate.

## Expected result

Please describe the behavior you are expecting.

## Environment

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* UUI version:
* Browser name:
* Operating System:

**Comment by NatalliaAlieva** [comment]
Hello @shanaeva ,

Could you please reproduce your bugs either on our website ([Main Menu component](https://uui.epam.com/documents?id=mainMenu&mode=doc&isSkin=null&category=components)) or in the [Codesandbox](https://codesandbox.io/s/wzndxr?file=/Example.tsx)?

**Comment by NatalliaAlieva** [comment]
> Hello @shanaeva ,
> 
> 
> 
> Could you please reproduce your bugs either on our website ([Main Menu component](https://uui.epam.com/documents?id=mainMenu&mode=doc&isSkin=null&category=components)) or in the [Codesandbox](https://codesandbox.io/s/wzndxr?file=/Example.tsx)?

Dear @shanaeva, 

As you have not provided additional data to reproduce the bug on our website or codesandbox, I am closing this ticket. Should you be able to reproduce the issue described in your ticket, please feel free to reopen this one with the relevant data attached.

Best regards.
