### ISSUE TITLE
[Pickers]: add possibility to get selection in renderFooter callback

### ISSUE THREAD

**Issue by AlekseyManetov** [epam/UUI#2395]
## To Do
Since in 5.8.0 version we've removed `view.getSelectedRows` callback, now it's impossible to get selected rows in `PickerInput` and `PickerModal` `renderFooter` prop callback. Let's add `getSelectedRows()` or just `selectedRows`(needs to decide which options is better) into `renderFooter` params, to be able to get them with new api.

**Comment by AlekseyManetov** [comment]
After discussion, we've decided that the primary use case is to get the picker selection, rather than an array of DataRowProps. Therefore, we will add the current selection into the renderFooter props.

**Comment by NatalliaAlieva** [comment]
Released in 5.8.2 ver.
