### ISSUE TITLE
[New component]: Vertical tabs

### ISSUE THREAD

**Issue by ilya-gorchakov-epam** [epam/UUI#24]
**Description**

**Describe the solution you'd like**

**Comment by NagibatorTraher** [comment]
[Display Spec](https://display.lab.epam.com/projects/5de8e67312ad7e0024d569d2/artboards/5e98509030064597981016bc/preview?menu=false)
[Figma Tabs](https://www.figma.com/file/HAkY2Uuarg2vSSyhZRgSZj/Components-UUI4?node-id=97%3A3276)
[Figma Hierarchy Tree](https://www.figma.com/file/HAkY2Uuarg2vSSyhZRgSZj/Components-UUI4?node-id=99%3A1305)

**Comment by dsv-sergey** [comment]
Implemented, wait for release
