### ISSUE TITLE
Picker Input: Use tags height inside input smaller

### ISSUE THREAD

**Issue by DzmitryTrubchyk** [epam/UUI#2406]
**[Open design for all sizes](https://www.figma.com/design/M5Njgc6SQJ3TPUccp5XHQx/UUI-Components?node-id=57275-51795&t=WtkjgpDEelJcceQk-11)**

![image](https://github.com/user-attachments/assets/91870b1b-f848-4d77-bd0d-92d79763765e)

**Comment by AlekseyManetov** [comment]
@DzmitryTrubchyk Could you add link to the figma with new variants in all sizes.

**Comment by DzmitryTrubchyk** [comment]
> @DzmitryTrubchyk Could you add link to the figma with new variants in all sizes.

Yes, added link to all sizes

**Comment by NatalliaAlieva** [comment]
Released in 5.9.0 ver.
