### ISSUE TITLE
File upload: Change error icon color to error

### ISSUE THREAD

**Issue by DzmitryTrubchyk** [epam/UUI#2410]
**Now**
![image](https://github.com/epam/UUI/assets/44213241/065b1461-7c5a-4983-94df-d2af643284c6)

**To Do**
![image](https://github.com/epam/UUI/assets/44213241/f34c33e0-f220-4bca-bc0b-d480a89a88f2)

For all themes, use error-70 variable for icon (same as for error text)
**[Figma link](https://www.figma.com/design/M5Njgc6SQJ3TPUccp5XHQx/UUI-Components?node-id=752-96051&t=dOzabcQkwCqX8ISb-11)**

**Comment by NatalliaAlieva** [comment]
Released in 5.9.0 ver.
