### ISSUE TITLE
[Radio Input, Checkbox]: improve visual part of components (Browser changes)

### ISSUE THREAD

**Issue by DzmitryTrubchyk** [epam/UUI#2412]
Update components Radio Input/Group, Checkbox regarding Browser changes (svg icons displays incorrectly, does not aligned visually)

**[Check Radio Button in Figma](https://www.figma.com/design/M5Njgc6SQJ3TPUccp5XHQx/UUI-Components?node-id=55634-90319&t=kxMgRYp3kqHq2CSm-11)**
**[Check Checkbox in Figma](https://www.figma.com/design/M5Njgc6SQJ3TPUccp5XHQx/UUI-Components?node-id=29-0&t=ILoghdV7ykKynhMT-0)**

**Comment by NatalliaAlieva** [comment]
This improvement is related to **[this](https://github.com/epam/UUI/issues/2383)** bug.

**Comment by NatalliaAlieva** [comment]
> This improvement is related to **[this](https://github.com/epam/UUI/issues/2383)** bug.

Still reproduced.

**Comment by NatalliaAlieva** [comment]
Released in 5.9.0 ver.
