### ISSUE TITLE
[DataTable]: click on resize marker prevents all further events from bubbling.

### ISSUE THREAD

**Issue by Kuznietsov** [epam/UUI#2444]
## Problem description

The event default behavior was prevented on the resize marker click to prevent text selection. It leads to tones of bugs, related to event bubbling, like blur calls, etc.
I guess the best way of solving the text selection problem is preventing it via CSS, not calling `e.preventDefault()`. 

https://github.com/user-attachments/assets/ee85a9e7-fd47-4bcd-8cb3-fcbd03113109

**Comment by NatalliaAlieva** [comment]
Released in 5.9.2 ver.
