### ISSUE TITLE
Landing: Responsive improvements

### ISSUE THREAD

**Issue by DzmitryTrubchyk** [epam/UUI#2456]
Update design for responsive

- Add theme selector
![image](https://github.com/user-attachments/assets/60dbcd6a-5011-407b-b3da-03f621282eb4)

- Slider hide into accordion in breakpoint "tbd"
![image](https://github.com/user-attachments/assets/53490a80-4820-4ba6-ad44-8e5957dcd43a)

- Finalize demo for breakpoints 
![image](https://github.com/user-attachments/assets/09707e08-8d77-4f49-8d43-494b9416246d)

![image](https://github.com/user-attachments/assets/0a4887f9-a90f-4fe6-a7e9-f3503c2b766c)
![image](https://github.com/user-attachments/assets/8e6a5995-0f3c-43eb-9454-533fa2ae14b1)

**Comment by DzmitryTrubchyk** [comment]
Design Review complete, found a couple of inconsistencies, wrote to @AlekseyManetov

**Comment by NatalliaAlieva** [comment]
Released in 5.9.1 version.
