### ISSUE TITLE
[Text]: Skin-specific and semantic color values in Loveship skin are different

### ISSUE THREAD

**Issue by vasilii-kovalev** [epam/UUI#2461]
Color pairs like `sky`-`info`-`primary`, `sun`-`warning`, `fire`-`critical` and others should have the same color values.

Actual result: colors in the picker look the same, the actual color of the text is not.

Fire color:
![Text with color=fire](https://github.com/user-attachments/assets/fec0766b-a344-4ec8-af78-df7b20e35e70)

Critical color:
![Text with color=critical](https://github.com/user-attachments/assets/0817520a-f079-4015-8f16-7fda2510c269)

**Comment by vasilii-kovalev** [comment]
Also, for some reason, `primary` color's value in the picker is blue, while the text is dark gray.
![image](https://github.com/user-attachments/assets/42bbb9db-2c35-4e4d-ada5-9d80060bc3a7)

**Comment by NatalliaAlieva** [comment]
Released in 5.9.2 ver.
