### ISSUE TITLE
[PickerInput]: wrong behaviour with non-removed data

### ISSUE THREAD

**Issue by MSt1ch** [epam/UUI#2468]
## Prerequisites (optional)

**This section may be deleted**

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Description (optional)

If you want to remove all items via backspace and you have some required non-removed data. You will see an error.

Please provide a clear and concise summary, highlighting the main issue or problem encountered.

Please use my sandbox link and try to delete all products via backspace. You will see an error.
https://codesandbox.io/p/sandbox/uui-forked-9gss4y?file=%2FExample.tsx%3A8%2C37

## Environment

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* UUI version: Latest
* Browser name: Chrome
* Operating System: MacOs

**Comment by MSt1ch** [comment]
https://github.com/user-attachments/assets/5259dc70-4a28-499c-ac09-59da06e0a983

**Comment by NatalliaAlieva** [comment]
Released in 5.9.2 ver.
