### ISSUE TITLE
Modal: Improve mobile view

### ISSUE THREAD

**Issue by DzmitryTrubchyk** [epam/UUI#2469]
## Now
Modal on mobile positions centered
![image](https://github.com/user-attachments/assets/f64ec41f-1a55-42b4-b382-2335e7fe3c60)

## To Do
Make modal sticky bottom in all box decisions (demo) and on examples. Add guidelines and examples. TBD
- Set bottom border radius to 0
- Fill buttons on width in footer
- Pin footer, in case a content a lot of content
![image](https://github.com/user-attachments/assets/7c188453-6bb6-4c2d-8f48-685091b6058b)
**[Open in Figma](https://www.figma.com/design/M5Njgc6SQJ3TPUccp5XHQx/UUI-Components?node-id=53514-11815&t=e4qCL8omMqhkrySo-11)**

**Comment by NatalliaAlieva** [comment]
Released in 5.10.0 ver.
