### ISSUE TITLE
Data Table: Columns config improvements

### ISSUE THREAD

**Issue by DzmitryTrubchyk** [epam/UUI#2479]
Requestor: **People**
**[Find design here](https://www.figma.com/design/cAd3iaIW4JxJapIVTrE96b/UUI-%E2%80%93-Tables-%26-Filters-(Demo-%26-Examples)?node-id=8316-23749&node-type=FRAME&t=Crq0ViBQD54ttt8p-11)**

Add:

1. Add ability to show all columns (not in one column) with: 

- A-Z sorting?
- Preset view? **Use Presets Panel**
Example:
![image](https://github.com/user-attachments/assets/f7c8c37b-9edd-4085-bbb6-f40b0ec07bcd)

2. Disabled item, change text color to normal (readability state)
3.  Increase modal width
4.  Select all, Clear all invisible, make it easier to find

5. Improve name display in case long titles
![image](https://github.com/user-attachments/assets/8eb338c4-3231-4bc2-8da9-c07d2eb6e880)
6. Remember item position, in case clicking chekbox

**Comment by NatalliaAlieva** [comment]
Released in 5.10.0 ver.
