### ISSUE TITLE
Drop shadows: Align core drop shadows with Figma

### ISSUE THREAD

**Issue by DzmitryTrubchyk** [epam/UUI#2488]
**[Open in Figma](https://www.figma.com/design/M5Njgc6SQJ3TPUccp5XHQx/UUI-Components?node-id=31224-25777&node-type=frame&t=m38iFuqRBX6EEWgI-11)**

### Loveship Light, Promo, Electric:

/* shadows/shadow-level-1 */
box-shadow: 0px 0px 3px rgba(29, 30, 38, 0.05), 0px 3px 6px rgba(29, 30, 38, 0.1);

/* shadows/shadow-level-2 */
box-shadow: 0px 6px 12px rgba(29, 30, 38, 0.05), 0px 3px 12px rgba(29, 30, 38, 0.1), 0px 0px 6px rgba(29, 30, 38, 0.05);

/* shadows/shadow-level-3 */
box-shadow: 0px 0px 10px rgba(29, 30, 38, 0.05), 0px 6px 36px rgba(29, 30, 38, 0.12), 0px 9px 15px rgba(29, 30, 38, 0.05);

### Loveship Dark

/* shadows/shadow-level-1 */
box-shadow: 0px 0px 4px rgba(0, 0, 0, 0.2), 0px 3px 6px rgba(0, 0, 0, 0.2);

/* shadows/shadow-level-2 */
box-shadow: 0px 1px 2px rgba(0, 0, 0, 0.2), 0px 4px 22px 3px rgba(0, 0, 0, 0.26);

/* shadows/shadow-level-3 */
box-shadow: 0px 1px 2px rgba(0, 0, 0, 0.2), 0px 3px 25px 3px rgba(0, 0, 0, 0.56);

**Comment by NatalliaAlieva** [comment]
Released in 5.10.0 ver.
