### ISSUE TITLE
Eduverse: Create theme in dev

### ISSUE THREAD

**Issue by DzmitryTrubchyk** [epam/UUI#2494]
The task is to create possibility to customize UUI based on Eduverse UUI library in Figma

**Comment by DzmitryTrubchyk** [comment]
Decision:
Because of absent Size variables in code & Figma there is no quick tech possibility to customize theme based on requirements. Awaiting additional review by stakeholders and Learn project?

**Comment by NatalliaAlieva** [comment]
Released in 5.11.0 ver.
