### ISSUE TITLE
[DataTable]: not pin column to the left by default if the isAlwaysVisible prop is true

### ISSUE THREAD

**Issue by AHrakovich** [epam/UUI#2527]
For now if specify the **isAlwaysVisible** property for DataTable column, the **fix** property for this column will be automatically defined as '**left**'. And there aren't ways to unpin this column.

So that, will be nice to **not define the fix property by default**, when **isAlwaysVisible** is set as **true**, and **allow user to pin it manually**. In any case we still have functionallity to specify fix property in the columns config.

Assumptions:
Does it make sense to separate isAlwaysVisible and 'locked' columns?
E.g. In case of isAlwaysVisible column I can't only hide it, pin/unpin/reordering are still available. In case of 'locked' I can't do anything, it is always on the same place, etc.

**Comment by NatalliaAlieva** [comment]
Released in 5.10.0 ver.
