### ISSUE TITLE
Size tokens des <> dev: Tag

### ISSUE THREAD

**Issue by DzmitryTrubchyk** [epam/UUI#2534]
### Changes

**42 size**
- padding-h changes from 6 to 9
- gap-h changed from 0 to 3
- caption-padding changed from 6 to 3

**36 size**
- gap-h changed from 0 to 3

**30 size**
- gap-h changed from 0 to 3

**24 size**
- gap-h changed from 0 to 3

**18 size**
- gap-h changed from 0 to 3
- caption-padding changed from 3 to 0

**Comment by DzmitryTrubchyk** [comment]
18 size, caption-padding should be 0

**Comment by NatalliaAlieva** [comment]
Released in 5.11.0 ver.
