### ISSUE TITLE
Size tokens des <> dev: Horizontal Tab Button

### ISSUE THREAD

**Issue by DzmitryTrubchyk** [epam/UUI#2535]
### Changes
**60 size**
- gap-h changed from 0 to 3
- right padding changed from 3 to 0 for counter and right icon
- caption-padding-v set to 0

**48 size**
- gap-h changed from 0 to 3
- caption-padding-v set to 0
- right padding changed from 3 to 0 for counter and right icon

**36 size**
- gap-h changed from 0 to 3
- caption-padding-v set to 0
- right padding changed from 3 to 0 for counter and right icon

**Comment by DzmitryTrubchyk** [comment]
All sizes, caption should be upper
![image](https://github.com/user-attachments/assets/da5eb447-6cf6-4842-b6cc-98854730dd0b)

**Comment by NatalliaAlieva** [comment]
Released in 5.11.0 ver.
