### ISSUE TITLE
[PickerInput] disableClear prop is not fully working

### ISSUE THREAD

**Issue by siarheiyelin** [epam/UUI#2558]
## Notes
It worked fine on v.5.7.3     

## Steps to Reproduce
1. Open property explorer for the PickerInput component. [Link to prop explorer](https://uui.epam.com/documents?category=components&id=pickerInput&mode=propsEditor&isSkin=true&theme=loveship)
2. Select some item from the picker dropdown
3. Select "disableClear=true"
4. Open picker dropdown

## Actual result
"CLEAR" button is rendered at the bottom of the picker dropdown
![image](https://github.com/user-attachments/assets/26fb14ba-de77-48f2-a2e6-3e73ba0b2e3c)

## Expected result
"CLEAR" button is not rendered (like it was on v 5.7.3)
![image](https://github.com/user-attachments/assets/34f4b105-3934-4f4e-9a3b-ad985892997e)

## Environment
* UUI version: 5.10.1
* Browser name: Chrome

**Comment by AHrakovich** [comment]
the same issue:
![image](https://github.com/user-attachments/assets/44018daf-22a2-4f2e-bd2c-71afc098a0d5)
sandbox link: https://codesandbox.io/p/sandbox/uui-forked-wj49hf

**Comment by NatalliaAlieva** [comment]
Released in 5.10.2 ver.
