### ISSUE TITLE
[Form]: flexible beforeLeave behavior

### ISSUE THREAD

**Issue by JuliaMV** [epam/UUI#258]
**Description**
I have Form component with beforeLeave modal and  redirect  to page **A** in onSuccess callback.

I) If user saves form on page **B** by clicking 'save' button the following actions happen:
1 - onSave calback is invoked
2 - onSuccess callback is invoked and added new url  for page **A** to browser history
3 - user sees page **A**.
The browser history for this case is **[B, A]**.

II) If user tries to leave page **B** with unsaved form and go to page **C** the following actions happen:
1 - showing beforeLeave modal 
2 - user clicks 'save'
3 - onSave calback is invoked
4 - onSuccess callback is invoked and URL  for page **A** is added  to browser history
5 - user goes to page **C**
The browser history is **[B, A, C]**.

**Describe the solution you'd like**
I would like to have ability do not add redundant redirects.  Expected browser history for second case is **[B, C]**.

**Comment by jonybekov** [comment]
I'm taking this
