### ISSUE TITLE
[Component name]: Modal

### ISSUE THREAD

**Issue by izy-13** [epam/UUI#2587]
## Description

On resolutions < 721px modal windows are pinned to the bottom edge of the screen

## Steps to Reproduce

1. open https://uui.epam.com/documents?id=modals&mode=doc&category=components
2. in any convenient way limit the screen width below 721 pixels
3. open any example modal

## Actual result

modal windows are pinned to the bottom edge of the screen

## Expected result

modal windows should be positioned in the center of the screen

## Environment

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* UUI version: 5.10.2
* Browser name: Google Chrome
* Operating System: Windows 11 64-bit

**Comment by AlekseyManetov** [comment]
This is expected behavior according to the following design improvements for mobile modal view - https://github.com/epam/UUI/issues/2469
