### ISSUE TITLE
[Error Pages]: Add possibility to provide support link

### ISSUE THREAD

**Issue by AlekseyManetov** [epam/UUI#2588]
## To Do

- Add possibility for UUI clients to embed additional message with link to the support portal into UUI ErrorPage component.
  <img width="826" alt="image" src="https://github.com/user-attachments/assets/f3eebf26-b649-4091-932c-74f1513446c8">
  Design: https://www.figma.com/design/l2WYMv33mQjb3wBiskimvK/EPM-STTS-2024?node-id=1796-11933&node-type=section&t=HpOpwwcuJTLj99dv-0
- Add mention to the change log with strong recommendation for EPAM apps to enable it and provide instructions.

## Describe the solution you'd like (optional)
Let's add additional field for the i18n object, that projects can set text message with support link. Make it empty by default, to not break external clients. Each project should add this by yourself:
```
i18n.errorHandler.supportLink = `You can track the service availability at <a href='https://status.epam.com/?utm_source=${window.location.host}&utm_medium=ErrorPage&utm_campaign=StatusAquisitionTracking'>status.epam.com'</a>
```

**Comment by NatalliaAlieva** [comment]
Released in 5.12.0 ver.
