### ISSUE TITLE
[Clickable]: `clickAnalyticsEvent` not being sent when `href` property used

### ISSUE THREAD

**Issue by cpoftea** [epam/UUI#2611]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Description

`clickAnalyticsEvent` not being sent when `href` property used at components, that uses inner `Clickable` component: `Tag`, `Badge`, `Anchor`, `TabButton`, `MainMenuButton`, `Button`, `LinkButton`, `IconButton`.

## Steps to Reproduce

1. Open [Sandbox](https://codesandbox.io/p/sandbox/clickanalyticsevent-with-href-y6vkq3) with simple analytics listener that will show notification when event being sent.
2. Check that mode `href` enabled
3. Click any clickable component 

## Actual result

No analytic notifications appeared

## Expected result

Analytic notifications appeared

## Additional info

Sandbox has 3 modes:
* when `href` property used
* when `link` property used
* when `onClick` property used

You can switch mode to `link` and `onClick` and repeat the same steps: analytic notifications will appear.

## Environment

* UUI version: 5.10.2
* Browser name: FF 132.0.1
* Operating System: macOS 15.0.1

**Comment by NatalliaAlieva** [comment]
Released in 5.11.0 ver.
