### ISSUE TITLE
Multiswitch: Add example or property with "icon" + "caption" and "icon" only

### ISSUE THREAD

**Issue by DzmitryTrubchyk** [epam/UUI#2616]
**[Icon only example](https://www.figma.com/design/M5Njgc6SQJ3TPUccp5XHQx/UUI-Components?node-id=64039-63869&node-type=frame&t=TBsACnpwEFtEQ9It-11)**
![image](https://github.com/user-attachments/assets/f93dfd53-877e-443a-882c-96cc475f170d)

**[Icon + Label example](https://www.figma.com/design/M5Njgc6SQJ3TPUccp5XHQx/UUI-Components?node-id=64039-63869&node-type=frame&t=TBsACnpwEFtEQ9It-11)**
![image](https://github.com/user-attachments/assets/f660d425-a13e-4733-8e52-b0c5c6ecdb51)

**Comment by NatalliaAlieva** [comment]
Released in 5.12.0 ver.
