### ISSUE TITLE
Add semantic colors for components with `background` property in Loveship skin

### ISSUE THREAD

**Issue by vasilii-kovalev** [epam/UUI#2619]
## Description

Since there are semantic colors for components with `color` property, like `Text`, `Button`, `Alert`, etc. in Loveship skin, it also makes sense to add them to components with `background` property, like `FlexRow` or `Panel`.

**Comment by AlekseyManetov** [comment]
Currently, we don’t have semantic colors for backgrounds, except for the 'surface' color present in the Panel component. If you mean primary, accent, success, warning, and similar colors, these are specifically used within components according to their designs, and we don’t have a global approach for applying them to panels.

I believe that colored panels shouldn’t be a responsibility of UUI, as any solution we provide would be anyway limited and wouldn’t cover all possible use cases. It's something like a creative part of a work, that we leave for the project and don't want to limit them. Moreover it’s easy add background by your own by passing a background color via the `cx` prop. 

What can be easily done on project side - should be done by project, UUI don't have aim to take such parts inside. We are focusing on more complex parts that require significant effort from the Frontend and Design teams.

**Comment by vasilii-kovalev** [comment]
But can it be done for already existing colors?

* `Panel`
  * `night50`
* `FlexRow`
  * `night50`
  * `night100`

In other skins, there is `surface-main` for `white`. Replacing `night*` variants would make changing skins easier.

**Comment by AlekseyManetov** [comment]
> But can it be done for already existing colors?

Unfortunately no, because we don't have semantic system for the panel backgrounds and we even don't have this skin options in our designs. We leave this colors in skins to not make a breaking changes for current skin users, but in UUI we adhere another approach where we are cutting down the options of skins in favor of semantics. 

I would recommend move this from props to the css, if you are moving from skin to UUI.
