### ISSUE TITLE
Size tokens des <> dev: Alert

### ISSUE THREAD

**Issue by DzmitryTrubchyk** [epam/UUI#2620]
**[Open in Figma](https://www.figma.com/design/M5Njgc6SQJ3TPUccp5XHQx/UUI-Components?node-id=15770-362256&node-type=frame&t=LOOaLZAjwi6ixlgN-11)**
**Changes**

36 size

- Children Long: apply common padding-v 6 (changed for bottom padding-v from 3 to 6)
![image](https://github.com/user-attachments/assets/19b180d8-2e59-4e66-a4a2-f8fd02439e4c)

- All children types: caption-gap-h change to 9
As is
![image](https://github.com/user-attachments/assets/3a6696fc-98b3-4ca4-9c5e-e09a8babdd9a)

As should be
![image](https://github.com/user-attachments/assets/96a33c77-795e-46a1-9b49-5420a65444fe)

**Comment by NatalliaAlieva** [comment]
Point 1 hasn't been implemented, as its implementation would cause breaking changes. This is because the Alert component is built on paddings that belong to the Text component.
