### ISSUE TITLE
Build and test for Linux/ARM64

### ISSUE THREAD

**Issue by odidev** [epam/UUI#2625]
## Description  

For aarch64 platform, I have built "UUI" from source.  

## Steps   

Following "STEPS (https://uui.epam.com/documents?id=gettingStarted)" were used for building and installing UUI.  
```
wget https://github.com/epam/UUI/archive/refs/tags/v5.10.1.tar.gz 
tar xvf v5.10.1.tar.gz 
cd UUI-5.10.1 
npm i @epam/uui 
```
## Outcome  

To validate that the build was successful we ran version Check. The version info returned matched the expected value(s). 

`npm list epam/uui`

All this information was also added to Software Ecosystem Dashboard for Arm (https://www.arm.com/developer-hub/ecosystem-dashboard/).

**Comment by AlekseyManetov** [comment]
Sorry, but I didn't get what is this issue about? Could you please provide more details and what is expected from our team?

**Comment by AlekseyManetov** [comment]
Closed since lack of details. Feel free to reopen it in feature.
