### ISSUE TITLE
[RTE]: Image caption not visible in initial readonly mode

### ISSUE THREAD

**Issue by cpoftea** [epam/UUI#2650]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Description

Image caption not visible at first render with readonly mode.

<img width="630" alt="Screenshot 2024-11-21 at 12 28 36" src="https://github.com/user-attachments/assets/17a412cc-55d0-461f-b70e-24b81b57c2a6"> 

## Steps to Reproduce

1. Open [Codesandbox](https://codesandbox.io/p/sandbox/rte-image-caption-not-visible-initially-tl8r78) example
2. Check that image contains caption at initial value
3. Check caption visibility at rendered content

## Actual result

No caption visible

## Expected result

Caption visible

## Additional info

Re-enable readonly mode with switch to make caption visible.

## Environment

* UUI version: 5.11.0
* Browser name: FF 132.0.2
* Operating System: macOS 15.1

**Comment by NatalliaAlieva** [comment]
Hi @cpoftea, 
could you please make the sandbox example available to the public?
Thank you.

**Comment by cpoftea** [comment]
@NatalliaAlieva done

**Comment by NatalliaAlieva** [comment]
Released in 5.12.0 ver.
