### ISSUE TITLE
[RTE]: App crashes when deleting sole table row

### ISSUE THREAD

**Issue by cpoftea** [epam/UUI#2673]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Description

App crashes when deleting sole table row

https://github.com/user-attachments/assets/e773e622-e22a-4e7a-81b3-08ed91027e4e

## Steps to Reproduce

1. Open [Codesandbox](https://codesandbox.io/p/sandbox/v4lx58) example
2. Put cursor inside table
3. Click delete row button at table toolbar

## Actual result

App crashes

## Expected result

App persistent and row not being removed the same as table plugin does not remove sole column.

## Environment

* UUI version: 5.11.0
* Browser name: FF 133.0
* Operating System: macOS 15.1

**Comment by NatalliaAlieva** [comment]
Released in 5.12.0 ver.
