### ISSUE TITLE
[RTE]: Inserting dark text to editor  in dark mode

### ISSUE THREAD

**Issue by RealOneReal** [epam/UUI#2682]
Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Description (optional)
I has a possibility insert dark text to editor in dark mode.

![image](https://github.com/user-attachments/assets/3ef8a57f-6da6-44a1-8ec9-26174a92c735)

May be you can write helper in RTE, that can colorize text considering the background color.

**Comment by RealOneReal** [comment]
Thanx, i use a helper that convert too dark colors to default related with theme.
https://github.com/epam/UUI/issues/908 
can`t resolve our problem because we have a lot of content, that user inserted when we didn`t have a dark theme.

**Comment by AlekseyManetov** [comment]
> because we have a lot of content, that user inserted when we didnt have a dark theme

In this case, I don't think we can offer some an out-of-the-box solution, as what works for you might not work for other clients, especially considering the variety of themes.

I believe a migration helper on your side is a good way to address this issue.

However, you could also consider my suggestion of adding functionality that allows to determine which attributes to retain during copying and which to remove. If this would help you, we can implement it—just let us know.
