### ISSUE TITLE
[DatePicker/FilterDatePicker]: Add ability to choose default view(Months or Years)

### ISSUE THREAD

**Issue by SakhnoI** [epam/UUI#2711]
## Now
Currently, it is not possible to select the default view for the calendar or remove unnecessary views. For instance, I would like to choose only the month view by default.
![image](https://github.com/user-attachments/assets/6c197f44-3325-4ae8-b66c-6bca9d2117b2)

## To Do
It would be great to have the ability to specify the desired order and select the views that are needed.
![image](https://github.com/user-attachments/assets/28de2520-1374-4832-98be-987523d0ef98)

## Describe the solution you'd like (optional)
A possible approach could be to pass a view prop, like 'view': ['month', 'year']. By default, it could be ['day', 'month', 'year'].

**Comment by AlekseyManetov** [comment]
I don’t think we should add this functionality to the DatePicker component. It’s more complex than simply displaying one of several views. We would also need to change the internal DatePicker logic to handle different date formats (e.g., YYYY-MM or YYYY). Currently, all the DatePicker code assumes the use of a full date format (YYYY-MM-DD), and adding support for different formats would introduce unnecessary complexity to an already complex component.

I believe a better solution would be to create separate MonthPicker and YearPicker components. However, these are not straightforward to implement, and we currently don’t see a high demand for them.

As a workaround—and often a better UX solution—we recommend replacing such DatePickers with two separate dropdowns for years and months, like this:
<img width="753" alt="image" src="https://github.com/user-attachments/assets/e890f696-617b-42a8-b7ff-1b173a4d6535" />

I think we should add this example to our DatePicker documentation. I’ll create a corresponding issue for it.
