### ISSUE TITLE
DataTable and VirtualList - scroll top on filter change

### ISSUE THREAD

**Issue by jakobz** [epam/UUI#279]
**Description**

DataTable, and other components which use VirtualList, needs to scroll to top in case when filter or search changes.

I'm not sure that it should be the only behavior, but defenitelly it should be default one.

**Describe the solution you'd like**

This to be discussed. However:
- I'd like to have a public API on the VirtualList to control scroll directly (ref-based approach might be ok in this case)
- I'd prefer DataTable to do this via some state manipulation. Resetting topIndex to 0 wouldn't work, as it also happens when user scrolls up, but not yet reach top.
- DataTableHeader and it's in-header filters should trigger this automatically
- We need to have a good recipe for cases when users compose tables at their side (e.g. uses DataSources and VirtualList directly).

**Comment by AlekseyManetov** [comment]
implemented in #518
