### ISSUE TITLE
[DropdownMenuButton] Problem with caption font

### ISSUE THREAD

**Issue by anna-kiranova** [epam/UUI#289]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Expected Behavior

Caption font before version update:
![image](https://user-images.githubusercontent.com/35148952/138457646-00a5127d-2f0c-41aa-9dfe-0d985e4c91f1.png)

# Current Behavior

Current view:
![image](https://user-images.githubusercontent.com/35148952/138457755-d992f6c4-4f8a-47dc-a687-6cd52159bf37.png)

## Steps to Reproduce

<DropdownMenuButton caption="Report expense" onClick={ () => ... } />

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* UUI version: 4.2.7
* Browser name: any
* Operating System: any

**Comment by okrypets** [comment]
Hello. Please write what version it was before updating to 4.2.7

**Comment by anna-kiranova** [comment]
Hello, @okrypets the previous version was 4.2.5
