### ISSUE TITLE
Empty picker input if Language level prop is choosen

### ISSUE THREAD

**Issue by ilya-gorchakov-epam** [epam/UUI#296]
<img width="903" alt="Screen Shot 2021-10-29 at 16 09 33" src="https://user-images.githubusercontent.com/83595891/139440795-e44045b5-acac-4067-8fa5-8eb35ff3064e.png">

https://uui.epam.com/documents?category=components&id=pickerInput&mode=propsEditor&skin=UUI4_promo

**Comment by rayetzki** [comment]
@ilya-gorchakov-epam You need to set getName to i => i.level for it to work
![image](https://user-images.githubusercontent.com/13886379/145782874-1dc58f72-7a22-45bc-a2c4-6fcbe7d17cd2.png)
