### ISSUE TITLE
Customizable Timeline components

### ISSUE THREAD

**Issue by anna-malysheva-epam** [epam/UUI#297]
CST team is using UUI Timeline components in our project and we were discussing the possibility of make custom timeline, scale and background of the existing Timeline with the UUI team.

**Describe the solution you'd like**
Background — remove scale
Timeline scale — make it customizable: add first letters of the day to the day number, add detailed description of the day (31 August 2021, Friday, 35 week), etc.
Timeline — change elements, work with the color, change the color of the current day, etc.

**Comment by AlekseyManetov** [comment]
I'll close this issue, because timeline component is deprecated and not supported. Contact me, if you still need this changes.
