### ISSUE TITLE
rawProps for other elements

### ISSUE THREAD

**Issue by nanbratan** [epam/UUI#298]
**Description**
In case we use auto-tests for testing our app, we need some selectors on DOM elements to find them. UUI provide **rawProps** for most elements, but not for all.

There are elements which we need to test:

1. PickerInput - need **rawProps** for _Input_ and for _Dropdown_, also it would be nice to have an id on PickerInputs's Dropdown elements.
2. RangeDatePicker - need **rawProps** for both Inputs, I mean _From_ and _To_
3. ModalHeader
4. DropSpot

**Update**

5. Notifications - needs rawProps for notification card and for action buttons on notification card

**Comment by anna-kiranova** [comment]
Please, add rawProps to DatePicker also
