### ISSUE TITLE
Get rid of legacy React APIs

### ISSUE THREAD

**Issue by dsv-sergey** [epam/UUI#30]
**Legacy code**
- [x] legacy lifecycle methods
- [x] legacy context API #44
- [ ] findDOMNode
- [x] createFactory methods - remove with deprecation warning in changelog.md

**Need update**
- **Rework some components to functional or to hooks**
  - [ ] Form Component #43
  - [ ] IEditableDebouncer
  - [ ] RichTextEditor
  - [ ] Stateful
  - [x] DocumentsPage, SandboxPage

- **Third party packages**:
  - [x] react-measure
  - [x] react-transition-group
  - [x] draft-js

**Comment by JuliaMV** [comment]
to update react-measure https://github.com/epam/UUI/pull/42

**Comment by dsv-sergey** [comment]
to update react-transition-group #48

**Comment by dsv-sergey** [comment]
reworked DocumentsPage, SandboxPage commit https://github.com/epam/UUI/commit/a848f729e035cd42f4a8a3ed422355d0b5b0f3a1

**Comment by dsv-sergey** [comment]
to update draft-js #50

**Comment by dsv-sergey** [comment]
removed deprecated createFactory method

**Comment by dsv-sergey** [comment]
this helps fix warning findDOMNode - https://github.com/reactjs/react-transition-group/issues/675#issuecomment-946376404
