### ISSUE TITLE
[RTE] Add blue color for text editing

### ISSUE THREAD

**Issue by martynov-dm** [epam/UUI#304]
**Description**

Add blue color
![image](https://user-images.githubusercontent.com/71134999/140707481-e971caf1-b663-4bbd-b0e4-55810bb7dab7.png)

**Comment by AlekseyManetov** [comment]
Hi, we don't have blue color in our specifications for RTE now. We need to add this for our design specs first, if we decide that we need this color for RTE. I think it may conflict with link color and can confused the user. 
@martynov-dm it will be good if you can share use-cases for us.
@Yaroslav-Zinkov could you please review this change from design side?
