### ISSUE TITLE
Problem with Form save in 4.3.0

### ISSUE THREAD

**Issue by Vicktoryan** [epam/UUI#305]
value:
{
  item: 'test'
}

1. set new value
formProps.lens.prop("item").set('change value');
2. formProps.save();

result:
method onSave={(newValue) => {
----- newValue has last value
   newValue === {
      item: 'test'
   }
}}

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* UUI version: 4.3.0
* Browser name:
* Operating System:

**Comment by rayetzki** [comment]
Hi, @Vicktoryan 
Can you please provide a sandbox to display the problem

**Comment by AlekseyManetov** [comment]
@rayetzki I have small call with @Vicktoryan and understand the problem, so it's not needed to create the sandbox. Contact me and i provide more details.

**Comment by AlekseyManetov** [comment]
will be fixed in next version
