### ISSUE TITLE
Promo: BurgerMenu light theme

### ISSUE THREAD

**Issue by JuliaMV** [epam/UUI#316]
Is it possible to add support light theme for BurgerMenu? As I see there isn't ability to change BurgerButton font and icon color from light to dark.

**Comment by AlekseyManetov** [comment]
HI, now we are working on new themization approach for UUI. We plan to make separate skin which can apply any them on it, and in the feature make current loveship and promo skins based on this skin, so it will be possible to make loveship-white and loveship-dark thems.
For now, we don't plan to use our current loveship approach, where you set theme via components props, so if you need white BurgerButton now you can custom it via cx prop.
