### ISSUE TITLE
Promo: BurgerButton issues

### ISSUE THREAD

**Issue by JuliaMV** [epam/UUI#317]
# Expected Behavior

1. Active link style doesn't applied to icon.
2. Space for icon is hard coded and applied even icon not passed.

# Current Behavior

![2021-11-24_09h58_04](https://user-images.githubusercontent.com/37875890/143191131-baa3732e-ac2b-4e93-b591-82263b29ed3f.png)
![2021-11-24_09h59_16](https://user-images.githubusercontent.com/37875890/143191139-d3ba4dfc-80f0-4343-a5e1-218c47c18919.png)

## Context

* UUI version: 4.3.0
* Browser name: any
* Operating System: any

**Comment by JuliaMV** [comment]
@AlekseyManetov  what do you think about the first point in the issue? Active color doesn't applied to icon.

**Comment by okrypets** [comment]
@JuliaMV Hi. There is an example from uui.epam.com
![image](https://user-images.githubusercontent.com/54622440/145353042-25a405b8-014c-4b9b-9e14-8c2feb9924fe.png)
In the current version, color is applied to the icon.

**Comment by okrypets** [comment]
@JuliaMV Sorry.
I recheck with isLinkActive={true} - there is a bug. I'll reopen the issue and fix it.
