### ISSUE TITLE
Promo: PickerInput custom renderToggler

### ISSUE THREAD

**Issue by MSt1ch** [epam/UUI#328]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ x ] I am running the latest version
- [ x ] I checked the documentation and found no answer
- [ x ] I checked to make sure that this issue has not already been filed

# Expected Behavior

If we are enabled "disableClear" prop, the close button should be hidden. The prop "disableClear" works correctly only with the default "renderToggler" prop. 

# Current Behavior

https://user-images.githubusercontent.com/17798957/144610837-36e7030c-d1c9-43b2-ab90-414c7d6cb011.mov

* UUI version: Latest
* Browser name: all
* Operating System: all

**Comment by AnLeonovich** [comment]
Loveship has the same issue.
![image](https://user-images.githubusercontent.com/25349873/146763389-e20f44f7-25f5-4036-b331-1fd2a7edb785.png)

**Comment by okrypets** [comment]
``Hi. Here in `PropertyExplorer` tab, there is just an example of passing some custom Toggler. 
`renderToggler` - is a prop for your custom Toggler. 
You can create a component for Toggler that you want and you should control the visibility of the cross icon inside this custom Toggler yourself.

For example, if you want to use Button as Toggler - then create a custom component like this: 
```
const TogglerCustomButton = (props: PickerTogglerProps<any>) => <Button
                    { ...props }
                    caption={ props.selection.map(s => s.value.name).join(', ') }
              >
                          <IconContainer icon={props.isOpen ? arrowIconUp : arrowIconDown } />
                          {props.disableClear && <IconContainer icon={crossIcon} />}
              </Button>

```
