### ISSUE TITLE
User is not able to highlight for copying a value in the field with dictionary

### ISSUE THREAD

**Issue by InaKazlovich** [epam/UUI#329]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

# Expected Behavior

The value that is selected in the field should be highlighted to copy it
# Current Behavior

The value that is selected in the field is not highlighted so user is not able to copy it for further usage

## Steps to Reproduce

Please provide detailed steps for reproducing the issue. Provide screenshots or minimal code snippet where appropriate.

1. Select a value in the  filed with dictionary (Setting row options https://uui.epam.com/documents?category=components&id=pickerInput&mode=doc&skin=UUI4_promo)
2. Highlight the value

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* UUI version: 4.3.0
* Browser name: Google Chrome
* Operating System: Win1
![2021-12-06_12h42_19](https://user-images.githubusercontent.com/95617063/144824853-752924fa-84a2-462f-9124-e702c1bd346b.gif)
0

**Comment by NatalliaAlieva** [comment]
Released in version 4.9.0
