### ISSUE TITLE
[Promo]: FileCard component issues and improves

### ISSUE THREAD

**Issue by JuliaMV** [epam/UUI#334]
Currently `<FileCard  />` component works correctly only with  `progress: 0...100 ` . If this info doesn't passed the component has gray color with incorrect information about size. 

![2021-12-08_19h10_31](https://user-images.githubusercontent.com/37875890/145242696-c20a82d7-ffbe-4b98-98e8-c7e46f51672f.png)

 Furthermore for correct work this component information about file name and file size are required, but interface of file prop is binded with interface FileUploadResponse with unnecessary (for FileCard component) required and optional fields.  
Other improves:
- props onClick applied only to cross icon but this icon appears even if onClick doesn't passed.
- wording ' of ' would be better move to i18n config.
- on the design mockups we have information about extension on the second line near the file size.

![2021-12-08_19h08_39](https://user-images.githubusercontent.com/37875890/145242705-30cafa30-4f4b-43ff-abf3-bbcb8c2983c2.png)

**Comment by AlekseyManetov** [comment]
1. If `progress` filed is't passed we need to disable loading state.
2. Remove file extension from file name, because we have it in the separate line. Also add possibility to get extension from `file.extention`
