### ISSUE TITLE
Buttons width is not correct

### ISSUE THREAD

**Issue by und3rtak3rz** [epam/UUI#339]
When I setup button (36) with icon (18) it has width less than it's height.

**Comment by rayetzki** [comment]
@und3rtak3rz Please provide a screenshot or a video to illustrate this.

**Comment by AlekseyManetov** [comment]
Hi, we can't make it, because in such case we wiil not be able to implement `ControlGroup` button like in this example - https://uui.epam.com/documents?category=components&id=controlGroup&mode=doc&skin=UUI4_promo#basic
