### ISSUE TITLE
ScrollBar types inconsistency

### ISSUE THREAD

**Issue by gegorov** [epam/UUI#340]
# Expected Behavior

ScrollbarProps that is exported from @uui/components should match what ScrollBars from @uui/loveship is expecting 

# Current Behavior

There is an error when you create a object that implements ScrollbarProps interface and try to spread it as props into ScrollBars component.
```
Types of property 'ref' are incompatible.
    Type 'LegacyRef<Scrollbars> | undefined' is not assignable to type 'Ref<any> | undefined'.
      Type 'string' is not assignable to type 'Ref<any> | undefined'.
```

## Steps to Reproduce

Please provide detailed steps for reproducing the issue. Provide screenshots or minimal code snippet where appropriate.

1. import ScrollbarProps and ScrollBars
```
import { ScrollBars } from '@epam/loveship';
import { ScrollbarProps } from '@epam/uui-components';
```
2. create a const 
```
const scrollBarProps: ScrollbarProps  = {
autoHeight: 100,
}
```
3. try to spread scrollBarProps as props into ScrollBar, you'll get an error

```
<ScrollBars {...scrollProps}>
      {children}
    </ScrollBars>
```

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* UUI version: 4.4
* Browser name: 96.0.4664.55
* Operating System: Macos

**Comment by rayetzki** [comment]
@gegorov The fix will land in the next relase
