### ISSUE TITLE
uui table - bottom line

### ISSUE THREAD

**Issue by Spinnen87** [epam/UUI#346]
# Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Expected Behavior
There isn't a line at the bottom of the table

# Current Behavior
There is a line at the bottom of the table

## Steps to Reproduce

1.  We use table  and use prop `renderRow` ->  `renderRow={rowProps => <DataTableRow {...rowProps} borderBottom={rowProps.isLastChild ? 'none' : 'night300'} />`
2. when we use zoom (CTRL + '+') sometimes we can see a line at the bottom of the table. If you are using a virtual machine, sometimes you can see this line without magnification
3. At first glance it looks like it is an element with a class  `.uui-table-scroll-bar`
4. We didn't have horizontal scrolling in the table

on the video I reproduce it on the site uui.epam.com
[video to reproduce ](https://drive.google.com/file/d/1wTW5b4tqC_OIpN8glnEMvyX59xJodnvb/view?usp=sharing)

## Context
* UUI version:  4.4.0
* Browser name: Google Chrome Version 96.0.4664.93
* Operating System: Windows 10

**Comment by rayetzki** [comment]
A non-issue since 4.5.0 version. Consider upgrading the library
