### ISSUE TITLE
DropSpot component MacOS mailfunction

### ISSUE THREAD

**Issue by AliaksandrZahorski** [epam/UUI#357]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Expected Behavior

User can upload file

# Current Behavior

Chrome browser freeze the window while user choose the file

## Steps to Reproduce

Click to link "Open file", choose any file.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* UUI version: @epam/loveship 4.2.1
* Browser name: Google Chrome Version 96.0.4664.110 (Official Build) (x86_64)
* Operating System: macOs Big Sur 11.6, macOs Monterey 12.1

https://user-images.githubusercontent.com/26260228/147227203-20815eaf-e8f6-4f4c-9834-ee03b19d2131.mp4

**Comment by AlekseyManetov** [comment]
Can't reproduce it on the latest version of MacOS. Please reopen it, if you still have such issue.
