### ISSUE TITLE
Replace findDOMNode with ref. React Strict Mode

### ISSUE THREAD

**Issue by alex9pro** [epam/UUI#359]
Hi, UUI Team!

**Description**

I'd like use React Strict mode to have possibility find potential problems in application. But I have many warnings about using findDOMNode in some components like Dropdown, Table, etc. It is tricky to use console with bunch of warnings.

**Describe the solution you'd like**

Please consider possibility to replace findDOMNode with ref.

Thanks 😊

**Comment by fvrrrn** [comment]
+1 for this
Also check out the [guide](https://medium.com/trabe/getting-rid-of-finddomnode-method-in-your-react-application-a0d7093b2660) given
