### ISSUE TITLE
Demo table scrolling is laggy

### ISSUE THREAD

**Issue by apalchys** [epam/UUI#370]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Expected Behavior

https://uui.epam.com/demo?filter=undefined&id=table
Table scrolling is smooth

# Current Behavior

https://uui.epam.com/demo?filter=undefined&id=table
When I scroll the table, I see noticeable frame drop/table freeze especially when new set of records is lazy-loaded.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue. Provide screenshots or minimal code snippet where appropriate.

1. Open https://uui.epam.com/demo?filter=undefined&id=table
2. Start scrolling table 

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Browser name: Chrome Version 97.0.4692.71 (Official Build) (x86_64)
* Operating System: Mac OS (Macbook Pro 16, 2,4 GHz 8-Core Intel Core i9, 32GB RAM)

**Comment by AlekseyManetov** [comment]
HI, could you please attach the video with `noticeable frame drop/table freeze`?

**Comment by apalchys** [comment]
Please see video and devtools ptofile file here:
https://www.dropbox.com/sh/3ofs9fh9ahlmuxt/AAD4DgPgoimwLT7Iq9dkj9dBa?dl=0

Please note that video doesn't fully demonstrate UX as I experience non-smooth feedback to my scrolling gestures.

**Comment by apalchys** [comment]
Additionally, i see similar issues when i try to scroll between "loaded" items.
