### ISSUE TITLE
Grid system

### ISSUE THREAD

**Issue by praad** [epam/UUI#379]
**Description**
I can not find any examples for how can I use the grid system of the UUI. Just examples as an images.

**Describe the solution you'd like**
It would be nice to see concrete examples with classes like Bootstrap doc has:
https://getbootstrap.com/docs/4.0/layout/grid/

**Comment by AlekseyManetov** [comment]
HI, we don't have grid system in UUI, we provide isolated components and you need to layout it on your side by any approach.
Also we provide some layout components which will help you in page layout - https://uui.epam.com/documents?category=components&id=flexItems&mode=doc&skin=UUI4_promo
