### ISSUE TITLE
[Promo - Badge]: more colors

### ISSUE THREAD

**Issue by JuliaMV** [epam/UUI#383]
**Description**
Badge component has some colors' set based on additional colors in Promo skin. 
![2022-01-17_10h31_15](https://user-images.githubusercontent.com/37875890/149726474-0bb10284-a622-4e49-96c1-2b273cac258d.png)

**Describe the solution you'd like**
We'd like to have some gray colors for Badge component like in Loveship skin. The main purpose is highlighting statuses for inactive elements in admin console.
![2022-01-17_10h31_28](https://user-images.githubusercontent.com/37875890/149726460-40bf9a62-62b7-411b-a2d9-31aaf22380db.png)

**Comment by AlekseyManetov** [comment]
@JuliaMV which colors do you actually need?

**Comment by Yaroslav-Zinkov** [comment]
Examples of Grey status
https://www.figma.com/file/UyChXPLmyv5zMrOU37KdUL/UUI4-(Components)?node-id=79%3A35614

**Comment by JuliaMV** [comment]
@AlekseyManetov any gray color would be acceptable.
