### ISSUE TITLE
Tooltip: add ability to hide tooltip content clicking anywhere.

### ISSUE THREAD

**Issue by IliaVeselov** [epam/UUI#388]
**Description**
if you open a tooltip, you have the option to close it only by clicking on the trigger again

**Describe the solution you'd like**
it is possible to close the tooltip by clicking somewhere other than it.

you are more comfortable, you can start interacting with another interface without making an extra click to close the late prompt

**Comment by AlekseyManetov** [comment]
Could you please add more information about feature which you want: behaviour, solution, which problem it solves?

**Comment by IliaVeselov** [comment]
added

**Comment by AlekseyManetov** [comment]
For you case it better to use `Dropdown` component, it's work exactly like you want - https://uui.epam.com/documents?category=components&id=dropdown&mode=doc&skin=UUI4_promo
