### ISSUE TITLE
Virtual List - add 'scroll to top' button

### ISSUE THREAD

**Issue by jakobz** [epam/UUI#39]
**Description**

It would be handy to have an Scroll-to-top button in Tables (and, probably, in other VirtualList-based components developed in projects).

**Describe the solution you'd like**

We need design for it. Something like and semi-transparent arrow at the bottom-left of the scrollable area.

Technically, it can be made like this:
- add 'renderScrollToTop' prop in the VirtualList. It can omit bothering about position. Just render anything passed inside VirtualLists's absolute positioning container.
- add 'ScrollToTopButton' component(s) in skin(s). 
- add 'showScrollToTop' prop to the DataTable. It can be enabled by default. If passed, it would render the ScrollToTopButton from the skin.

**Comment by AlekseyManetov** [comment]
We add `indexToScroll` property in useVirtualList in #533. It probably don't need to make any `renderScrollToTop` inside VirtualList, because it can be implemented by each UUI user manually according the project specific design.
