### ISSUE TITLE
[Docs]: Add Table example with custom row

### ISSUE THREAD

**Issue by AlekseyManetov** [epam/UUI#392]
Create table doc example with custom renderRow implementation

**Comment by jakobz** [comment]
https://codesandbox.io/s/uui-tables-row-styles-jz9ld?file=/Example.tsx:1423-1461 - at least let's have this example.

We need to illustrate both:
- custom css on row
- complex customizaition, like adding a foldable panel with details to each row

**Comment by NatalliaAlieva** [comment]
Released in 5.9.0 ver.
