### ISSUE TITLE
Standard table left and right 24px paddings are not always works for us, please make padding size adjustable

### ISSUE THREAD

**Issue by vitali-paliakou** [epam/UUI#398]
# Expected Behavior

![image](https://user-images.githubusercontent.com/97738348/150363102-c153823e-4e0e-4a60-8c07-e63d5cbefee7.png)
In narrow spaces (like cards) every pixel is valuable, so it both important to be able to keep information more condensed to have more of it AND it's aesthetically better on a mockups like this one

# Current Behavior

![image](https://user-images.githubusercontent.com/97738348/150362935-d34bb626-cc1c-4cb5-b519-9a10e007cd68.png)
Works great on large full page tables

**Comment by AlekseyManetov** [comment]
@vitali-paliakou we will implement such customisation for tables, but we take it to the work after implementation editable table cells behaviour, to have full set of use-cases.
