### ISSUE TITLE
Chevrons of dotted badges inherit dot's color (when they shouldn't)

### ISSUE THREAD

**Issue by vitali-paliakou** [epam/UUI#399]
# Expected Behavior

![image](https://user-images.githubusercontent.com/97738348/150364150-d12ed0b2-513c-4b3f-89bb-8dc98372bd92.png)

# Current Behavior

![image](https://user-images.githubusercontent.com/97738348/150364099-a0cded3b-a9f0-4e74-a589-4198db8309b7.png)

## Steps to Reproduce

You can test this behavior on uui.epam.com in property explorer

**Comment by AlekseyManetov** [comment]
duplication of #393
