### ISSUE TITLE
Rich text editor problem with pasting text

### ISSUE THREAD

**Issue by SoleSurvivor111** [epam/UUI#444]
# Prerequisites

# Expected Behavior

Text paste  works correct

# Current Behavior

When I am copying lists (bullet points) from my notes (OS X Notes app) to the talk summary, the sub-nodes (level 2 or more) are suppressed and not displayed. If I copy it from MS Word (OS X version) it is copied as text and the bulletting is missing

* UUI version:
* Browser name: Safari
* Operating System: Intel Mac OS X

**Comment by AlekseyManetov** [comment]
HI, we do not provide 100% support of copying from different sources in our editor, it may has a lot of different independent of us issues and how this apps use this texts. So we cannot garniture that all copying text will pasted correctly.
