### ISSUE TITLE
Possibility to open inactive drop-down list and change their value with "Enter" key

### ISSUE THREAD

**Issue by Vicktoryan** [epam/UUI#463]
1. Set property to field (Picker Input) -> isReadonly
2. Use Tab select field
3. Press Enter
![bug](https://user-images.githubusercontent.com/10162309/155654485-df82d5e1-0f1d-4d1d-a356-8974f1273eed.gif)

* UUI version: 4.5.4
* Browser name: Opera, Chrome
* Operating System: Window

**Comment by Vicktoryan** [comment]
bug reproduced in 4.6.1

**Comment by NatalliaAlieva** [comment]
> 

This fix was released in # 4.6.2
