### ISSUE TITLE
[Update logo]: Billing project (EPM-BSRV)

### ISSUE THREAD

**Issue by tatsiana1minenkova** [epam/UUI#475]
Components in Figma:
Colored logo https://www.figma.com/file/3mpAy3BEZ75n5GJEZ5UV8z/UUI-(Assets)?node-id=3562%3A13296
White logo https://www.figma.com/file/3mpAy3BEZ75n5GJEZ5UV8z/UUI-(Assets)?node-id=3562%3A13301

**Comment by AlekseyManetov** [comment]
Hi @tatsiana1minenkova, please provide svg logo files

**Comment by tatsiana1minenkova** [comment]
[Logos_Billing.zip](https://github.com/epam/UUI/files/8350998/Logos_Billing.zip)
