### ISSUE TITLE
[Tables] Scrolls are overlapping with table headers and pinned columns

### ISSUE THREAD

**Issue by shum-dev** [epam/UUI#484]
# Expected Behavior
The scroll is placed below the table header and it doesn't overlap with it.

# Current Behavior
The scroll overlaps with the header. In the case with pinned columns, the horizontal scroll is overlapping with pinned columns.

## Steps to Reproduce
See https://uui.epam.com/documents?category=components&id=tables&mode=doc&skin=UUI3_loveship

## Context
* UUI version: latest
* Browser name: chrome
* Operating System: any

![image](https://user-images.githubusercontent.com/40317982/160074524-1e7fd53d-0744-4bfb-94f2-56feb7386e55.png)

**Comment by AlekseyManetov** [comment]
Hi @shum-dev. It's expected behavior, because we use native`position: sticky` for header and pinned columns and it needed to placed into general container.
