### ISSUE TITLE
Jumping scroll in picker input tree view

### ISSUE THREAD

**Issue by shishka02** [epam/UUI#49]
When you checking a lot of items in picker input that have tree hierarchy ( gqlAsyncDataSourcce ) scroll is jumping to the top 

https://user-images.githubusercontent.com/14928263/120516361-f0c8ab80-c3d7-11eb-94de-79ae6191340a.mp4

**Comment by okrypets** [comment]
@shishka02 Hi. Can you reproduce this bug on our app - https://uui.epam.com/documents?category=components&id=pickerInput&mode=propsEditor&skin=UUI4_promo

And what version do you use?
