### ISSUE TITLE
[RTE] crash page after set list on empty line

### ISSUE THREAD

**Issue by nadiushkaNA** [epam/UUI#509]
# Current Behavior

https://user-images.githubusercontent.com/11243577/162715826-7ddd7988-ba1a-4980-88a4-c07ecc5f13f0.mp4

https://user-images.githubusercontent.com/11243577/162770549-6df6e445-378b-4a11-9308-564933b0ac73.mp4

## Steps to Reproduce

1. type first line
2. set second line empty
3. type third line
4. select 2 and 3 line
5. apply list on selection(2-3 line)
6. select 1, 2 ,3 line
7. apply list on selection(1-3 line)
8. page is crach

* UUI version: 4.6.1

**Comment by haresh1410** [comment]
@NatalliaAlieva  Can I be assigned to this issue ?

**Comment by NatalliaAlieva** [comment]
Within this issue, only the first case was fixed. The second bug is moved in ticket #470 - case 4 (bug part).
