### ISSUE TITLE
[DataTable] focusedIndex break app on first render in safari

### ISSUE THREAD

**Issue by Smalyik** [epam/UUI#526]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ V ] I am running the latest version
- [ V ] I checked the documentation and found no answer
- [ V ] I checked to make sure that this issue has not already been filed

# Description
Chrome behaviour: https://user-images.githubusercontent.com/42422844/165098866-83e66349-67c1-40e9-b17c-13d3ecb6e8fd.mov
Safari behaviour: https://user-images.githubusercontent.com/42422844/165098881-e9014ce5-4366-4e83-8555-f41249d5c0f8.mov

When changing table state in useEffect in first render like code below in safari all elements over focused don't do render (
```
const handleTableStateChange = useCallback((newState: DataSourceState) => {
      setTableState(newState);
  }, []);

const currentJobIndex = view.getVisibleRows().find(row => row.id === selectedJobFunctionBase.id)?.index;
handleTableStateChange({
    ...tableState,
    focusedIndex: currentJobIndex,
});
```
)

## Steps to Reproduce

1. Open safari
2. Set DataTable focusedIndex in useEffect in first render
3. Look at elements over focused element

## Actual result

All elements over focused not rendered

## Expected result

All elements rendered

# Environment

* UUI version: 4.5.4, 4.6.2
* Browser name: Safari version 15.3 (17612.4.9.1.8)
* Operating System: macOS Monterey 12.2.1

**Comment by AlekseyManetov** [comment]
Can't reproduce on the latest version of UUI and MacOS. If it's still reproduced, please reopen the issue.
