### ISSUE TITLE
Rows in picker input (multi) are displayed incorrectly

### ISSUE THREAD

**Issue by twentytwol** [epam/UUI#53]
Checkboxes have 9px margin-top instead 6px
<img width="328" alt="Screenshot 2021-06-10 at 14 21 32" src="https://user-images.githubusercontent.com/32148325/121517363-f5085080-c9f7-11eb-9674-b41386696de0.png">
![Screenshot 2021-06-10 at 14 21 07](https://user-images.githubusercontent.com/32148325/121517394-fd608b80-c9f7-11eb-88e8-527e4dc212b8.png)

**Comment by AlekseyManetov** [comment]
Will be fixed in next release
