### ISSUE TITLE
Update to React 18

### ISSUE THREAD

**Issue by AlekseyManetov** [epam/UUI#533]
1. Update 'react-focus-lock'  when the issue is resolved https://github.com/theKashey/react-focus-lock/issues/215
2. Update 'react-markdown'
3. Update 'react-custom-scrollbars-2' when the issue is resolved https://github.com/RobPethick/react-custom-scrollbars-2/issues/27
4. Replace 'react-measure' last updated 2 years ago
5. Update 'react-router'

**Comment by AlekseyManetov** [comment]
please pay attention on portal users(like Dropdown and Tooltip) that the don't create extra portal nodes on open

**Comment by vasilii-kovalev** [comment]
> please pay attention on portal users(like Dropdown and Tooltip) that the don't create extra portal nodes on open

I've faced the problems with Dropdown component and created a little demo to illustrate it (and test, when the library is updated).
https://codesandbox.io/s/uui-dropdown-react-18-issue-mjhlrh
There are 2 issues in there:
1. When hovering over the button, the inner text appears in the top left corner first, then, after a short time, appears when it belongs
2. When **clicking** on the button (which shows the content **on hover**), an error occurs:
![image](https://user-images.githubusercontent.com/10310491/183421107-a6b19589-1626-45db-8f29-1dec09f7589a.png)

Hope it will be useful.
