### ISSUE TITLE
[RTE]: Need double-click to outside element for click will work if  you work in Text rich

### ISSUE THREAD

**Issue by Vicktoryan** [epam/UUI#54]
# Expected Behavior

Click to element work after one click

# Current Behavior

Start edit in text rich block, after that click some outside element

## Steps to Reproduce

Please provide detailed steps for reproducing the issue. Provide screenshots or minimal code snippet where appropriate.

1. Start edit in text rich block
2. Click some outside element 
3. Text rich had lost focus, but click didn't work
4. If click to element again, click will work

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* UUI version: 4.0.0
* Browser name: All
* Operating System: Windows

**Comment by okrypets** [comment]
@Vicktoryan Hi. Can you reproduce this bug in our [demo](https://uui.epam.com/demo?id=RTE) and record video.

**Comment by Vicktoryan** [comment]
reproduce 4.2.1
![anim_bug](https://user-images.githubusercontent.com/10162309/132502165-ad7c8185-8e28-4679-bca5-0b686ae0ce8a.gif)
