### ISSUE TITLE
Open for edit disabled double date picker

### ISSUE THREAD

**Issue by Vicktoryan** [epam/UUI#55]
# Prerequisites

# Expected Behavior

Don't open for edit

# Current Behavior

![image](https://user-images.githubusercontent.com/10162309/121643999-4c6bf680-cab4-11eb-9dcf-787cf65cf6b7.png)

## Steps to Reproduce

Please provide detailed steps for reproducing the issue. Provide screenshots or minimal code snippet where appropriate.

1. Disable double date picker element
2. Click to input block

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* UUI version: 3.x
* Browser name: All
* Operating System: Windows

**Comment by AlekseyManetov** [comment]
Please update to the latest UUI version or try to reproduce it here - https://uui.epam.com/documents?category=components&id=rangeDatePicker&mode=propsEditor&skin=UUI4_promo

**Comment by Vicktoryan** [comment]
Before 4.0.0 — reproduced

  
>Четверг, 1 июля 2021, 11:47 +03:00 от Aleksey Manetov ***@***.***>:
> 
> 
>Please update to the latest UUI version or try to reproduce it here -  https://uui.epam.com/documents?category=components&id=rangeDatePicker&mode=propsEditor&skin=UUI4_promo
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Alex Alien
