### ISSUE TITLE
[App][Checkbox] Remove unused colors from the website for UUI3

### ISSUE THREAD

**Issue by NatalliaAlieva** [epam/UUI#552]
## Steps to Reproduce

1. Open https://uui.epam.com/documents?category=components&id=checkbox&mode=doc&skin=UUI3_loveship
2. Go to Property Explorer.
3. Set property "color = white".
4. Set property "value = true".

## Actual result

"Value = true" for white color is not visible.

### Intended solution

Remove colors from white to night500 from the website.

![2022-05-30_23h41_01](https://user-images.githubusercontent.com/57751283/171061762-2dc81c04-4e1d-4952-a13a-60d0144394d5.jpg)

# Environment

* UUI version: 4.6.3
* Browser name: Chrome (101.0.4951.67), Firefox (100.0.1)
* Operating System: Win

**Comment by DzmitryTrubchyk** [comment]
Hi, here you can find design for all elements with focus state https://www.figma.com/file/k5nk7V11rswer9drJ1gmMY/UUI-Components-(Sandbox)?node-id=2932%3A277289
