### ISSUE TITLE
Change the error state view for the FileCard in File Upload

### ISSUE THREAD

**Issue by Yaroslav-Zinkov** [epam/UUI#560]
Please change the error state view for the FileCard in File Upload. 
Add the ability to delete a card (a cross in the corner) and move the error icon under the name of the card, also add the ability to display a tooltip with a description of the error by hovering

as in the example below
https://www.figma.com/file/UyChXPLmyv5zMrOU37KdUL/UUI4-(Components)?node-id=14354%3A263968

**Comment by NatalliaAlieva** [comment]
Ability to display a tooltip has been added, but is not visible on the website for users.
