### ISSUE TITLE
Fix active and hover state in DropdownMenu

### ISSUE THREAD

**Issue by Yaroslav-Zinkov** [epam/UUI#565]
Please fix active and hover state in DropdownMenu menu

What is the current behavior?

<img width="752" alt="image" src="https://user-images.githubusercontent.com/89978100/171150930-185ed16e-92af-4757-8770-e96cb23d4baf.png">

## Expected result

<img width="617" alt="image" src="https://user-images.githubusercontent.com/89978100/171151022-20010c17-6ddd-4c74-a0f7-770cb673b6d7.png">

Check the actual specification
https://www.figma.com/file/UyChXPLmyv5zMrOU37KdUL/UUI4-(Components)?node-id=14508%3A265281

**Comment by NatalliaAlieva** [comment]
The new implementation of complex examples looks like this:
![2022-06-22_15h14_47](https://user-images.githubusercontent.com/57751283/175038776-c8dc1063-3232-4e3c-9ac8-25c3e752971d.jpg)
