### ISSUE TITLE
[FileUpload]: Impossible drop file from dialog window in Firefox

### ISSUE THREAD

**Issue by JuliaMV** [epam/UUI#584]
# Prerequisites

# Description

## Steps to Reproduce
1. open https://uui.epam.com/documents?id=fileUpload&mode=doc&skin=UUI4_promo&category=components.
2. click "browse" button
3. select image in dialog window and try to drug and drop in input area

![2022-06-10_14h43_24](https://user-images.githubusercontent.com/37875890/173060115-4375a5c6-95c8-4e53-919a-d82aa3381dd7.png)

## Actual result
Selected file isn't attached.

## Expected result
Selected file is attached. 

# Environment

* UUI version: 4.6.3
* Browser name: Firefox
* Operating System: Windows

**Comment by vik753** [comment]
https://support.mozilla.org/en-US/kb/windows-administrator-launcher-process-error-fix
It isn't a bug but it's a native behaviour Firefox/Opera browsers in Windows OS.
