### ISSUE TITLE
[useVirtualList]: After scrolling at the bottom gets jammed

### ISSUE THREAD

**Issue by MSt1ch** [epam/UUI#587]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Description

After the latest response scrolling at the bottom gets jammed

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Scroll through at the bottom and wait the latest response
2. The scroll is looping

## Actual result

What is the current behavior?

[https://codesandbox.io/s/uui-forked-oc8w16?file=/Example.tsx](url)

https://user-images.githubusercontent.com/17798957/173914485-8d25e1bd-1db0-4cb5-a348-7ac518b9daba.mov

# Environment

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* UUI version: Latest
* Browser name:All
* Operating System: All

**Comment by JuliaMV** [comment]
@AlekseyManetov are there any updates related to this issue?
