### ISSUE TITLE
[App] Error "Something went wrong" appears after moving from component with "Property Explorer" to component without it

### ISSUE THREAD

**Issue by NatalliaAlieva** [epam/UUI#589]
# Description
When User moves from "Property Explorer" of "Control Group" component to "Data Tables" component they  see picture error "Something went wrong. Sorry for the inconvenience, we’ll get it fixed."

## Steps to Reproduce
1. Open [Control Group](https://uui.epam.com/documents?id=controlGroup&mode=doc&skin=UUI4_promo&category=components) component.
2. Move to "Property Explorer".
3. Go to "Data Tables" component.

## Actual result
Error "Something went wrong" appears after moving from component with "Property Explorer" to component without it

https://user-images.githubusercontent.com/57751283/174606545-77b24c18-a188-4497-b942-060282890ea5.mp4

## Expected result
If the component does not provide "Property Explorer", then the user sees a stub
![589 Property explorer _ exp result](https://user-images.githubusercontent.com/57751283/174605769-27022cf2-ba34-4d79-8e83-f0a59beed805.jpg)

## Note

Component without "Property Explorer":
- Data Tables;
- DropdownMenu;
- File Upload;
- Flex Items;
- Form;
- Modals;
- Loaders;
- Rich Text Editor;
- Scroll Spy;
- VirtualList.

**Comment by ashiqsultan** [comment]
Raised a PR for this issue, please have a look.
