### ISSUE TITLE
[SlateEditor] Images cannot adjust when width of container is changing

### ISSUE THREAD

**Issue by SystemGhost** [epam/UUI#594]
# Description

## Steps to Reproduce

1. Create plugins with basePlugins and imagePlugin() from loveship
2. Create SlateEditor with plugins
3. Add image to SlateEditor
4. click for stretch button on image (image below)
5. save temp SlateEditor state
6. change width of container (for example smaller)
7. Image in slate is cropped

start state
![image](https://user-images.githubusercontent.com/5677074/174995949-860f7f98-3824-4b17-aa8e-1cf27e77d781.png)

click for  stretch button
![image](https://user-images.githubusercontent.com/5677074/174994668-a7d2f4a4-04df-48c7-a3ac-7d7eb3d3a6cb.png)

change container for small size
![image](https://user-images.githubusercontent.com/5677074/174996119-3842eda0-b944-490b-a2a7-b91a6cc2aeca.png)

## Actual result
SlateEditor crops the picture

## Expected result
Picture varies depending on size of container 

# Environment
* Site: https://uui.epam.com/demo?id=RTE
* UUI version: 4.6.1
* Browser name: Google Chrome 
* Operating System: Windows 10

**Comment by NatalliaAlieva** [comment]
Released in 5.1.0 ver.
