### ISSUE TITLE
[DropdownMenu] Submenu closes after selecting a value in it

### ISSUE THREAD

**Issue by NatalliaAlieva** [epam/UUI#595]
# Description
When User selects any value in the submenu, it closes. User can see the selected value only after reopening the submenu.

## Steps to Reproduce

1. Open [Dropdown Menu](https://uui.epam.com/documents?id=dropdownMenu&mode=doc&skin=UUI3_loveship&category=components) component.
2. Click on Avatar in the complex example.
3. Hover the cursor over "Status" value.
4. Click on "Available" value.

## Actual result

Submenu closes immediately after selecting any value.

https://user-images.githubusercontent.com/57751283/175308347-ccbd4991-cd62-4b46-91b7-2578ea7746aa.mp4

## Expected result

Submenu remains open and User can see the value he has selected.
**OR**
Submenu closes, but with some delay so that User has time to notice what he has chosen.

# Environment

* UUI version: 4.8.0
* Browser name: Chrome, FF
* Operating System: Win 10 pro

**Comment by AlekseyManetov** [comment]
By default we need to remain dropdown open, but also we need get possibility to close dropdown by some action, for example selecting item.
