### ISSUE TITLE
[Picker Input] Parent is not marked as selected after selecting all children

### ISSUE THREAD

**Issue by ialeksandrovich** [epam/UUI#599]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Open Picker Input (with AsyncDataSource and cascadeSelection=true)
2. Select all children
3. Check parent checkbox

## Actual result

Parent isn't marked as selected (It's marked as partially selected)

## Expected result

Parent is marked as selected

* UUI version: 4.6.3
* Browser name: Chrome
* Operating System: Windows

https://user-images.githubusercontent.com/18554835/176192867-8415f689-0646-4f15-8c28-3a4b92990811.mp4

**Comment by AlekseyManetov** [comment]
it was fixed in 4.7.0 release, please update packages
