### ISSUE TITLE
[SlateEditor] Incorrect JSON is saved when replacing link

### ISSUE THREAD

**Issue by SystemGhost** [epam/UUI#600]
# Description

## Steps to Reproduce

1. Create plugins with basePlugins
2. Create SlateEditor with basePlugins,  tablePlugin() from lovership, linkPlugin()  from lovership
3. Add a table
4. Add a list to one of the table cells
5. Add link to one of the list options
6. Save the made changes
7. Return to table and load saved changes
8. Try to replace link from the step (5) with another one

## Actual result

What is the current behavior?

Has  error from ui lib:
![err1](https://user-images.githubusercontent.com/5677074/176638660-7423ae99-10d5-4ef5-a8bc-db2fab69d028.PNG)

Note: bug is showing sometimes

## Expected result

link is replaced and changes is saved

# Environment

UUI version: 4.6.1
Browser name: Google Chrome
Operating System: Windows 10

**Comment by AlekseyManetov** [comment]
Hi, could you please provider codesanbox for this case? I try to do it whithout saving(we don't have environment for save something) and don't receive any errors.
