### ISSUE TITLE
UUI components for Angular-based applications

### ISSUE THREAD

**Issue by sberdachuk-epam** [epam/UUI#61]
**Description**
Currently, it is React-based UI components and it is unclear how to use them in Angular-based applications.

**Describe the solution you'd like**
Please extend documentation on how to use these components in Angular-based applications.
If it is impossible then it will be useful to create an alternative using Stenciljs

**Comment by AlekseyManetov** [comment]
Hi, UUI is react-based library, so you can't use it with angular or any other framework.
