### ISSUE TITLE
[PickerInput] Add the ability to sort items while searching in PickerInput (AsyncDataSource)

### ISSUE THREAD

**Issue by ialeksandrovich** [epam/UUI#612]
**Description**

Add the ability to sort items while searching in PickerInput (AsyncDataSource)

We need this feature to develop our technical task: 
- Show 100% match first, then results which "starts with" what is entered for a search, then the rest results which are partially matched.
- In every group described in point 1 firstly should be shown active skills, then inactive. Each section of these results should be then sorted alphabetically.

**Describe the solution you'd like**

Add third parameter "search" in sortBy property for PickerInput
https://codesandbox.io/s/uui-custom-sorting-nrbxeh?file=/Example.tsx

**Comment by Kuznietsov** [comment]
TBD:
- Add this behavior as default for Array/Async DS.
- Add highlighting.

**Comment by AlekseyManetov** [comment]
Will be done by #1239. I am closing it due to duplication.
