### ISSUE TITLE
Impossible to use all available symbols in the text area for giving badge in Safari in the specific case

### ISSUE THREAD

**Issue by arsen2494** [epam/UUI#619]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [х] I am running the latest version
- [х] I checked the documentation and found no answer
- [х] I checked to make sure that this issue has not already been filed

# Description
[Browse specific] Impossible to use all available symbols in the text area for giving badge in Safari in the specific case. If the user starts writing a text, which starts from the new line, the count of available symbols is decreased.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Start writing text and using that some of text starts from the new line (TextArea);
2. Try to use all available symbols in the text area.## Actual result

What is the current behavior?

## Expected result

t should be possible to use all available symbols in the text area for giving badge in Safari

# Environment

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* UUI version: 4.6.3
* Browser name: Safari
* Operating System: MacOS

**Comment by NatalliaAlieva** [comment]
Dear @arsen2494, could you please provide a video of the reproduction of this bug on our components presented on the site [uui.epam.com](https://uui.epam.com/) "Components" tab?

**Comment by arsen2494** [comment]
[Screen Recording 2022-07-18 at 12.09.26.mov.zip](https://github.com/epam/UUI/files/9186911/Screen.Recording.2022-07-18.at.12.09.26.mov.zip)

@NatalliaAlieva you can find attached zip file which contains a video from or QA engineeers

**Comment by AlekseyManetov** [comment]
@arsen2494 we can't reproduce such behavior on our environment, can you please try to reproduce it on our TextArea [demo](https://uui.epam.com/documents?id=textArea&mode=doc&skin=UUI4_promo&category=components) or create the codesandbox with you code example - https://codesandbox.io/s/kb3vwq?file=/Example.tsx

**Comment by arsen2494** [comment]
<img width="1061" alt="Screen Shot 2022-07-27 at 14 10 41" src="https://user-images.githubusercontent.com/24619190/181222366-eb13ed8a-e721-441a-92ad-08be8f877750.png">

It's reproduced on demo see screenshot and make sure you're using safari on macOS

**Comment by NatalliaAlieva** [comment]
@AlekseyManetov Hi, this issue is still reproduced

https://github.com/epam/UUI/assets/57751283/7a1de37d-14af-4428-b299-f031f9f1befd

**Comment by NatalliaAlieva** [comment]
Dear @arsen2494, as of July 2024, we were unable to reproduce the bug. If the issue continues to occur, please feel free to reopen the ticket.
