### ISSUE TITLE
[MainMenuButton]: highlight active link in dropdown

### ISSUE THREAD

**Issue by JuliaMV** [epam/UUI#621]
**Description**
Currently prop isLinkActive is only one way of adding active link styles for MainMenuButton. But this approach looks unconvenient for links that were placed in dropdown.

![2022-07-19_16h38_11](https://user-images.githubusercontent.com/37875890/179764612-545b8fb0-fb10-4699-be2a-24f1ffacc545.png)
https://codesandbox.io/s/uui-forked-49jr39?file=/Example.tsx

**Describe the solution you'd like**
Would be nice to have additional styling functionality for this case.

**Comment by NatalliaAlieva** [comment]
Active state can be found [Main Menu Custom elements](https://ui-dev.epm-ppa.projects.epam.com/documents?category=components&id=mainMenu&mode=doc&skin=UUI4_promo#main_menu_custom_elements) example.
