### ISSUE TITLE
Light documentation edits to improve readability and grammar in README, landing page and overview

### ISSUE THREAD

**Issue by dxeastman-epam** [epam/UUI#622]
Update documentation text in README, BenefitsBlock.tsx and overview.json to improve readability and grammar as proposed in [my forked branch](https://github.com/epam/UUI/compare/develop...dxeastman-epam:UUI--grammar-fixes:improvement/grammar-fixes-readme-overview).

If this is ok, I can create a pull request with the changes. Thanks.

**Comment by AlekseyManetov** [comment]
Hi @dxeastman-epam, thanks for your fixes and contribution! You can create a PR, only remove mention about documentation fixes from changelog, we don't include changes which is not affect our npm packages into it.
