### ISSUE TITLE
Color icon in readonly status in Datepiker

### ISSUE THREAD

**Issue by Vicktoryan** [epam/UUI#628]
* UUI version: 4.7.1
* Browser name: Chrome
* Operating System: Windows
Check icon  color Readonly status
![image](https://user-images.githubusercontent.com/10162309/180133161-8ee18a00-a697-44a7-8115-ab8872a54625.png)
Disable status
![image](https://user-images.githubusercontent.com/10162309/180133317-725e4b5e-3975-4d80-b65a-dbaa0708712b.png)

**Comment by AlekseyManetov** [comment]
Current appearance match design specification, disabled and readonly states are different and has different styling.
