### ISSUE TITLE
Link in text editor doesn't work

### ISSUE THREAD

**Issue by arsen2494** [epam/UUI#635]
# Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Description

I checked in the UUI and the issue is reproducible. Please, see attached video   [2022-06-08_14h51_24.mp4](https://jira.epam.com/jira/secure/attachment/2620531/2620531_2022-06-08_14h51_24.mp4)for reference.

The link could be opened just through "Open link in new tab".

After page reloading the link disappears.

## Steps to Reproduce

1. User goes to Custom plan->Task->Notes/ Custom plan-> Task->Sub-task->Notes
2. Type a text and select it
3. Click on ''Link icon in text editor
4. Add a link to the text
5. Click on link
6. Select the text and click on "Link" icon

## Actual result

1. User is not redirected to the page which is  linked to the text
2. "Add link" pop-up doesn't contain the url

## Expected result

1. User is redirected to the page which is linked to the text 
2. "Add link" pop-up  contains the url

* UUI version: 4.6.3

https://user-images.githubusercontent.com/24619190/180934002-a6992fdc-bd17-4947-8943-a7454decde6f.mp4

* Browser name: Google Chrome
* Operating System: Windows

**Comment by NatalliaAlieva** [comment]
Mr. @arsen2494, 

You are trying to open a link in "edit mode". This is a correct behavior. 

https://user-images.githubusercontent.com/57751283/181014896-92a946f1-2413-4667-b13e-b65a9aade807.mp4

Regarding the disappearance of the attached link after refreshing the page, this is also correct behavior. UUI.epam.com doesn't have a back office, so this kind of change is not saved anywhere.
