### ISSUE TITLE
[UUI] Calendar cannot be fully displayed for system scale 150%

### ISSUE THREAD

**Issue by arsen2494** [epam/UUI#639]
# Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Description

Request from user Michal Masny (Contractor)
![image-2022-05-16-13-22-04-151](https://user-images.githubusercontent.com/24619190/181174832-ec0f56a7-7a52-455b-a9fb-370539c9d6bc.png)
![image-2022-05-16-13-22-25-571](https://user-images.githubusercontent.com/24619190/181174841-9f7c088c-67b6-4c7b-8207-2e183a69d47b.png)

Scale and layout 150% (displayed as recommended for HP EliteBook 840 G8 Notebook
1920x1080)

* UUI version: 4.6.3
* Browser name: Google Chrome
* Operating System: Windows

**Comment by 13IEZ** [comment]
@arsen2494 As a possible solution we add a "placement" property for Date Picker and in a future release you can control the "placement" of Date Picker
