### ISSUE TITLE
NumericInput. Minimum value is not set automatically on focus lost when value is empty

### ISSUE THREAD

**Issue by augustbright** [epam/UUI#642]
# Description

## Steps to Reproduce

Here is code sandbox to reproduce https://codesandbox.io/s/uui-forked-j7j47j?file=/Example.tsx
A NumericInput has the property "min" set to 10.

1. set the focus into numeric input
2. clean the value e.g. with backspace
3. click outside the input to make it lose the focus

## Actual result

The value of input remains unset

## Expected result

The value of the input is automatically set to the minimum possible value. That is 10 in this case

# Environment

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* UUI version: 4.8.0
* Browser name: Chrome
* Operating System: Windows 10

**Comment by NatalliaAlieva** [comment]
Released in version 4.9.0
