### ISSUE TITLE
[RTE][Safari] reverse text in list

### ISSUE THREAD

**Issue by nadiushkaNA** [epam/UUI#643]
# Description

## Steps to Reproduce

1. go to https://uui.epam.com/demo?id=RTE using Safari
2. select any list
3. type 'text'

## Actual result

https://user-images.githubusercontent.com/11243577/181580939-82b2cce7-5358-435b-bf94-123be4217307.mp4

see reverse text: 'txet'

## Expected result

see correct text

# Environment

* UUI version: 4.8.0 (on site)
* Browser name: Safari

**Comment by AlekseyManetov** [comment]
Possible solution - https://github.com/epam/UUI/pull/955, look on it after completing Slate upgrade

**Comment by NatalliaAlieva** [comment]
Released in 5.1.0 ver.
