### ISSUE TITLE
[Drag and Drop] Drop marker has different thickness

### ISSUE THREAD

**Issue by mikzakh** [epam/UUI#659]
# Description

## Steps to Reproduce

1. Visit an [example](https://uui.epam.com/documents?id=dragAndDrop&mode=doc&skin=UUI3_loveship&category=advanced) from documentation.
2. Try to drag an item to different places. 

## Actual result

Drop marker has different thickness:

![dnd1](https://user-images.githubusercontent.com/97105597/184340608-d9fc1e9b-704d-4e6a-900c-27903eae0fe6.png)

![dnd2](https://user-images.githubusercontent.com/97105597/184340623-696870df-2813-44a7-b2a5-6edfb607f1d7.png)

## Expected result

Drop marker has the same thickness.

# Environment

UUI version 4.8.0.

**Comment by Sushasgit** [comment]
Hi, @mikzakh, could you please provide more details regarding this bug (screen recording if possible), because currently we can't reproduce this issue in demo and documentation example. Thanks!

**Comment by AlekseyManetov** [comment]
@mikzakh Please reopen issue if it still reproduce
