### ISSUE TITLE
[TextInput]: Chevron is not clickable in TextInput with isDropdown=true prop

### ISSUE THREAD

**Issue by mari-shakhanava** [epam/UUI#667]
## Steps to Reproduce
1. TextInput component with prop isDropdown=true.
2. Click on chevron in TextInput

## Actual result
Chevron is not clickable, nothing happens

## Expected result
Chevron is clickable, dropdown is open

# Environment

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* UUI version: 4.8.1
* Browser name: Chrome
* Operating System: Windows 10

**Comment by NatalliaAlieva** [comment]
Released in version 4.9.0
