### ISSUE TITLE
[PickerInput] Impossible select several values from keyboard when minCharsToSearch != 0

### ISSUE THREAD

**Issue by NatalliaAlieva** [epam/UUI#670]
# Description
When User navigate using keyboard it is impossible select more than one value when selectionMode = multi and minCharsToSearch > 0.

## Steps to Reproduce

1. Open [PickerInput](https://uui.epam.com/documents?category=components&id=pickerInput&mode=propsEditor&skin=UUI4_promo) component.
2. Set `selectionMode = multi`.
3. Set `minCharsToSearch = 3` or 1 or 5.
4. Move to picker input field using `Tab` key.
5. Type three letters in the field (e.g. "lan").
6. Using `up or down arrows` navigate through values.
7. Select any value using `Enter` key.

## Actual result

Window with list closes after selecting one value and User cannot select more values.

https://user-images.githubusercontent.com/57751283/185689636-4e403790-53e9-4b13-87b9-24482c5cd69e.mp4

## Expected result

User can select more tan one value using keyboard.

# Environment

* UUI version: 4.8.2
* Browser name: Chrome
* Operating System: Win 10 pro

**Comment by Sardor2** [comment]
Missing step: Chose input for searchPosition.

Tested locally it seems working now properly.

**Comment by NatalliaAlieva** [comment]
> Missing step: Chose input for searchPosition.
> 
> Tested locally it seems working now properly.

Hello @Sardor2 !

Yes, if check on the current version, the step of selecting searchPosition is missing. But if you look at the video, it previously worked without selecting this prop.
I double-checked this bug, it really is not reproducible now.

Thank you
