### ISSUE TITLE
PickerInput inside form tag opens list of options after submitting form on enter

### ISSUE THREAD

**Issue by pavelspichonak** [epam/UUI#679]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [x] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

# Description

**PickerInput** inside **form** tag opens list of options after submitting form on **enter**

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. open [Codesandbox](https://codesandbox.io/s/uui-forked-4nv4iw?file=/Example.tsx)
2. select some value in **PickerInput**
3. set focus to **TextInput**
4. press enter to submit form

## Actual result

What is the current behavior?

**PickerInput** opens list with options

[Codesandbox](https://codesandbox.io/s/uui-forked-4nv4iw?file=/Example.tsx)

## Expected result

**PickerInput** does not open list with options.

# Environment

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* UUI version:
    "@epam/promo": "^4.8.0",
    "@epam/uui": "^4.8.0",
    "@epam/uui-components": "^4.8.0",
* Browser name: Google Chrome
* Operating System: MacOs

**Comment by pavelspichonak** [comment]
Additional information: all button must have type attribute because inside form buttons without type attribute get "submit" type and on click submit form

**Comment by AlekseyManetov** [comment]
Released in version 4.9.0
