### ISSUE TITLE
[Table] no posible drag-and-drop any column on first place in configure columns modal

### ISSUE THREAD

**Issue by nadiushkaNA** [epam/UUI#682]
# Description

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. create table with columns
2. set for first column NOT FIX position 
3. open 'Configure columns' modal
4. move last column to first place

the same with last columns

https://user-images.githubusercontent.com/11243577/188573101-2a9b2521-4fc6-4425-b444-7470397099fc.mp4

## Actual result

What is the current behavior?

user see error 'getOrderBetween: can't find values between s and s' and column no change position

## Expected result

user sucssesfull move column to first  position

# Environment
* UUI version: 4.8.3
* on demo site

**Comment by NatalliaAlieva** [comment]
Released in version 4.9.0
