### ISSUE TITLE
[Picker Input] Blue border remains after moving focus out of field in mobile screen size

### ISSUE THREAD

**Issue by NatalliaAlieva** [epam/UUI#685]
# Description
When User closes popup by clicking on the cross in the upper right corner and then clicks on `Tab` key the blue border still remains on the field.

## Steps to Reproduce

1. Open [Picker Input](https://uui.epam.com/documents?category=components&id=pickerInput&mode=propsEditor&skin=UUI4_promo) Property Explorer.
2. Reduce the window (e.g. 640x630px or less).
3. Click on the field with value list.
4. Click on the cross in the upper right corner.
5. Click `Tab` key.

## Actual result

The field with value list still highlighting with blue border.

https://user-images.githubusercontent.com/57751283/188977136-5d8777b0-a786-4496-82ab-c1f0ec788d2f.mp4

## Expected result

After shifting focus from the field with value list, it is no longer highlighted with a blue border.

# Environment

* UUI version: 4.8.3
* Browser name: any 
* Operating System: any

**Comment by blackymax** [comment]
Fixed focus, also fixed keyboard navigation for input (added the ability to call the modal with the "Enter" key and navigate inside from the keyboard). Keyboard actions need to be tested too.

**Comment by NatalliaAlieva** [comment]
Released in version 4.9.0
