### ISSUE TITLE
Indent issues with different elements of LPath's block settings 

### ISSUE THREAD

**Issue by yuliyakavalchuk1** [epam/UUI#686]
# Description
Indent issues with different elements of LPath's block settings 

## Steps to Reproduce

1. As Client Admin/Coordinator go to the 'Contribution' tab> 'Content' page;
2. Click on the row for any Lpath/User content with 'Visible for everyone' access rules and blocks added in;
3. Click on the 'Actions' button > choose 'Edit' mode;
4. Click on the gear of any block within the Lpath/User content;
5. Turn the tabs within the pop-up with settings.

## Actual result

The elements have wide indents and are displayed not according to the content.

## Expected result

The elements have the proper and exact indents and are displayed according to the content.

# Environment

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* UUI version: 4.8.3
* browser: Firefox
* Operating System: Ubundu

**Comment by yuliyakavalchuk1** [comment]
We use loveship theme now.

**Comment by NatalliaAlieva** [comment]
This is a bug not from the UUI side.
