### ISSUE TITLE
Wide indents of the pop-up while selecting actions for LPath/User Content on the Assignment tab

### ISSUE THREAD

**Issue by yuliyakavalchuk1** [epam/UUI#687]
# Description
Wide indents of the pop-up while selecting actions for LPath/User Content on the Assignment tab

## Steps to Reproduce

1. As Client Admin go to Learn ->Admin ->Assignments. 
2. Find any user's request.
3. Click on the LPath/UserContent name in "Learning" column.

## Actual result

The pop-up has additional indents (height and width) around the content.

## Expected result

 The pop-up has the indents (height and width) according to the content.

# Environment

* UUI version: 4.8.3.
* Browser name: FIrefox
* Operating System: Ubuntu

**Comment by yuliyakavalchuk1** [comment]
We use loveship theme.

**Comment by NatalliaAlieva** [comment]
This is a bug not from the UUI side.
