### ISSUE TITLE
Please fix placeholder for Note for managers field for mobile Chrome

### ISSUE THREAD

**Issue by PavelBagrovets** [epam/UUI#688]
Ticket is created in relation to Support Request [C2846021](https://support.epam.com/esp/index.do?ctx=docEngine&file=cm3r&query=header,number%3D%22C2846021%22) Talk Service:

https://jira.epam.com/jira/browse/EPMTALK-11882

Hello, please fix placeholder for Note for managers field for mobile Chrome
Attachment files:
Sent from page : https://telescope.epam.com/who/Ivan_Korshunov?tab=wall
User agent : Mozilla/5.0 (Linux; Android 12; SM-G990B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
Display size : 1920X888
Source: SDI12852490
Contact Name : Alexandr Yegioya
![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/105484469/189600423-7a83cabc-e7c4-41ee-a085-1844e6008851.png)

**Comment by NatalliaAlieva** [comment]
Hello!
What version of UII are you using?

**Comment by AlekseyManetov** [comment]
Please try to reproduce this bug on our environment - https://uui.epam.com/demo?id=RTE. I guess this bug was already fixed, so if you don't use latest version - please update uui packages.
