### ISSUE TITLE
[All Inputs] Move error text & footnote 3px down

### ISSUE THREAD

**Issue by DzmitryTrubchyk** [epam/UUI#689]
Move error text & footnote 3px down, for all components based on text input 

- Text input, 
- Numeric input, 
- Text area, 
- Picker input, 
- Search input,
- Date Picker
- Date Range Picker
- and for other form elements (checkboxes, tec.)

![image](https://user-images.githubusercontent.com/44213241/189629886-d10d2ed1-79a2-459c-a3e1-0537d5556b97.png)

**Comment by AlekseyManetov** [comment]
Because error text added by `LabeledInput` component, assume that we need rework this styles in it

**Comment by NatalliaAlieva** [comment]
Released in version 4.9.0
