### ISSUE TITLE
[NumericInput]: add possibility to round value

### ISSUE THREAD

**Issue by sanazez** [epam/UUI#69]
Can we add to NumericInput props to round the value after the decimal point? And the rounding will be worked when onBlur event.
We now have a situation that we need to prohibit the user from entering more than two decimal places, we cut it in onValueChange, but NumericInput is not updated due to checking for value in componentDidUpdate, in the case when the user adds digits to the old value.
For example: on the first input, 20.123 - > round up to 20.12 and the component is updated, on the second input, 20.1244 - > we round up to 20.12, the value for Numeric Input does not change and is not rendered according to our state, but the entered 20.1244 remains.

**Comment by okrypets** [comment]
@sanazez Hi. Now releases 4.1.0 is available. 
NumericInput suports formatter function in props. You can use it for rounding numbers.
Example:
```typescript
const BasicExample = () => {
    const [value, onValueChange] = useState(null);

    const handleFormatter = (value: number): number => {
        const formattedValue = Number(value.toFixed(2));
        return formattedValue;
    }

    return (
        <FlexCell width='auto' cx={ css.container } >
            <NumericInput 
                  value={ value } 
                  onValueChange={ onValueChange } 
                  min={ -10 } 
                  max={ 10 } 
                  formatter={handleFormatter}/>
        </FlexCell>
    );
}
```
