### ISSUE TITLE
[Picker input] rawProps for PickerInput with editMode="modal"

### ISSUE THREAD

**Issue by nanbratan** [epam/UUI#690]
**Description**
For auto-tests we need `id` on our HTML's nodes to get access to it. We already have possibility to pass `id` by `rawProps` in Picker Input, but `rawProps` doesn't work with `PickerInput editMode="modal"`(`rawProps.body` won't apply on modal window).

**Describe the solution you'd like**
We'd like to have possibility to have `id` on Picker input's modal window to have access to option list/search input/button. I think it would be nice to have `rawProps.body` on modal window, because without it we just can't use `PickerInput editMode="modal"`.

**Comment by NatalliaAlieva** [comment]
Released in version 4.9.0
