### ISSUE TITLE
[RTE] Text selection breaks if mouse cursor lands on toolbar

### ISSUE THREAD

**Issue by nadiushkaNA** [epam/UUI#696]
# Description
When User tries to select text in a table cell, his selection breaks if the cursor hits the toolbar.

## Steps to Reproduce
1. Create a table.
2. Type text in 3 line in one cell.
3. Try to select all 3 line.

## Actual result
Text selection breaks when User tries to highlight text if mouse cursor lands on toolbar.

https://user-images.githubusercontent.com/11243577/190648174-9be80738-a522-428e-87dc-6275f74c761e.mp4 

## Expected result
All lines are easy to select.

**Comment by NatalliaAlieva** [comment]
Released in 5.1.0 ver.
