### ISSUE TITLE
[RTE] Can't add list to the table.

### ISSUE THREAD

**Issue by nadiushkaNA** [epam/UUI#697]
# Description

## Steps to Reproduce

1. create table.
2. type 3 line.
3. select 3 line.
4. apply list.

## Actual result
nothing happened or all table mark as item in list

## Expected result
create list

https://user-images.githubusercontent.com/11243577/190648174-9be80738-a522-428e-87dc-6275f74c761e.mp4

**Comment by NatalliaAlieva** [comment]
It currently works with all lists except for the checkbox list.

**Comment by NatalliaAlieva** [comment]
Released in 5.1.0 ver.
