### ISSUE TITLE
[RangeDatePicker] Incorrect align for preset

### ISSUE THREAD

**Issue by nadiushkaNA** [epam/UUI#698]
# Description

What is the current behavior?

![image](https://user-images.githubusercontent.com/11243577/190660216-bbc8f7fb-4601-4cb5-a372-bda6f00c2d82.png)

## Expected result
not close to top

![image](https://user-images.githubusercontent.com/11243577/190661432-e080caeb-a1ce-4aa5-aad9-fd9b0f03429f.png)

or
![image](https://user-images.githubusercontent.com/11243577/190661546-77b7681f-0de8-4ef3-940a-e50faf33aef1.png)

# Environment

* UUI version: 4.8.5

**Comment by NatalliaAlieva** [comment]
Released in version 4.9.0
