### ISSUE TITLE
[Date Picker] onValueChange triggered without date selection

### ISSUE THREAD

**Issue by torchik-slava** [epam/UUI#709]
# Description

## Steps to Reproduce

1. have empty date picker
2. set focus to picker
3. remove focus from picker

## Actual result

onValueChange event triggered

![chrome_nPKFwXtcsa](https://user-images.githubusercontent.com/43167841/191511358-75b31463-e70d-4fdd-bbda-0eb18a369df0.gif)

## Expected result

onValueChange event not triggered

# Environment

loveship/promo (latest 4.8.5)
Chrome
Windows

**Comment by NatalliaAlieva** [comment]
Released in version 4.9.0
