### ISSUE TITLE
[MainMenuButton]: remove hover effect if button not clickable

### ISSUE THREAD

**Issue by JuliaMV** [epam/UUI#714]
# Description

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Open a demo https://codesandbox.io/s/jsvicg?file=/Example.tsx
2.  Hover MainMenuButton w/o callback or link or href.

## Actual result
Hover-style on element is applied (darken background)
![2022-09-27_09h46_38](https://user-images.githubusercontent.com/37875890/192453944-41dba008-69bb-4ab0-aa46-5b5724c5fa37.png)

The same for BurgerButton.
![2022-09-27_09h47_13](https://user-images.githubusercontent.com/37875890/192453947-1d04b12f-3caf-41cf-a1b3-9859f5a6740c.png)

## Expected result
No any style changes

# Environment

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* UUI version: latest
* Browser name: any
* Operating System: any

**Comment by JuliaMV** [comment]
please. don't forget about BurgerButton. This component has the same issue

**Comment by NatalliaAlieva** [comment]
Released in version 4.9.0
