### ISSUE TITLE
[NumericInput]: remove default min value

### ISSUE THREAD

**Issue by JuliaMV** [epam/UUI#729]
# Description

## Steps to Reproduce

1. Open sandbox https://codesandbox.io/s/nh1wyr?file=/Example.tsx
2. Remove MIN prop for NumericInput

## Actual result
Min value was defined as 0
![2022-09-29_19h37_32](https://user-images.githubusercontent.com/37875890/193089247-176e872b-217c-4786-a07c-c8296e725fcf.png)

## Expected result
There isn't any min value.

# Environment

* UUI version: latest
* Browser name: any
* Operating System: any

PS: Some interesting articles about numeric inputs:
https://stackoverflow.blog/2022/09/15/why-the-number-input-is-the-worst-input/
https://technology.blog.gov.uk/2020/02/24/why-the-gov-uk-design-system-team-changed-the-input-type-for-numbers/

**Comment by AlekseyManetov** [comment]
Hi, for most cases this is reasonable default. Cases when you need numeric with negative values it's more specific case, so if you have such case, just provide your own `min` value.
Also if we remove this default it will be breaking change for app who relied on it.
