### ISSUE TITLE
[RangeDatePicker] Add ability to set a class to the date pickers toggler

### ISSUE THREAD

**Issue by vasilii-kovalev** [epam/UUI#733]
## Now

There is no ability to set a class to the date pickers wrapper (the `div`, that includes both inputs and a border between them). If one would want to customize it and its children, it would be necessary to:
1. Wrap `RangeDatePicker` in a `div` and set a class to it, like this:
  ```typescript
  <div className={styles.wrapper}>
    <RangeDatePicker
      value={value}
      onValueChange={onValueChange}
      format="MMM D, YYYY"
    />
  </div>
  ```
2. Add tag selector, like this:
  ```css
  /* The date pickers wrapper's styles. */
  .wrapper > div {
    /* Some rules. */
  }

  /* The border between the inputs. */
  .wrapper > div > :not(:global(.uui-input-box)) {
    /* Some rules. */
  }
  ```

There is `cx` property, but its value is assigned to the dropdown body, not the dropdown target.

Here's a little demo: https://codesandbox.io/s/uui-range-date-picker-class-name-issue-o9xh34?file=/Example.tsx.

## To Do

Add a property for a CSS class, that would be assigned to the dropdown target (the date pickers wrapper). That would make adding a wrapper on the user's side unnecessary.

## Describe the solution you'd like (optional)

Actually, `cx` should be used for that, but changing the element it is assigned to would be a breaking change. Unless this issue has been taken to work during a new major version's development, a property called `pickersCx` or something like this would help.

**Comment by AlekseyManetov** [comment]
Will be done by this task - https://github.com/epam/UUI/issues/845
