### ISSUE TITLE
[ScrollBars] Updates in nested children is not reflected

### ISSUE THREAD

**Issue by vasilii-kovalev** [epam/UUI#734]
## Description

`ScrollBars` component's UI is not updated, when there are changes in width and/or height in its children.

## Steps to Reproduce

1. Go to this [CodeSandbox](https://codesandbox.io/s/uui-scrollbars-nested-children-issue-qqgnw8?file=/Example.tsx)
2. Open tab "With spoilers"
3. Clicking on one of the spoilers ("First", "Second" or "Third") to open it
4. Scroll down a bit
5. Click on the spoiler again to close it

## Actual result

3. The vertical scroll track didn't appear, though content overflows the container
4. The scroll track appears
5. The scroll track remains visible, though content doesn't overflow the container anymore

## Expected result

3. The vertical scroll track appears
4. The scroll track is still visible
5. The scroll track disappears

## Environment

* UUI version: 4.8.5
* Browser name: Google Chrome v.106.0.5249.91
* Operating System: Windows 10 64-bit

## Notes
1. On the tab "With spoilers (fixed)" the problem is fixed: the scroll track appears and disappears correctly. The difference is, in this case, the component containing `ScrollBars` is forced to re-render if any changes happen in its children
2. The last tab "Plain" contains a plain list of rows, and was added just to show, that the problem appears only when content is not in the same component with `ScrollBars`

**Comment by vasilii-kovalev** [comment]
Please, add the necessary label. I created this issue from the discussion, and it wasn't assigned automatically.

**Comment by AlekseyManetov** [comment]
Closed according this [comment](https://github.com/epam/UUI/discussions/719#discussioncomment-3814129)
