### ISSUE TITLE
[RangeDatePicker] Improve close handling of the "to" field when a date is chosen

### ISSUE THREAD

**Issue by vasilii-kovalev** [epam/UUI#736]
## Now

The "to" field always closes when:
1. Both dates exist
2. The last time the focus was on the "to" field

I believe that [this code](https://github.com/epam/UUI/blob/main/uui-components/src/inputs/DatePicker/RangeDatePickerBody.tsx#L151-L153) handles this.

## Business case

In our case, if a date has been chosen, and the range is big enough, we want other date to be cleared, and the focus is moved to "from" date, so that the user can choose it manually, and only after that it would be applied. It works for "from" field fine, because there is a transition of focus from "from" date to "to" one.

The business case for that is if a big range is chosen, a large amount of data is fetched from the back-end, which is undesirable. For example:
1. Today is "02-10-2022"
2. Somehow, user was able to pick "from" date "01-04-2020" and "to" date "30-04-2020"
3. User wants to pick "to" date "01-09-2020"

In this case, the range is about 150 days, which is huge, and we need to clear the "from" date, so that the user can choose, for example, "01-07-2020". If they still want to pick "01-04-2020", then we will accept it, and start loading that huge amount of data, but the first time it shouldn't happen. That big range could be chosen by an accident after all.

## To Do

Make it possible to change focus from "to" to "from" date (like it is done for "from" → "to" dates transition), when "from" date is cleared, and not closing the dropdown's body automatically.

**Comment by vasilii-kovalev** [comment]
I can see, that the PR #907, which covers this request, is already merged. Maybe it makes sense to close this issue, then.
@AlekseyManetov

**Comment by NatalliaAlieva** [comment]
The next thing is done: the focus automatically shifts from the "To" field to the "From" field, if it is not filled.

**Comment by NatalliaAlieva** [comment]
Released in 4.10.0 version.
