### ISSUE TITLE
[UuiContext] Add ability to provide data in `props.abort` in `svc.uuiModals.show` function

### ISSUE THREAD

**Issue by vasilii-kovalev** [epam/UUI#737]
# Now

`svc.uuiModals.show` provides `success` and `abort` functions, that can be used in the modal windows to close them, but only `success` one [accepts](https://github.com/epam/UUI/blob/921cf6def305db83596dae5798e1dfc638f251cf/uui-core/types/props.ts#L124) something, that can be used on the level the `svc.uuiModals.show` is called. If an error occurs, it is necessary to call `success` function to pass the error-related data.

# To Do

Allow `abort` function to accept data as well.

**Comment by AlekseyManetov** [comment]
Will be released in 4.9.0 version
