### ISSUE TITLE
[useLazyDataSource] Incorrect type of `parent` and `parentId` in `api` function's context parameter

### ISSUE THREAD

**Issue by vasilii-kovalev** [epam/UUI#738]
## Description

`api` function in `useLazyDataSource` provides the second (`context`) parameter, that has `parent` and `parentId` values, which are used to determine, which node was clicked on in the tree data structure. [By definition](https://github.com/epam/UUI/blob/main/uui-core/data/processing/types.ts#L57-L60), they can be either omitted (which is equal to `undefined`) or have types `TItem` and `TId` accordingly. But actually they both have `null` value when omitted.

## Steps to Reproduce

1. Go to this [CodeSandbox](https://codesandbox.io/s/uui-use-lazy-data-source-parent-type-issue-tquxqk?file=/Example.tsx)
2. Wait until the page is loaded. It should look like this: 
![image](https://user-images.githubusercontent.com/10310491/193450724-1b3e90b0-c3ff-4a94-a2d9-995b7d1cee3c.png)
3. Check the console

## Actual result

The console contains string `{parentId: null, parent: null}`, which means that when the first level was loading, `parent` and `parentId` had value `null` instead of `undefined`.

## Expected result

Types and implementation should match, be it `undefined` or `null`.

## Environment

* UUI version: 4.8.5
* Browser name: Google Chrome v.106.0.5249.91
* Operating System: Windows 10 64-bit

**Comment by AlekseyManetov** [comment]
will be fixed in 4.9.0 version
