### ISSUE TITLE
Remove links to internal EPAM repositories

### ISSUE THREAD

**Issue by vasilii-kovalev** [epam/UUI#740]
## Now

There are [several links to internal EPAM repositories](https://github.com/epam/UUI/search?q=git.epam.com). Maybe there are others, that can be found by another query. Since the library is now open sourced, it makes sense to get rid of them.

## To Do

* The links should be replaced with the actual ones or removed
* All the necessary code should be migrated from the internal EPAM repositories to this one
* The internal EPAM repositories should be removed (they are abandoned anyway)

**Comment by NatalliaAlieva** [comment]
Released in version 4.9.0
