### ISSUE TITLE
[PickerInput]: apply value to search on first type in single mode

### ISSUE THREAD

**Issue by AlekseyManetov** [epam/UUI#748]
## Now
Now after you select item in `PickerInput`, your search is removing and when you open `PickerInput` there is no any search value. But it can be useful to apply current selected value to the search, to be able to find some similar items. For example, you select 'Solution Architect 2' and then just want to select 'Solution Architect 3'. Now you need to type 'Solution Architect' one more time, but if we prefill search with already selected value, you just need to delete the last symbol to see all 'Solution Architect' items. This behavior inspired by Jira filters behavior.
<img width="502" alt="image" src="https://user-images.githubusercontent.com/14283670/194363573-a7c36d9f-ca03-4192-bfc4-b44eff8286bc.png">

## To Do
Don't apply placeholder styles for search, when picker is opening add current value to the search input, but don't apply it until user made any the change in search, when he change it - apply changed value. If it possible, make value in search selected on picker open.
<img width="437" alt="image" src="https://user-images.githubusercontent.com/14283670/194360867-618dc959-f632-4362-9a36-3a579e21cee7.png">

## Describe the solution you'd like (optional)
We need to create the separate state for search input and apply this search to the DataSource when user made the first change, for this we can add some boolean variable, aka `isSearchChanged` and if this variable is true also apply search to the DataSource.

**Comment by NatalliaAlieva** [comment]
Released in version 4.9.0
