### ISSUE TITLE
[PickerInput]: clear search field after selection (multi select)

### ISSUE THREAD

**Issue by mylostandromeda** [epam/UUI#750]
## Description
Search field doesn't clear after selection

## Steps to Reproduce
1. Move to [Picker Input](https://uui.epam.com/documents?category=components&id=pickerInput&mode=propsEditor&skin=UUI4_promo)
2. Set `selectionMode=multi`
3. Set `searchPosition=Input`
4. Search some item
5. Select some item
6. See search field after selection

## Actual result
Search field doesn't clear after selection
![image](https://user-images.githubusercontent.com/49440391/194555653-48c812a4-a12c-424a-95a5-c843d14b7741.png)
[Watch the video](https://jira.epam.com/jira/secure/attachment/2594248/OrgName.mp4)
## Expected result
Search field clearing after selection
## Environment

* UUI version: 4.8.5
* Browser name: any
* Operating System: Windows 10

**Comment by AlekseyManetov** [comment]
It's expected behavior, search is clearing only on picker close, if we will clear it on any items selection, you can't select more than one items according your search.
