### ISSUE TITLE
[UUI Site] Tooltip on Slider & Slider Rating

### ISSUE THREAD

**Issue by DzmitryTrubchyk** [epam/UUI#757]
Tooltips seem to be broken on UUI site
![image](https://user-images.githubusercontent.com/44213241/195029083-556bc05d-446e-4e10-b18c-2b0c0ceb2bcd.png)
![image](https://user-images.githubusercontent.com/44213241/195029334-4ee6cc26-5b13-4343-9e10-8c9441e7b56a.png)

**Comment by AlekseyManetov** [comment]
Is seams that we broke paddings in Tooltip component in all cases, you can find this issue on each Tooltip demo.

**Comment by NatalliaAlieva** [comment]
Released in version 4.9.0
