### ISSUE TITLE
[Assets from Skills library] Update icon pack

### ISSUE THREAD

**Issue by DzmitryTrubchyk** [epam/UUI#758]
Please, find updated icon pack below. Changes:

- Added icons from Skills library
- Import/Export icons renamed, according to more logical and global usage
- Icons added: 
status: open, in progress (12)
folder (18,24,36)
view table (18,36)
view grid (18,24,36)
radar (24)

[UUI icon pack 11.10.22.zip](https://github.com/epam/UUI/files/9753401/UUI.icon.pack.11.10.22.zip)

**Comment by AlekseyManetov** [comment]
released in 4.9.0
