### ISSUE TITLE
[LinkButton] `captionCX` property is not applied to the caption in Loveship skin

### ISSUE THREAD

**Issue by vasilii-kovalev** [epam/UUI#775]
## Description

`captionCX` property is not applied to the caption in Loveship skin (but is applied in Promo one).

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Go to this [CodeSandbox](https://codesandbox.io/s/uui-link-button-caption-cx-issue-kbd934?file=/Example.tsx)
2. Check the text's color of the button with text "LinkButton (Promo)"
3. Check the text's color of the button with text "LinkButton (Loveship)"

## Actual result

1. --
2. The text's color is red
3. The text's color is default for this component

## Expected result

The text's color is red for both buttons.

## Environment

* UUI version: 4.8.5
* Browser name: Google Chrome v.106.0.5249.119
* Operating System: Windows 10 64-bit

**Comment by AlekseyManetov** [comment]
Hi, this is internal prop, which can be deprecated in feature, we don't recommend to use it, better just pass your css selector via `cx` which will find global `.uui-caption` element.
