### ISSUE TITLE
[MainMenu] Issues in the CodeSandbox examples

### ISSUE THREAD

**Issue by vasilii-kovalev** [epam/UUI#780]
## Description

There are some issues with the provided examples in CodeSandbox for `MainMenu` component.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Go to [the last example's CodeSandbox](https://codesandbox.io/s/cbvel1?file=/Example.tsx) (it contains all the problems mentioned below)
2. Check the logo image
3. Check the "Give badge" image
4. Click on the side menu icon (on the left side of the component) and observe the side menu's height

## Actual result

![image](https://user-images.githubusercontent.com/10310491/196320259-8c5ca7ac-8eb1-4784-bef3-17fa12b33327.png)
![image](https://user-images.githubusercontent.com/10310491/196320292-36ea0b8e-e610-487c-ae16-4e07f371562f.png)

1. --
2. The logo image is broken in all the examples
3. The "Give badge" image is broken in the last example
4. The side menu doesn't occupy the screen's height fully

## Expected result

1. --
2. The logo image is displayed correctly in all the examples, like it does in the documentation
3. The "Give badge" image is displayed correctly in the last example, like it does in the documentation
4. The side menu occupies the screen's height fully

## Environment

* UUI version: 4.8.5
* Browser name: Google Chrome v.106.0.5249.119
* Operating System: Windows 10 64-bit

**Comment by NatalliaAlieva** [comment]
Released in version 4.9.0
