### ISSUE TITLE
Support a full page spinner

### ISSUE THREAD

**Issue by vasilii-kovalev** [epam/UUI#781]
## Description

For now there is no possibility to make a full page spinner getting along with UUI library nicely. The library has a [layouts counting logic](https://github.com/epam/UUI/blob/main/uui-core/services/LayoutContext.ts), that affects `z-index` rule's value of each layer, but only a [small bunch of components](https://github.com/epam/UUI/search?p=1&q=.getLayer%28%29) contribute to it.
I've created a [demo](https://codesandbox.io/s/full-page-spinner-with-custom-layout-fddwef?file=/example.tsx) to illustrate how we do the full page spinner component ourselves. When clicking on the "Show modal" button to open the modal window, and then clicking on the "Ok" button, a custom overlay with red background and a spinner in the middle should appear.
![image](https://user-images.githubusercontent.com/10310491/196335673-16932d52-5c93-4d05-b6dd-6ed805cd5ec9.png)
Since our custom component doesn't contribute to the layers count, it doesn't know which `z-index` it should have, and thus it is displayed **behind** the modal window, though it should be **in front of** it. Increasing `z-index` rule's value in `example.module.css` solves the problem, but since `z-index` of the modal window may be variable, it is a guessing game - today it works, tomorrow it doesn't. Replacing `FullPageSpinner` with `Blocker` from the library doesn't change anything, because `Blocker` doesn't contribute to the layers count either.
A temporary solution is to use `zIndex` property from the modal window blocker's props (`modalProps` in the CodeSandbox example), and assign `zIndex + 1`, for instance, to the `FullPageSpinner` component, but it would be great if it would happen **automatically** so that it won't be necessary to do it manually in every place like this. Also, the spinner may not only be needed while performing actions in modal windows - it may be needed on the page with other components too (like dropdowns, tooltips, etc.), which means we can't always rely on (and have access to) the component's props.

## Describe the solution you'd like

* Change `Blocker` component, so that it:
  * Supports a custom layout (via `children` property, for example)
  * Contributes to the layers count
  **and/or**
* Provide an ability to contribute to the layers count manually. Maybe be dangerous, because it will be harder to understand, what layer comes from where, and can break the layers' natural flow
  **and/or**
* Create a separate component (to avoid potential breaking changes, if you are afraid of them), which:
  * Supports a custom layout (via `children` property, for example)
  * Contributes to the layers count

**Comment by AlekseyManetov** [comment]
You can also use our layout context inside your components, via `const layer = context.uuiLayout.getLayer()` and then use `layer.zIndex` inside your component or pass it into our `Blocker`. 
I have fixed your example - https://codesandbox.io/s/full-page-spinner-with-custom-layout-forked-pg69h9?file=/full-page-spinner.tsx

**Comment by vasilii-kovalev** [comment]
Thank you! It works in our codebase too (v.4.6.3). I suppose the issue is not relevant anymore and can be closed, but I think it makes sense to add this use case to the documentation (to "Contexts" section).

**Comment by AlekseyManetov** [comment]
Yes, totally agree, we need to have Layout Context documentation also, we will add it in nearest feature. Thanks.
