### ISSUE TITLE
[Data tables] Unable to select all filtered rows by clicking on general checkbox in the table header

### ISSUE THREAD

**Issue by NatalliaAlieva** [epam/UUI#782]
## Description
User cannot select all rows in a table by clicking the general checkbox in the table header.

## Steps to Reproduce
1. Open Demo -> [Filtered table](https://uui.epam.com/demo?id=filteredTable) OR Demo -> [Table](https://uui.epam.com/demo?id=table) OR Data tables -> Advanced -> [Columns Configuration](https://uui.epam.com/documents?id=advancedTables&mode=doc&skin=UUI4_promo&category=tables#columns_configuration)
2. Click the checkbox in the table header to the left of the "Name" column.

## Actual result
Nothing happens. The rows are not selected.

https://user-images.githubusercontent.com/57751283/196377570-7ad8e751-78ae-4efa-9166-a6c52e6731e4.mp4

## Expected result
All table rows are selected.

## Environment
* UUI version: 4.9.0 (rc)
* Browser name: all
* Operating System: Win 10 pro

**Comment by vik753** [comment]
For the FilteredTable demo we decided to turn "selectAll" value into false position because we using here a LazyTable.

**Comment by NatalliaAlieva** [comment]
Released in version 4.9.0
