### ISSUE TITLE
[RTE] Crash page after delete horizontal line/separator

### ISSUE THREAD

**Issue by nadiushkaNA** [epam/UUI#788]
## Steps to Reproduce

1. Insert horizontal line/separator
2. Click backspace

## Actual result

https://user-images.githubusercontent.com/11243577/196912099-db9010ce-5bec-4c10-8421-a2b34daa43c0.mp4

Page is crashed

## Expected result

RTE with empty text

## Environment
https://uui.epam.com/demo?id=RTE

* UUI version: 4.8.5
* Browser name: Chrome

**Comment by NatalliaAlieva** [comment]
Released in 5.1.0 ver.
