### ISSUE TITLE
[Numeric Input] Random occurrence of value "-100" in the Base Example

### ISSUE THREAD

**Issue by NatalliaAlieva** [epam/UUI#789]
## Description
When User clicks between "Default settings", "With placeholder" and "Step = 10, Min = -100, Max = 100" fields value `-100` appears randomly.

## Steps to Reproduce
1. Open [Numeric Input component](https://uui.epam.com/documents?id=numericInput&mode=doc&skin=UUI4_promo&category=components#basic).
2. Click between "Default settings", "With placeholder" and "Step = 10, Min = -100, Max = 100" fields.

## Actual result
Value `-100` appears randomly.

https://user-images.githubusercontent.com/57751283/197292745-a146df9e-c27c-4395-a1d6-92023cebccd0.mp4

## Expected result
The value in the field doesn't change if User didn't enter any values.

## Description
User has possibility to type in the cell `e`, `.` and `-`.

## Steps to Reproduce
1. Open [Numeric Input component](https://uui.epam.com/documents?id=numericInput&mode=doc&skin=UUI4_promo&category=components#basic).
2. Type `e`, `.` and `-`

## Actual result
System allows type `e`, `.` and `-`.

![- e](https://user-images.githubusercontent.com/57751283/197725364-8ac2f0bd-11df-4445-932b-ada562411ddb.jpg)

## Expected result
System resets invalid values to the last valid values - **needs to be discussed**.

## Environment
* UUI version: 4.9.0 -rc.1
* Browser name: any
* Operating System: Win 10 Pro

**Comment by dzevakov** [comment]
**Actual result**

***Case 1***
An input with min/max attributes will no longer set a minimum value when defocusing a component when the component has an unset value or a value = 0. It will be possible to set the value to 0 if it falls within the min/max range

***Case 2***
The input values are validated. Allowed symbols for input type ="number" as "e" "-" "." can be entered. But if you enter a non-valid value using them, the input will be cleared.

**Comment by NatalliaAlieva** [comment]
Released in 4.9.1 version.
