### ISSUE TITLE
[Dropdown] Link to "Basic" example in CodeSandbox is broken

### ISSUE THREAD

**Issue by vasilii-kovalev** [epam/UUI#790]
## Description

Link to "Basic" example in CodeSandbox is broken.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Go to ["Dropdown" component's documentation page](https://uui.epam.com/documents?id=dropdown&mode=doc&category=components)
2. In "Basic" example, click on "Open in Codesanbox" button

## Actual result

CodeSandbox is not opened, and a default browsers' page for 414 error code is displayed instead.
![image](https://user-images.githubusercontent.com/10310491/197448535-f239a434-cdf1-4a4c-96eb-87b2222d0aa6.png)

## Expected result

The example is opened in CodeSandbox.

## Environment

* Browser name: Google Chrome v.106.0.5249.119
* Operating System: Windows 10 64-bit

**Comment by vasilii-kovalev** [comment]
Maybe it makes sense to check all the CodeSandbox links at once in scope of this task to avoid issues' creation for individual cases.

**Comment by SzatmariZs** [comment]
> Maybe it makes sense to check all the CodeSandbox links at once in scope of this task to avoid issues' creation for individual cases.

I found the following links not working:
* Data Tables > Editable Table
* Dropdown > Basic
* Rich Text View > Basic

I'm working on the fix if still available.

**Comment by AlekseyManetov** [comment]
released in 4.9.0
