### ISSUE TITLE
[Table filters] Selected items are hidden after click "Show only selected"

### ISSUE THREAD

**Issue by kiryl-labada** [epam/UUI#792]
## Description

Incorrect behavior for "Show only selected" for Table filters when LazyDataSource is used. Reproduced on UUI loveship.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. https://uui.epam.com/sandbox?id=tableDemo
2. Open "Job Title" filter
3. Scroll down
4. Select any element
5. Check "Show only selected"

## Actual result

View doesn't resize, so selected elements are hidden in the top

![image](https://user-images.githubusercontent.com/49092192/197527287-0831becd-375c-40ac-b98d-2a8433a2e9f4.png)

## Expected result

View matches size of selected elements like an existing behavior in Promo version

**Comment by NatalliaAlieva** [comment]
Released in version 4.9.0
