### ISSUE TITLE
[useVirtualList]: add restore scroll functionality

### ISSUE THREAD

**Issue by JuliaMV** [epam/UUI#798]
## Description

We would like to have an ability to restore a scroll position of virtual lists that based on LazyDataSource.

We've implemented solution on our side but several edge cases were found:
- all virtual list items should have the same height and there aren't any margins between them;
- the target element should be returned in the first api-call so we manually increase count-query;
- virtual list should display enough amount of placeholders, otherwise user will see empty screen;
- we should wait while estimatedHeight is calculated and only than use scrollToIndex method.

Nice to have in the future:
- scroll through the list of items in two modes (full/collapsed)
- don't fetch all items from the start and use offest for the first query (for huge lists of elements)

**Comment by NatalliaAlieva** [comment]
Released in 5.2.0 version.
