### ISSUE TITLE
[DatePicker] Add ability to enter date in format different than props.format

### ISSUE THREAD

**Issue by Kernstall** [epam/UUI#806]
## Description
Cases exist when user wants to enter date in different format than the format he wants to see date, for example, when copy-pasting dates from another source.

## Describe the solution you'd like
User enters date in some format, e.g. "YYYY-MMM-DD", on losing focus datePicker calls onValueChange and changes format to props.format

**Comment by Sushasgit** [comment]
Added the list of support dates format (for input):
- "MM/DD/YYYY",
- "DD-MM-YYYY",
-  "DD.MM.YYYY",
-  "YYYY/MM/DD",
-  "YYYY-MM-DD",
- "YYYY.MM.DD",
- "MMM D, YYYY",
- "D/M/YYYY",
-  "YYYY/M/D",

**Comment by NatalliaAlieva** [comment]
The system is still case-sensitive in the format MMM D, YYYY. For example. Dec 3, 2022 is a valid value, but dec 3, 2022 is not valid. We are trying to clarify this point in [this ](https://github.com/iamkun/dayjs/issues/2177)ticket.

**Comment by NatalliaAlieva** [comment]
Released in 4.9.1.
