### ISSUE TITLE
TimePicker component should be able to format time in utc

### ISSUE THREAD

**Issue by AndriyHromyak** [epam/UUI#818]
## Describe the solution you'd like (optional)
TimePicker is always presenting time in local timezone format yet it should be able to show time in utc format.

ex:  "2022-11-12T00:00:00z" should produce time as 00:00 and not within local time zone

dayjs has option for that.
https://day.js.org/docs/en/plugin/utc

**Comment by AlekseyManetov** [comment]
TimePicker component works just with { hours: string, minutes: string } value, it doesn't work with date time format. But you can make it on your side:
```
const date = new Date();
date.setHours(timePickerValue.hours);
date.setMinutes(timePickerValue.minutes);
```

**Comment by AndriyHromyak** [comment]
I believe it will correct min and hours according to local timezone. so if we pass 01:00 we will see in form input 03:00, as an example.  Won't it?

**Comment by AlekseyManetov** [comment]
No, it's not a business of `TimePicker`, it doesn't know anything about timezone and should't make any conversations. Also it can be specific behavior for each project, some app need to have such adjustment according the timezone, some not. So you need to do it on your side and pass already adjusted for timezone value to the `TimePicker`.
