### ISSUE TITLE
[DatePicker]: can't delete value by keyboard

### ISSUE THREAD

**Issue by dsv-sergey** [epam/UUI#828]
## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. choose any date
2. clear from field using keyboard
3. open React inspect, check value

## Actual result

What is the current behavior?

![image](https://user-images.githubusercontent.com/33173033/202695740-af636f51-a840-45bb-b2ea-e556e1349875.png)

## Expected result

The value is null or another valid type

**Comment by NatalliaAlieva** [comment]
Released in 4.9.1 version
