### ISSUE TITLE
[NumericInput]: change value onScroll

### ISSUE THREAD

**Issue by JuliaMV** [epam/UUI#835]
If user focuses on NumeriсInput and starts scrolling (using mouse or touchpad) the input value will be changed with scroll page simultaneously. https://uui.epam.com/documents?id=numericInput&mode=doc&skin=UUI4_promo&category=components

Looks like this  behavior related to React events https://github.com/facebook/react/issues/14856.
But in vanilla input type=number state isn't changed on scroll. https://codepen.io/JuliaMV/pen/jOKzgQz

I think would be better to do one thing or scroll or change input state.

**Comment by dzevakov** [comment]
The proposed implementation describes the following behavior:

1 When the mouse cursor is over the input and the input is in focus - when scrolling, the value of the input does not change, the page does not scroll

2 When the mouse cursor is over the input and the input is not in focus - when scrolling, the value of the input does not change, the page scrolls

3 When the mouse cursor is outside the input and the input is in focus - when scrolling, the value of the input does not change, the page scrolls

**Comment by NatalliaAlieva** [comment]
Released in 4.9.1 version.
