### ISSUE TITLE
[Docs]: Tooltips examples rework

### ISSUE THREAD

**Issue by DzmitryTrubchyk** [epam/UUI#836]
## Examples based on tooltip variant

[See prototype](https://www.figma.com/proto/XvNqYvKrGf8PP1wCedPVQu/UUI-Components-Main-Branch-(Sandbox)?page-id=1337%3A321257&node-id=1449%3A328514&viewport=2179%2C486%2C0.18&scaling=min-zoom&starting-point-node-id=1449%3A328514&show-proto-sidebar=1)
[See design here](https://www.figma.com/file/XvNqYvKrGf8PP1wCedPVQu/UUI-Components-Main-Branch-(Sandbox)?node-id=1449%3A328514&t=SpUQ8D7mYoddZZpl-1)

Default examples
![image](https://user-images.githubusercontent.com/44213241/205090455-ee40e09d-2d01-48cb-971a-5f5cbfcf980f.png)

Compact example
![image](https://user-images.githubusercontent.com/44213241/205092961-e0cf202f-d3ac-4697-9f6d-73afdb07e7d6.png)

Infotip example(replace current Custom markup example)
![image](https://user-images.githubusercontent.com/44213241/203788705-23cab964-d655-4c32-b35c-4dcf16880b72.png)
![image](https://user-images.githubusercontent.com/44213241/203788744-b9d149eb-d0bb-4141-9949-30186c0b1ec3.png)

Custom examples with logic of closing one dropdown by opening new one (implement on Dropdown and also add it for Dropdown doc) 
![image](https://user-images.githubusercontent.com/44213241/205089608-e353be3d-921b-43da-a5f6-6503aec639b1.png)

Placement and direction
![image](https://user-images.githubusercontent.com/44213241/203788466-dbf1a7b3-314d-4d1a-a764-27e01f9640cb.png)

**Comment by NatalliaAlieva** [comment]
Released in 4.10.0 version.
