### ISSUE TITLE
[PickeInput]: error while deleting item

### ISSUE THREAD

**Issue by JuliaMV** [epam/UUI#843]
## Steps to Reproduce

1. Create PickerInput with selection mode "multy" and lazy datasource.
2. Render PickerInput with initial value as array of several items.
3. Try to delete one item.

## Actual result
![2022-11-29_14h30_53](https://user-images.githubusercontent.com/37875890/204518011-a37b8db4-09c1-4807-944a-20da44d8ed8d.png)

## Expected result
Item is deleted without errors.

## Environment

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* UUI version: 4.9.0 
* Browser name: any
* Operating System: any

**Comment by AlekseyManetov** [comment]
released in 4.9.1
