### ISSUE TITLE
[PickerInput, LazyDataSource] No programatically selected and already loaded value in Show selected mode if api returns empty array

### ISSUE THREAD

**Issue by cpof-tea** [epam/UUI#849]
## Prerequisites

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

## Description

Programmatically selected already loaded item doesn't show up in Show selected mode, if an api returns empty array of items upon showing dropdown.

## Steps to Reproduce

You can follow these steps
on [Example (UUI Codesandbox, `valueType="id"`)](https://codesandbox.io/s/picker-input-lazy-list-bug-4-9-0-w1jb2w?file=/Example.tsx)
or [Example (UUI Codesandbox, `valueType="entity"`)](https://codesandbox.io/s/picker-input-lazy-list-bug-4-9-0-entity-type-r40u0k?file=/Example.tsx)
1. When `PickerInput` has preselected value
2. And I click on picker input
3. And I toggle Show selected
4. Then I see selected item
5. And I click on clear button
6. And I click Programmatic update button
7. Then `PickerInput` has programmatically selected value
8. And I click on picker input
9. And I toggle Show selected

## Actual result

Programmatically selected already loaded item doesn't show up in Show selected mode.

## Expected result

Programmatically selected already loaded item should show up in Show selected mode.

## Environment

* UUI version: 4.9.0
* Browser name: Firefox 107.0
* Operating System: Ubuntu 20.04

**Comment by AlekseyManetov** [comment]
Will be fixed in next release
