### ISSUE TITLE
[DropdownMenuButton] There is no way to add `rel` attribute

### ISSUE THREAD

**Issue by svikhristyuk** [epam/UUI#857]
## Now
We have a security issue:
Using target without correctly setting the "rel" attribute, or disassociating the new window from its parent, is an unsafe way of opening a new window. 

## To Do
How to avoid it:

  * Do not set the "target" attribute (with any value) for links created by users unless required.
  * If required, when using the "target" attribute, also set the "rel" attribute as “noopener noreferrer”:
      + “noopener” for Chrome and Opera
      + “noreferrer” for Firefox and old browsers

## Describe the solution you'd like (optional)

I suggest to add rel property to `ICanRedirect` interface

**Comment by NatalliaAlieva** [comment]
Released in 4.10.0 version.
