### ISSUE TITLE
[Docs]: Badge examples rework

### ISSUE THREAD

**Issue by DzmitryTrubchyk** [epam/UUI#866]
[Prototype](https://www.figma.com/proto/XvNqYvKrGf8PP1wCedPVQu/UUI-Components-Main-Branch-(Sandbox)?page-id=1337%3A321257&node-id=1509%3A356440&viewport=10417%2C4397%2C0.93&scaling=min-zoom&starting-point-node-id=1509%3A356440&show-proto-sidebar=1)
[Design](https://www.figma.com/file/XvNqYvKrGf8PP1wCedPVQu/UUI-Components-Main-Branch-(Sandbox)?node-id=1509%3A356440&t=QUum9CgcXhLeO9x1-1)

![image](https://user-images.githubusercontent.com/44213241/206319220-753693bd-1277-474e-a949-45d8b8aaf340.png)

**Comment by NatalliaAlieva** [comment]
Released in 4.10.0 version.
