### ISSUE TITLE
Columns config dialog - deny to hide all columns

### ISSUE THREAD

**Issue by jakobz** [epam/UUI#878]
## Description

If there's no isAlwaysVisible columns, it's possible to disable all columns. This can lead to confusing UI state, and trigger other problems. 

Let's prevent this "no columns visible state" by adding validation to the column config dialog.

## Describe the solution you'd like

Options
- disable the last column checkbox to deny unchecking it
- disable "OK" button of the dialog, with a comment like "Please enable at least one column"

Note that some tables have the right small "tools/burger-menu" column. It shouldn't count - user shouldn't be able to uncheck all columns except this one. We already have some logic to exclude this column from the Columns dialog - let's just re-use it.

**Comment by Yaroslav-Zinkov** [comment]
<img width="699" alt="image" src="https://user-images.githubusercontent.com/89978100/210974524-dc9bf811-051f-4d14-94f0-d3517750fa10.png">
https://www.figma.com/file/yph0lYTxCIM3GWExIVeNAb/UUI-%E2%80%93-Tables-Examples?node-id=2467%3A689872&t=7Xu5fgBgcElItp7S-1

**Comment by Kunzetsov** [comment]
@Yaroslav-Zinkov, thanks for the details 👍

**Comment by Kunzetsov** [comment]
According to the new notes of @DzmitryTrubchyk, the color of the tooltip should be changed to `grey90` or `night900`.

**Comment by NatalliaAlieva** [comment]
Released in 4.10.0 version.
