### ISSUE TITLE
[PickerInput, AsyncDataSource] `onValueChange` invoked with old value when value changed during data source loading

### ISSUE THREAD

**Issue by cpof-tea** [epam/UUI#879]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Steps to Reproduce

[UUI Codesandbox](https://codesandbox.io/s/onvaluechange-invocation-with-old-props-after-datasource-reload-wb117d)

Please, first wait until data source is loaded.

1. When `PickerInput` has preselected value `["c-AF"]`
2. And `dataSource` is a shared as global variable
3. And I click "Reload data source" button
4. Then `dataSource.reload()` invoked
5. When data source is still loading 
6. And `value` changes programmatically to `[]`
7. And data source ends loading

## Actual result

8. Then `onValueChange` invokes with old value `["c-AF"]`

## Expected result

7. Then `onValueChange` invokes with current value `[]`

## Environment

* UUI version: 4.9.1
* Browser name: Firefox 108.0
* Operating System: Ubuntu 20.04

**Comment by AlekseyManetov** [comment]
Will be fixed in next release
