### ISSUE TITLE
[PickerInput] PickerInput in Dropdown isn't moving when scroll a page

### ISSUE THREAD

**Issue by ialeksandrovich** [epam/UUI#880]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Open dropdown
2. Open picker in dropdown
3. Scroll the page

## Actual result

Picker body isn't moving when scroll a page. There is a gap between picker toggler and body.

https://user-images.githubusercontent.com/18554835/211592512-2f01a566-a225-47ab-b123-d622ad4fcd2a.mp4

## Expected result

Picker body is moving when scroll a page. It should be near the picker toggler

## Environment

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* UUI version: 4.9.2
* Browser name: Chrome
* Operating System: Windows

**Comment by AlekseyManetov** [comment]
Hi, could you please provide video of wrong behavior?

**Comment by NatalliaAlieva** [comment]
Released in 4.10.0 version.
