### ISSUE TITLE
[Accordion] Can't be auto expanded by some trigger

### ISSUE THREAD

**Issue by DzmitryTrubchyk** [epam/UUI#881]
Please, see details below
![image](https://user-images.githubusercontent.com/44213241/208419058-b16615d9-058e-442e-880b-5dbb8aca4a27.png)

![image](https://user-images.githubusercontent.com/44213241/208419012-eeb351b4-bad9-4782-bcef-83b22d5c8a84.png)

**Comment by AlekseyManetov** [comment]
Let's implement `IEditable` interface for Accordion component. 
Also leave possibility to use Accordion without `IEditable` interface, in case when user didn't pass onValueChange - handle isOpen state via internal state(like in Dropdown component).

**Comment by Kunzetsov** [comment]
@AlekseyManetov, @DzmitryTrubchyk, this functionality is already implemented.

https://uui.epam.com/documents?id=accordion&mode=doc&skin=UUI4_promo&category=components#handle_accordion_state_by_yourself
