### ISSUE TITLE
PickerInput - enable renderFooter prop in mode='single

### ISSUE THREAD

**Issue by jakobz** [epam/UUI#883]
## Description

Currently, renderFooter prop is ignored in PickerInput, if mode='single'. That's because normally, single-pickers doesn't need footers - there's no 'show selected' / 'select all'.

However, a custom footer can be required even in single-pickers. 

Let's use renderFooter prop to render the footer in any case, if passed.

Let's also add examples to illustrate how to use it:
- a custom footer to replace the existing
- a custom footer to supplement the existing footer 

We need design with some real-world cases for this examples.

A sandbox to experiment with footers: https://codesandbox.io/s/uui-custom-pickerinput-footer-thltxp?file=/index.html

**Comment by Kuznietsov** [comment]
@DzmitryTrubchyk, could you, please, provide some real-world design examples? I'll implement it at the current PR. Thanks.

**Comment by Kuznietsov** [comment]
After a  short discussion, I've received new info about the decision to make a `Clear` footer as default for the `Single selection mode`.

cc @jakobz, @AlekseyManetov, @DzmitryTrubchyk.

**Comment by Kuznietsov** [comment]
Blocked by https://github.com/epam/UUI/pull/1249.

**Comment by AlekseyManetov** [comment]
Released in 5.0.0 ver.
