### ISSUE TITLE
[Vertical Tab Button]: text is trimmed in case of long caption

### ISSUE THREAD

**Issue by JuliaMV** [epam/UUI#889]
## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Open [Vertical Tab Button docs](https://uui.epam.com/documents?category=components&id=verticalTabButton&mode=propsEditor&skin=UUI4_promo)
2. Type long caption

## Actual result

Caption is partially hidden.

![2022-12-21_11h59_47](https://user-images.githubusercontent.com/37875890/208865274-f121ddd4-2386-403a-894b-b2c3beb4a25d.png)

## Expected result

Caption is visible and aligned correctly

## Environment

* UUI version: latest
* Browser name: any
* Operating System: any

**Comment by NatalliaAlieva** [comment]
Released in 4.10.0 version.
