### ISSUE TITLE
[DataTable] Checkbox alignment in case of column's textAlign prop is 'right' or 'center'

### ISSUE THREAD

**Issue by mari-shakhanava** [epam/UUI#891]
## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. There is DataTable with checkboxes, allowColumnsReordering={ true } prop, there is any column with textAlign prop 'right' or 'center'
2. Place column with textAlign prop 'right' or 'center' on the first place

## Actual result
Checkboxes are not align
![2022-12-20_16h53_10](https://user-images.githubusercontent.com/70166849/208876599-a0438f17-4c5c-4acb-9fcf-6814255a49af.png)

## Expected result
Checkboxes are align

## Environment
* UUI version: latest
* Browser name: any
* Operating System: any

**Comment by NatalliaAlieva** [comment]
Released in 4.10.1 ver.
