### ISSUE TITLE
[Switch] Unnecessary margin when `label` property is absent

### ISSUE THREAD

**Issue by vasilii-kovalev** [epam/UUI#900]
## Description

Since `label` property is optional, it can be absent. In this case, there is an unnecessary margin, which makes the component's width wider than it should be.

## Steps to Reproduce

1. Go to this [CodeSandbox](https://codesandbox.io/s/uui-switch-unnecessary-margin-issue-08nxn7?file=/Example.tsx)
2. Take a look at the example

## Actual result

The label's margin is present.

![image](https://user-images.githubusercontent.com/10310491/209509271-4156b1d7-6f6e-4bfc-b335-eeba7bf0c398.png)

## Expected result

There is no the label's margin.

## Environment

* UUI version: 4.9.2
* Browser name: Google Chrome v.108.0.5359.125
* Operating System: Windows 10 64-bit

**Comment by NatalliaAlieva** [comment]
Released in 4.10.0 version.
