### ISSUE TITLE
[FilterPanel] - improvements

### ISSUE THREAD

**Issue by jakobz** [epam/UUI#909]
## Description

For Learn project, to migrate to UUI Filter Panel, we need the following improvements of the existing components/hooks:

1. Store Sorting as a part of the preset
2. Review if we really need the tableState prop in the IPresetsBlockProps interface. Also, rename IPresetsBlockProps => PresetPanelProp?
3. To be decided: if Learn need to customize whether to save filters in URL

**Comment by AlekseyManetov** [comment]
implemented 1 and 2 point, 3 point decided as not critical for now and will be implemented in feature

**Comment by NatalliaAlieva** [comment]
Released in 4.10.0 version.
