### ISSUE TITLE
[Table Column settings] Fix vertical padding

### ISSUE THREAD

**Issue by DzmitryTrubchyk** [epam/UUI#941]
Vertical padding between sections should be 12px
[Find design here](https://www.figma.com/file/yph0lYTxCIM3GWExIVeNAb/UUI-%E2%80%93-Tables-Examples?node-id=2467%3A689874&t=bIdJY4cX7sf6YJJl-4)
![image](https://user-images.githubusercontent.com/44213241/212041097-e78ac1ba-e4c6-4460-b2d8-d5715fc77442.png)

**Comment by NatalliaAlieva** [comment]
Released in 4.10.0 version.
