### ISSUE TITLE
[Rating] Background for selected stars was broken in loveship

### ISSUE THREAD

**Issue by nadiushkaNA** [epam/UUI#943]
## Description
Background for selected stars was broken in loveship

## Steps to Reproduce

go to https://uui.epam.com/documents?category=components&id=rating&mode=propsEditor&skin=UUI3_loveship

## Actual result

What is the current behavior?

![image](https://user-images.githubusercontent.com/11243577/212057325-e58bb5d1-45bf-458a-8b53-047a93a22189.png)

## Expected result

![image](https://user-images.githubusercontent.com/11243577/212057439-c0dffc0e-6906-4bca-a8eb-150d99f2e87f.png)

**Comment by NatalliaAlieva** [comment]
Released in 4.10.0 version.
