### ISSUE TITLE
[LinkButton] Property captionCX does not work for LinkButton component

### ISSUE THREAD

**Issue by AnastasiyaMazura** [epam/UUI#966]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [+] I am running the latest version
- [+] I checked the documentation and found no answer
- [+] I checked to make sure that this issue has not already been filed

## Description

Styles for caption of LinkButton component cannot be applied.
Any value added to captionCX property will not be shown in html.

## Environment

* UUI version:
    "@epam/assets": "^4.9.1",
    "@epam/loveship": "^4.9.2",
    "@epam/uui": "^4.9.2",
    "@epam/uui-components": "^4.9.2",
    "@epam/uui-core": "^4.9.2",
* Browser name: Google Chrome Version 108.0.5359.124 (Official Build) (x86_64)
* Operating System: macOS Ventura 13.1

**Comment by dsv-sergey** [comment]
One of the possible solutions
![image](https://user-images.githubusercontent.com/33173033/212929569-7abf07fc-b827-4495-b696-ad8137da6182.png)

**Comment by AlekseyManetov** [comment]
`captionCx` is internal technical prop, which will be removed in feature. Better pass class which cascade to '.uui-caption' selector via `cx` prop.
