### ISSUE TITLE
[MainMenu] MainMenuDropdown not closing on route change

### ISSUE THREAD

**Issue by shushenchik** [epam/UUI#967]
## Description

After upgrading to v4.9.2 and passing menu items to the `MainMenu` component as `items` prop (not as children), the `MainMenuDropdown` component stopped closing on route change.

## Actual result

Here is the sandbox demonstrating this behavior:

- v4.9.2, items as prop: https://codesandbox.io/s/uui-v4-9-2-mainmenu-h1vxbm

## Expected result

Menu dropdowns should be closed on route change, as it worked in the previous version of UUI:

- v4.8.5, items as children: https://codesandbox.io/s/uui-v4-8-5-mainmenu-emkmc1

## Environment

* UUI version: v4.9.2
* Browser name: Chrome 108
* Operating System: Windows 10

**Comment by NatalliaAlieva** [comment]
Released in 5.0.0 ver.
